// =============================================================================
// ExamVault - Real Indian Exam Seed Data
// =============================================================================
// This module contains real Indian exam-prep data for seeding Firestore:
//   - 7 categories (LIC, SSC, Banking, UPSC, Assam APSC, WBCS, UPPSC)
//   - 14 subjects (2 per category)
//   - 14 tests (1 per subject)
//   - 70 questions (5 per test)
//   - 5 banners (homepage promotional)
//   - 8 announcements (exam notifications)
//   - 10 upcoming exams (real 2025-2026 schedules)
//
// Indian Railways category already exists in Firestore — skipped here.
//
// All image URLs are from Wikimedia Commons (public domain / CC) or
// Unsplash (free to use). Replace with your own CDN URLs anytime.
// =============================================================================

export interface SeedCategory {
  name: string;
  slug: string;
  icon: string;       // emoji
  description: string;
  image: string;      // URL
  color: string;      // hex
  order: number;
  isPremium: boolean;
  premiumPrice: number;
  premiumDurationMonths: number;
  subjects: SeedSubject[];
}

export interface SeedSubject {
  name: string;
  slug: string;
  icon: string;
  description: string;
  order: number;
  tests: SeedTest[];
}

export interface SeedTest {
  title: string;
  slug: string;
  type: string;       // 'mock' | 'previous' | 'practice'
  duration: number;   // minutes
  totalMarks: number;
  passingMarks: number;
  isPublished: boolean;
  difficulty: string; // 'easy' | 'medium' | 'hard'
  negativeMarking: boolean;
  negativeMarks: number;
  instructions: string;
  year: number;
  examSession: string;
  isPremium: boolean;
  price: number;
  questions: SeedQuestion[];
}

export interface SeedQuestion {
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  subjectTopic: string;
  marks: number;
  isPremium: boolean;
}

export interface SeedBanner {
  title: string;
  subtitle: string;
  imageUrl: string;
  link: string;
  linkLabel: string;
  order: number;
  isActive: boolean;
  startsAt: string;   // ISO date
  endsAt: string;     // ISO date
}

export interface SeedAnnouncement {
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'promo';
  imageUrl: string;
  link: string;
  linkLabel: string;
  isPinned: boolean;
  isPublished: boolean;
  order: number;
  expiresAt: string;
}

export interface SeedUpcomingExam {
  name: string;
  organization: string;
  categoryIdSlug: string; // matches category slug above
  examDate: string;
  applicationStartDate: string;
  applicationEndDate: string;
  notificationUrl: string;
  syllabusUrl: string;
  imageUrl: string;
  description: string;
  tags: string[];
  isPublished: boolean;
  order: number;
}

// =============================================================================
// CATEGORIES (7 new — Indian Railways already exists, skipped)
// =============================================================================

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: 'LIC',
    slug: 'lic',
    icon: '🛡️',
    description: 'Life Insurance Corporation of India — recruitment exams for AAO, ADO, and Assistant posts. Covers insurance awareness, general awareness, quantitative aptitude, and reasoning.',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    color: '#0d9488',
    order: 10,
    isPremium: false,
    premiumPrice: 99,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'Insurance Awareness',
        slug: 'lic-insurance-awareness',
        icon: '📋',
        description: 'Insurance principles, LIC products, IRDAI regulations, and insurance history.',
        order: 1,
        tests: [
          {
            title: 'LIC AAO Prelims Mock Test 1',
            slug: 'lic-aao-prelims-mock-1',
            type: 'mock',
            duration: 60,
            totalMarks: 100,
            passingMarks: 40,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: true,
            negativeMarks: 0.25,
            instructions: 'Total 60 minutes. Each question carries 1 mark. 0.25 marks deducted for each wrong answer.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'In which year was the Life Insurance Corporation of India (LIC) established?',
                options: ['1947', '1956', '1969', '1972'],
                correctAnswerIndex: 1,
                explanation: 'LIC was established on 1st September 1956 after the Parliament of India passed the Life Insurance Corporation Act, 1956, nationalizing the insurance industry in India.',
                subjectTopic: 'LIC History',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'What does the acronym "IRDAI" stand for?',
                options: [
                  'Insurance Regulatory and Development Authority of India',
                  'Indian Risk and Development Authority of Insurance',
                  'Insurance Regulation and Distribution Agency of India',
                  'Indian Regulatory Department of Assurance and Insurance',
                ],
                correctAnswerIndex: 0,
                explanation: 'IRDAI is the Insurance Regulatory and Development Authority of India, an autonomous apex statutory body that regulates and develops the insurance industry in India.',
                subjectTopic: 'Insurance Regulation',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Where is the headquarters of the Life Insurance Corporation of India located?',
                options: ['New Delhi', 'Kolkata', 'Mumbai', 'Chennai'],
                correctAnswerIndex: 2,
                explanation: 'LIC is headquartered in Mumbai, Maharashtra. Its central office is located at "Yogakshema", Jeevan Bima Marg.',
                subjectTopic: 'LIC Organization',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Which of the following is NOT a type of life insurance policy offered by LIC?',
                options: ['Term Insurance', 'Whole Life Policy', 'Endowment Policy', 'Crop Insurance'],
                correctAnswerIndex: 3,
                explanation: 'Crop Insurance is a general (non-life) insurance product, typically offered by companies like Agriculture Insurance Company of India, not LIC which deals in life insurance.',
                subjectTopic: 'LIC Products',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'What is the minimum entry age for most LIC life insurance policies?',
                options: ['12 years', '18 years', '21 years', '25 years'],
                correctAnswerIndex: 1,
                explanation: 'The minimum entry age for most LIC life insurance policies is 18 years. Some child plans allow entry from 90 days, but standard adult policies require the policyholder to be at least 18.',
                subjectTopic: 'LIC Policies',
                marks: 1,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'Quantitative Aptitude',
        slug: 'lic-quantitative-aptitude',
        icon: '🔢',
        description: 'Number system, percentage, profit & loss, time & work, and data interpretation for LIC exams.',
        order: 2,
        tests: [
          {
            title: 'LIC ADO Quant Practice Test',
            slug: 'lic-ado-quant-practice',
            type: 'practice',
            duration: 30,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '30 minutes. 50 questions, each 1 mark. No negative marking.',
            year: 2025,
            examSession: 'Practice',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'A man buys an article for ₹800 and sells it for ₹1000. What is his profit percentage?',
                options: ['20%', '25%', '30%', '15%'],
                correctAnswerIndex: 1,
                explanation: 'Profit = 1000 - 800 = ₹200. Profit % = (200/800) × 100 = 25%.',
                subjectTopic: 'Profit and Loss',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'If 15 men can complete a work in 20 days, how many days will 10 men take to complete the same work?',
                options: ['25 days', '30 days', '35 days', '40 days'],
                correctAnswerIndex: 1,
                explanation: 'Work = 15 × 20 = 300 man-days. Days required for 10 men = 300/10 = 30 days.',
                subjectTopic: 'Time and Work',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'What is 25% of 480?',
                options: ['100', '110', '120', '130'],
                correctAnswerIndex: 2,
                explanation: '25% of 480 = (25/100) × 480 = 120.',
                subjectTopic: 'Percentage',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'The simple interest on ₹5000 at 8% per annum for 2 years is:',
                options: ['₹600', '₹700', '₹800', '₹900'],
                correctAnswerIndex: 2,
                explanation: 'SI = (P × R × T)/100 = (5000 × 8 × 2)/100 = ₹800.',
                subjectTopic: 'Simple Interest',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'If the ratio of two numbers is 3:5 and their sum is 64, what is the smaller number?',
                options: ['18', '24', '30', '36'],
                correctAnswerIndex: 1,
                explanation: 'Let numbers be 3x and 5x. 3x + 5x = 64 → 8x = 64 → x = 8. Smaller number = 3 × 8 = 24.',
                subjectTopic: 'Ratio and Proportion',
                marks: 1,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'SSC',
    slug: 'ssc',
    icon: '📋',
    description: 'Staff Selection Commission — recruitment exams for Group B and C posts in various Government of India ministries and departments. Includes CGL, CHSL, MTS, and GD.',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    color: '#059669',
    order: 11,
    isPremium: false,
    premiumPrice: 99,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'General Intelligence & Reasoning',
        slug: 'ssc-general-intelligence',
        icon: '🧠',
        description: 'Verbal and non-verbal reasoning, analogies, classification, series, coding-decoding.',
        order: 1,
        tests: [
          {
            title: 'SSC CGL Tier 1 Reasoning Mock',
            slug: 'ssc-cgl-tier1-reasoning-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: true,
            negativeMarks: 0.5,
            instructions: '25 minutes, 25 questions. Each question 2 marks. 0.5 marks deducted for wrong answers.',
            year: 2025,
            examSession: 'Tier 1',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'Find the next number in the series: 2, 6, 12, 20, 30, ?',
                options: ['40', '42', '44', '46'],
                correctAnswerIndex: 1,
                explanation: 'Differences: 4, 6, 8, 10, 12. Next number = 30 + 12 = 42.',
                subjectTopic: 'Number Series',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'If "CAT" is coded as "DBU", how is "DOG" coded?',
                options: ['EPH', 'EPG', 'DPH', 'EOH'],
                correctAnswerIndex: 0,
                explanation: 'Each letter shifts by +1: D→C+1, O→D+1... wait. C→D, A→B, T→U. So D→E, O→P, G→H. Answer: EPH.',
                subjectTopic: 'Coding-Decoding',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which number does not belong: 4, 9, 16, 23, 25, 36?',
                options: ['4', '16', '23', '36'],
                correctAnswerIndex: 2,
                explanation: 'All except 23 are perfect squares (2², 3², 4², 5², 6²). 23 is not a perfect square.',
                subjectTopic: 'Classification',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Pointing to a photograph, a man said, "She is the daughter of my grandfather\'s only son." How is the girl related to the man?',
                options: ['Sister', 'Daughter', 'Niece', 'Cousin'],
                correctAnswerIndex: 0,
                explanation: 'Grandfather\'s only son = the man\'s father (or the man himself). The daughter of his father could be his sister. If it were himself, he\'d say "daughter". So sister is most consistent in SSC convention.',
                subjectTopic: 'Blood Relations',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Complete the analogy: Book : Author :: Painting : ?',
                options: ['Brush', 'Canvas', 'Painter', 'Colour'],
                correctAnswerIndex: 2,
                explanation: 'A book is created by an author. A painting is created by a painter.',
                subjectTopic: 'Analogies',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'General Awareness',
        slug: 'ssc-general-awareness',
        icon: '🌍',
        description: 'Indian history, geography, polity, economy, science, and current affairs.',
        order: 2,
        tests: [
          {
            title: 'SSC CGL General Awareness Mock',
            slug: 'ssc-cgl-ga-mock',
            type: 'mock',
            duration: 20,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '20 minutes, 25 questions. No negative marking. Test your general awareness.',
            year: 2025,
            examSession: 'Tier 1',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'Who was the first President of independent India?',
                options: ['Dr. Rajendra Prasad', 'Dr. S. Radhakrishnan', 'Jawaharlal Nehru', 'Sardar Patel'],
                correctAnswerIndex: 0,
                explanation: 'Dr. Rajendra Prasad was the first President of India, serving from 1950 to 1962.',
                subjectTopic: 'Indian Polity',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which Article of the Indian Constitution abolishes untouchability?',
                options: ['Article 14', 'Article 15', 'Article 17', 'Article 21'],
                correctAnswerIndex: 2,
                explanation: 'Article 17 abolishes untouchability and forbids its practice in any form.',
                subjectTopic: 'Indian Polity',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Battle of Plassey was fought in which year?',
                options: ['1757', '1761', '1764', '1857'],
                correctAnswerIndex: 0,
                explanation: 'The Battle of Plassey was fought on 23 June 1757 between the British East India Company and the Nawab of Bengal, Siraj-ud-Daulah.',
                subjectTopic: 'Indian History',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which is the longest river in India?',
                options: ['Yamuna', 'Ganga', 'Godavari', 'Brahmaputra'],
                correctAnswerIndex: 1,
                explanation: 'The Ganga (Ganges) is the longest river in India, flowing approximately 2,525 km from Gangotri to the Bay of Bengal.',
                subjectTopic: 'Indian Geography',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who is known as the "Missile Man of India"?',
                options: ['Homi Bhabha', 'Vikram Sarabhai', 'Dr. A.P.J. Abdul Kalam', 'C.V. Raman'],
                correctAnswerIndex: 2,
                explanation: 'Dr. A.P.J. Abdul Kalam was known as the "Missile Man of India" for his work on ballistic missile technology. He later became the 11th President of India.',
                subjectTopic: 'Indian Personalities',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'Banking',
    slug: 'banking',
    icon: '🏦',
    description: 'Banking sector recruitment exams — IBPS PO, IBPS Clerk, SBI PO, SBI Clerk, and RBI Grade B. Covers banking awareness, quantitative aptitude, reasoning, and English.',
    image: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    color: '#7c3aed',
    order: 12,
    isPremium: false,
    premiumPrice: 99,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'Banking Awareness',
        slug: 'banking-awareness',
        icon: '💰',
        description: 'Indian banking system, RBI functions, monetary policy, banking products, and financial awareness.',
        order: 1,
        tests: [
          {
            title: 'IBPS PO Banking Awareness Mock',
            slug: 'ibps-po-banking-awareness-mock',
            type: 'mock',
            duration: 20,
            totalMarks: 40,
            passingMarks: 16,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '20 minutes, 40 questions. Each question 1 mark. No negative marking.',
            year: 2025,
            examSession: 'Mains',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'In which year was the Reserve Bank of India (RBI) established?',
                options: ['1935', '1947', '1949', '1969'],
                correctAnswerIndex: 0,
                explanation: 'The RBI was established on 1st April 1935 under the Reserve Bank of India Act, 1934. It was nationalized on 1st January 1949.',
                subjectTopic: 'RBI History',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'What is the full form of NEFT?',
                options: [
                  'National Electronic Funds Transfer',
                  'New Electronic Financial Transaction',
                  'National Electronic Finance Transfer',
                  'Network Electronic Funds Transfer',
                ],
                correctAnswerIndex: 0,
                explanation: 'NEFT stands for National Electronic Funds Transfer, a nationwide payment system facilitating one-to-one funds transfer.',
                subjectTopic: 'Banking Terms',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Who is the current Governor of the Reserve Bank of India (as of 2025)?',
                options: ['Shaktikanta Das', 'Urjit Patel', 'Raghuram Rajan', 'Sanjay Malhotra'],
                correctAnswerIndex: 3,
                explanation: 'Sanjay Malhotra became the 26th RBI Governor in December 2024, succeeding Shaktikanta Das.',
                subjectTopic: 'RBI Current Affairs',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'What is the minimum paid-up capital required for a Small Finance Bank in India?',
                options: ['₹100 crore', '₹200 crore', '₹500 crore', '₹1000 crore'],
                correctAnswerIndex: 1,
                explanation: 'Small Finance Banks require a minimum paid-up equity capital of ₹200 crore as per RBI guidelines.',
                subjectTopic: 'Banking Regulations',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Which committee recommended the introduction of the Goods and Services Tax (GST)?',
                options: ['Kelkar Committee', 'Chelliah Committee', 'Raja Chelliah Committee', 'Narasimham Committee'],
                correctAnswerIndex: 0,
                explanation: 'The Vijay L. Kelkar Task Force (2002) was the first to recommend a comprehensive GST in India.',
                subjectTopic: 'Indian Economy',
                marks: 1,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'English Language',
        slug: 'banking-english',
        icon: '📖',
        description: 'Reading comprehension, cloze test, error spotting, sentence improvement, and vocabulary.',
        order: 2,
        tests: [
          {
            title: 'SBI PO English Practice Test',
            slug: 'sbi-po-english-practice',
            type: 'practice',
            duration: 30,
            totalMarks: 30,
            passingMarks: 12,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: true,
            negativeMarks: 0.25,
            instructions: '30 minutes, 30 questions. Each question 1 mark. 0.25 marks deducted for wrong answers.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'Choose the correct synonym of "ABUNDANT":',
                options: ['Scarce', 'Plentiful', 'Insufficient', 'Limited'],
                correctAnswerIndex: 1,
                explanation: '"Abundant" means existing in large quantities; plentiful.',
                subjectTopic: 'Synonyms',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Choose the correct antonym of "TRANSPARENT":',
                options: ['Clear', 'Opaque', 'Visible', 'Bright'],
                correctAnswerIndex: 1,
                explanation: '"Transparent" means allowing light to pass through so objects can be seen. Its antonym is "opaque" — not transparent.',
                subjectTopic: 'Antonyms',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Fill in the blank: "She has been working here ____ 2018."',
                options: ['since', 'for', 'from', 'by'],
                correctAnswerIndex: 0,
                explanation: '"Since" is used with a specific point in time (2018). "For" is used with a duration.',
                subjectTopic: 'Prepositions',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Identify the error in: "One of the boys have broken the window."',
                options: [
                  '"One of" should be "One off"',
                  '"the boys" should be "the boy"',
                  '"have" should be "has"',
                  'No error',
                ],
                correctAnswerIndex: 2,
                explanation: 'The subject is "One of the boys" — "One" is singular, so the verb should be "has", not "have".',
                subjectTopic: 'Error Spotting',
                marks: 1,
                isPremium: false,
              },
              {
                question: 'Choose the correct meaning of the idiom "To bite the bullet":',
                options: [
                  'To eat quickly',
                  'To face a difficult situation bravely',
                  'To be aggressive',
                  'To make a mistake',
                ],
                correctAnswerIndex: 1,
                explanation: '"To bite the bullet" means to endure a painful or difficult situation with courage.',
                subjectTopic: 'Idioms',
                marks: 1,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'UPSC',
    slug: 'upsc',
    icon: '🎓',
    description: 'Union Public Service Commission — Civil Services Examination (CSE) for IAS, IPS, IFS, and other Group A services. Also covers CDS, NDA, and CAPF exams.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    color: '#ea580c',
    order: 13,
    isPremium: true,
    premiumPrice: 149,
    premiumDurationMonths: 3,
    subjects: [
      {
        name: 'Indian Polity',
        slug: 'upsc-indian-polity',
        icon: '⚖️',
        description: 'Constitution, fundamental rights, DPSP, parliament, judiciary, federalism, and local government.',
        order: 1,
        tests: [
          {
            title: 'UPSC CSE Prelims Polity Mock Test',
            slug: 'upsc-cse-prelims-polity-mock',
            type: 'mock',
            duration: 30,
            totalMarks: 50,
            passingMarks: 25,
            isPublished: true,
            difficulty: 'hard',
            negativeMarking: true,
            negativeMarks: 0.33,
            instructions: '30 minutes, 25 questions. Each question 2 marks. 0.33 marks deducted for wrong answers.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 99,
            questions: [
              {
                question: 'Which Article of the Indian Constitution deals with the Right to Constitutional Remedies?',
                options: ['Article 19', 'Article 21', 'Article 32', 'Article 226'],
                correctAnswerIndex: 2,
                explanation: 'Article 32 provides the Right to Constitutional Remedies, allowing citizens to approach the Supreme Court directly for enforcement of fundamental rights. Dr. Ambedkar called it the "heart and soul" of the Constitution.',
                subjectTopic: 'Fundamental Rights',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'How many members are nominated to the Rajya Sabha by the President of India?',
                options: ['10', '12', '14', '15'],
                correctAnswerIndex: 1,
                explanation: 'The President nominates 12 members to the Rajya Sabha from persons having special knowledge or practical experience in literature, science, art, and social service.',
                subjectTopic: 'Parliament',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The concept of "Directive Principles of State Policy" in the Indian Constitution is borrowed from which country?',
                options: ['United States', 'United Kingdom', 'Ireland', 'Canada'],
                correctAnswerIndex: 2,
                explanation: 'The Directive Principles of State Policy (Part IV, Articles 36-51) are borrowed from the Irish Constitution.',
                subjectTopic: 'Constitution Sources',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who is the head of the Indian Republic?',
                options: ['Prime Minister', 'President', 'Chief Justice of India', 'Speaker of Lok Sabha'],
                correctAnswerIndex: 1,
                explanation: 'The President of India is the constitutional head of the Indian Republic. The executive power is exercised in the name of the President.',
                subjectTopic: 'Executive',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which Constitutional Amendment introduced the Anti-Defection Law in India?',
                options: ['42nd Amendment', '44th Amendment', '52nd Amendment', '61st Amendment'],
                correctAnswerIndex: 2,
                explanation: 'The 52nd Constitutional Amendment Act, 1985 introduced the Anti-Defection Law by adding the Tenth Schedule to the Constitution.',
                subjectTopic: 'Constitutional Amendments',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'Indian History',
        slug: 'upsc-indian-history',
        icon: '📜',
        description: 'Ancient, medieval, and modern Indian history, freedom struggle, and post-independence India.',
        order: 2,
        tests: [
          {
            title: 'UPSC CSE Modern History Mock',
            slug: 'upsc-cse-modern-history-mock',
            type: 'mock',
            duration: 30,
            totalMarks: 50,
            passingMarks: 25,
            isPublished: true,
            difficulty: 'hard',
            negativeMarking: true,
            negativeMarks: 0.33,
            instructions: '30 minutes, 25 questions. Each question 2 marks. 0.33 marks deducted for wrong answers.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 99,
            questions: [
              {
                question: 'Who founded the Indian National Congress in 1885?',
                options: ['A.O. Hume', 'Dadabhai Naoroji', 'W.C. Bonnerjee', 'Surendranath Banerjee'],
                correctAnswerIndex: 0,
                explanation: 'Allan Octavian Hume, a retired British civil servant, founded the Indian National Congress in 1885. W.C. Bonnerjee was the first president.',
                subjectTopic: 'Freedom Struggle',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Non-Cooperation Movement was launched by Mahatma Gandhi in which year?',
                options: ['1919', '1920', '1922', '1930'],
                correctAnswerIndex: 1,
                explanation: 'The Non-Cooperation Movement was launched in September 1920 and was withdrawn in February 1922 after the Chauri Chaura incident.',
                subjectTopic: 'Freedom Struggle',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who was the first Governor-General of independent India?',
                options: ['Lord Mountbatten', 'C. Rajagopalachari', 'Lord Wavell', 'Rajendra Prasad'],
                correctAnswerIndex: 0,
                explanation: 'Lord Mountbatten was the first Governor-General of independent India (1947-48). C. Rajagopalachari succeeded him as the first Indian Governor-General.',
                subjectTopic: 'Post-Independence',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Quit India Movement was launched in which year?',
                options: ['1930', '1935', '1942', '1945'],
                correctAnswerIndex: 2,
                explanation: 'The Quit India Movement was launched on 8th August 1942 by Mahatma Gandhi with the slogan "Do or Die" ("Karenge ya Marenge").',
                subjectTopic: 'Freedom Struggle',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who wrote the book "Discovery of India"?',
                options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Subhas Chandra Bose'],
                correctAnswerIndex: 1,
                explanation: '"The Discovery of India" was written by Jawaharlal Nehru during his imprisonment in Ahmednagar Fort prison in 1944.',
                subjectTopic: 'Indian Literature',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'Assam (APSC)',
    slug: 'assam-apsc',
    icon: '🗺️',
    description: 'Assam Public Service Commission — Combined Competitive Examination (CCE) for ACS, APS, and other state civil services. Covers Assam history, geography, polity, and general studies.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    color: '#dc2626',
    order: 14,
    isPremium: false,
    premiumPrice: 79,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'Assam History & Culture',
        slug: 'assam-history-culture',
        icon: '🎭',
        description: 'Ahom kingdom, Assam\'s freedom struggle, cultural heritage, Bihu, Satriya, and Assamese literature.',
        order: 1,
        tests: [
          {
            title: 'APSC CCE Assam History Mock',
            slug: 'apsc-cce-assam-history-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'Who was the founder of the Ahom Kingdom in Assam?',
                options: ['Sukapha', 'Suhungmung', 'Pratap Singha', 'Rudra Singha'],
                correctAnswerIndex: 0,
                explanation: 'Chaolung Sukapha founded the Ahom Kingdom in 1228 CE, crossing the Patkai mountains from Mong Mao. He is considered the architect of greater Assam.',
                subjectTopic: 'Ahom Kingdom',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which Mughal general was defeated by the Ahoms in the Battle of Saraighat (1671)?',
                options: ['Mir Jumla', 'Ram Singh', 'Shaista Khan', 'Man Singh'],
                correctAnswerIndex: 1,
                explanation: 'The Ahoms led by Lachit Borphukan defeated the Mughal forces led by Ram Singh (Raja Ram Singh I of Amber) in the famous Battle of Saraighat in 1671 on the Brahmaputra river.',
                subjectTopic: 'Ahom-Mughal Conflicts',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Bihu, the major festival of Assam, is primarily associated with:',
                options: ['Harvest', 'New Year', 'Victory', 'Marriage'],
                correctAnswerIndex: 0,
                explanation: 'Bihu is primarily a harvest festival. Rongali/Bohag Bihu marks the Assamese New Year and the spring harvest, while Kati Bihu and Magh Bihu mark other agricultural stages.',
                subjectTopic: 'Assam Culture',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who composed the "Buranjis", the historical chronicles of the Ahom kingdom?',
                options: ['Ahom scribes', 'Brahmin priests', 'Buddhist monks', 'Mughal historians'],
                correctAnswerIndex: 0,
                explanation: 'Buranjis were written by Ahom scribes and officials. These chronicles in Assamese language recorded political, social, and administrative events — a unique historical tradition.',
                subjectTopic: 'Ahom Literature',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Assam Agitation (1979-1985) was primarily aimed at:',
                options: [
                  'Detecting and deporting foreign nationals',
                  'Demanding statehood',
                  'Protesting against British rule',
                  'Demanding separate flag',
                ],
                correctAnswerIndex: 0,
                explanation: 'The Assam Agitation (Assam Movement) was a 6-year-long popular movement against illegal immigration, demanding detection and deportation of foreign nationals from the electoral rolls.',
                subjectTopic: 'Modern Assam',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'Assam Geography & Economy',
        slug: 'assam-geography-economy',
        icon: '🏞️',
        description: 'Physical geography, rivers, climate, agriculture, tea industry, oil, and Assam\'s economic development.',
        order: 2,
        tests: [
          {
            title: 'APSC Assam Geography Mock',
            slug: 'apsc-assam-geography-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'Which is the longest river in Assam?',
                options: ['Brahmaputra', 'Barak', 'Subansiri', 'Dibang'],
                correctAnswerIndex: 0,
                explanation: 'The Brahmaputra is the longest river in Assam, flowing about 725 km through the state. It is called "Luit" in Assamese.',
                subjectTopic: 'Assam Rivers',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which national park in Assam is famous for the one-horned Indian rhinoceros?',
                options: ['Manas National Park', 'Kaziranga National Park', 'Dibru-Saikhowa', 'Nameri National Park'],
                correctAnswerIndex: 1,
                explanation: 'Kaziranga National Park is a UNESCO World Heritage Site, home to two-thirds of the world\'s population of one-horned rhinoceroses.',
                subjectTopic: 'Assam Wildlife',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Assam is the largest producer of which commodity in India?',
                options: ['Tea', 'Coffee', 'Rubber', 'Cotton'],
                correctAnswerIndex: 0,
                explanation: 'Assam is the largest tea-producing state in India, accounting for over 50% of India\'s tea production. Assam tea is famous worldwide for its strong, malty flavor.',
                subjectTopic: 'Assam Economy',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Where is the headquarters of Oil India Limited (OIL) located?',
                options: ['Guwahati', 'Duliajan', 'Digboi', 'Nazira'],
                correctAnswerIndex: 1,
                explanation: 'Oil India Limited is headquartered in Duliajan, Dibrugarh district, Assam. Digboi has Asia\'s first oil refinery (1901).',
                subjectTopic: 'Assam Industry',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which district of Assam is famous for the Majuli river island?',
                options: ['Dibrugarh', 'Jorhat', 'Majuli', 'Sivasagar'],
                correctAnswerIndex: 2,
                explanation: 'Majuli is the largest river island in the world, located in the Brahmaputra river. It became a separate district in 2016 and is known for its Vaishnavite Satras.',
                subjectTopic: 'Assam Geography',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'West Bengal (WBCS)',
    slug: 'wbcs',
    icon: '📚',
    description: 'West Bengal Civil Service Examination — recruitment for WBCS (Executive), WB Audit & Accounts Service, and other state Group A, B, C, D services.',
    image: 'https://images.unsplash.com/photo-1577563908413-9a595f754d00?w=800&q=80',
    color: '#be123c',
    order: 15,
    isPremium: false,
    premiumPrice: 79,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'Bengal History & Culture',
        slug: 'wbcs-bengal-history',
        icon: '🏛️',
        description: 'Bengal Renaissance, freedom movement in Bengal, Bengali literature, and cultural heritage.',
        order: 1,
        tests: [
          {
            title: 'WBCS Bengal History Mock Test',
            slug: 'wbcs-bengal-history-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'Who is known as the "Rishi of Bengal Renaissance"?',
                options: ['Rabindranath Tagore', 'Raja Ram Mohan Roy', 'Ishwar Chandra Vidyasagar', 'Swami Vivekananda'],
                correctAnswerIndex: 1,
                explanation: 'Raja Ram Mohan Roy (1772-1833) is called the "Father of the Bengal Renaissance" and "Rishi of Bengal Renaissance". He founded the Brahmo Sabha in 1828.',
                subjectTopic: 'Bengal Renaissance',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Where was the first session of the Indian National Congress held in 1885?',
                options: ['Delhi', 'Calcutta', 'Bombay', 'Madras'],
                correctAnswerIndex: 2,
                explanation: 'The first session of the Indian National Congress was held at Gokuldas Tejpal Sanskrit College in Bombay (now Mumbai) in December 1885, with W.C. Bonnerjee as president.',
                subjectTopic: 'Freedom Struggle',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who composed "Vande Mataram", the national song of India?',
                options: ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarat Chandra Chattopadhyay', 'Kazi Nazrul Islam'],
                correctAnswerIndex: 1,
                explanation: 'Bankim Chandra Chattopadhyay composed "Vande Mataram", which appears in his 1882 novel "Anandamath". It was adopted as India\'s national song in 1950.',
                subjectTopic: 'Bengali Literature',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Alipore Bomb Case (1908) was associated with which revolutionary?',
                options: ['Bhagat Singh', 'Aurobindo Ghosh', 'Chandrashekhar Azad', 'Subhas Chandra Bose'],
                correctAnswerIndex: 1,
                explanation: 'The Alipore Bomb Case (1908-09) involved Aurobindo Ghosh and his brother Barindra Kumar Ghosh, following the Muzaffarpur bombing attempt. Aurobindo was acquitted.',
                subjectTopic: 'Revolutionary Movement',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who founded the Indian Statistical Institute (ISI) in Calcutta?',
                options: ['C.R. Rao', 'P.C. Mahalanobis', 'S.N. Bose', 'Meghnad Saha'],
                correctAnswerIndex: 1,
                explanation: 'Prasanta Chandra Mahalanobis founded the Indian Statistical Institute (ISI) in Calcutta on 17th December 1931. He is known as the father of Indian statistics.',
                subjectTopic: 'Bengal Intellectuals',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'Indian Polity & Governance',
        slug: 'wbcs-indian-polity',
        icon: '⚖️',
        description: 'Constitution, central and state government structure, panchayati raj, and West Bengal state administration.',
        order: 2,
        tests: [
          {
            title: 'WBCS Indian Polity Mock',
            slug: 'wbcs-indian-polity-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'How many seats are reserved for Scheduled Castes in the West Bengal Legislative Assembly?',
                options: ['52', '68', '76', '85'],
                correctAnswerIndex: 1,
                explanation: '68 seats are reserved for Scheduled Castes in the 294-member West Bengal Legislative Assembly, as per delimitation.',
                subjectTopic: 'West Bengal Polity',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'When was the Panchayati Raj System introduced in India through Constitutional Amendment?',
                options: ['1989 (64th Amendment)', '1992 (73rd Amendment)', '1995 (76th Amendment)', '2001 (86th Amendment)'],
                correctAnswerIndex: 1,
                explanation: 'The 73rd Constitutional Amendment Act, 1992 introduced the Panchayati Raj System as Part IX of the Constitution, with Articles 243 to 243-O.',
                subjectTopic: 'Local Government',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who is the executive head of a state government in India?',
                options: ['Chief Minister', 'Governor', 'President', 'Cabinet Secretary'],
                correctAnswerIndex: 1,
                explanation: 'The Governor is the executive head of a state, appointed by the President. The Chief Minister is the head of the council of ministers, the real executive authority.',
                subjectTopic: 'State Executive',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which Schedule of the Indian Constitution deals with Panchayati Raj?',
                options: ['Ninth Schedule', 'Tenth Schedule', 'Eleventh Schedule', 'Twelfth Schedule'],
                correctAnswerIndex: 2,
                explanation: 'The Eleventh Schedule (added by 73rd Amendment, 1992) deals with Panchayati Raj, listing 29 subjects. Twelfth Schedule deals with Municipalities (74th Amendment).',
                subjectTopic: 'Constitutional Schedules',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Right to Information (RTI) Act was enacted in which year?',
                options: ['2002', '2005', '2008', '2010'],
                correctAnswerIndex: 1,
                explanation: 'The Right to Information Act was enacted by Parliament in 2005, coming into force on 12th October 2005. It mandates timely response to citizen requests for information.',
                subjectTopic: 'Good Governance',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'Uttar Pradesh (UPPSC)',
    slug: 'uppsc',
    icon: '🏛️',
    description: 'Uttar Pradesh Public Service Commission — Provincial Civil Service (PCS) and other state civil services recruitment. Includes RO/ARO, Upper Subordinate, and Lower Subordinate exams.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    color: '#c2410c',
    order: 16,
    isPremium: false,
    premiumPrice: 79,
    premiumDurationMonths: 1,
    subjects: [
      {
        name: 'UP History & Culture',
        slug: 'uppsc-up-history',
        icon: '🏰',
        description: 'Mughal era, Awadh region, 1857 revolt, UP\'s role in freedom struggle, and cultural heritage.',
        order: 1,
        tests: [
          {
            title: 'UPPSC PCS UP History Mock',
            slug: 'uppsc-pcs-up-history-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: false,
            price: 0,
            questions: [
              {
                question: 'The Indian Rebellion of 1857 began from which cantonment in Uttar Pradesh?',
                options: ['Bareilly', 'Meerut', 'Kanpur', 'Lucknow'],
                correctAnswerIndex: 1,
                explanation: 'The 1857 Revolt began on 10th May 1857 from Meerut cantonment when Indian sepoys mutinied, soon spreading across northern and central India.',
                subjectTopic: '1857 Revolt',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which Mughal emperor built the Taj Mahal at Agra?',
                options: ['Akbar', 'Jahangir', 'Shah Jahan', 'Aurangzeb'],
                correctAnswerIndex: 2,
                explanation: 'Shah Jahan commissioned the Taj Mahal in 1632 in memory of his wife Mumtaz Mahal. It was completed in 1653 and is a UNESCO World Heritage Site in Agra, UP.',
                subjectTopic: 'Mughal Era',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Who was the first Chief Minister of Uttar Pradesh?',
                options: ['Govind Ballabh Pant', 'Charan Singh', 'Hemwati Nandan Bahuguna', 'Sucheta Kripalani'],
                correctAnswerIndex: 0,
                explanation: 'Govind Ballabh Pant was the first Chief Minister of Uttar Pradesh (1950-1954), succeeding his role as Premier of United Provinces from 1937.',
                subjectTopic: 'Post-Independence UP',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which city in UP is known as the "City of Nawabs"?',
                options: ['Agra', 'Varanasi', 'Lucknow', 'Allahabad'],
                correctAnswerIndex: 2,
                explanation: 'Lucknow is known as the "City of Nawabs" due to its association with the Nawabs of Awadh (1722-1856), who developed its unique Ganga-Jamuni tehzeeb culture.',
                subjectTopic: 'Awadh Region',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'The Kumbh Mela, the largest religious gathering, is held in which UP city every 12 years?',
                options: ['Haridwar', 'Prayagraj (Allahabad)', 'Ujjain', 'Nashik'],
                correctAnswerIndex: 1,
                explanation: 'Prayagraj (formerly Allahabad) hosts the Kumbh Mela every 12 years at the Triveni Sangam (confluence of Ganga, Yamuna, and mythical Saraswati). It is a UNESCO Intangible Cultural Heritage.',
                subjectTopic: 'UP Culture',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
      {
        name: 'UP Geography & Economy',
        slug: 'uppsc-up-geography',
        icon: '🌾',
        description: 'Physical features, rivers (Ganga, Yamuna), climate, agriculture, industries, and UP\'s economic profile.',
        order: 2,
        tests: [
          {
            title: 'UPPSC UP Geography Mock',
            slug: 'uppsc-up-geography-mock',
            type: 'mock',
            duration: 25,
            totalMarks: 50,
            passingMarks: 20,
            isPublished: true,
            difficulty: 'medium',
            negativeMarking: false,
            negativeMarks: 0,
            instructions: '25 minutes, 25 questions. Each question 2 marks. No negative marking.',
            year: 2025,
            examSession: 'Prelims',
            isPremium: true,
            price: 49,
            questions: [
              {
                question: 'Which river flows through Prayagraj and is considered the holiest in India?',
                options: ['Yamuna', 'Ganga', 'Saraswati', 'Saryu'],
                correctAnswerIndex: 1,
                explanation: 'The Ganga flows through Prayagraj, where it meets the Yamuna at the Triveni Sangam. The Ganga is the longest river in India, flowing 2,525 km.',
                subjectTopic: 'UP Rivers',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which district of Uttar Pradesh is the birthplace of Lord Krishna?',
                options: ['Ayodhya', 'Mathura', 'Varanasi', 'Vrindavan'],
                correctAnswerIndex: 1,
                explanation: 'Mathura is the birthplace of Lord Krishna, according to Hindu tradition. It is located on the banks of the Yamuna and is part of the Braj region.',
                subjectTopic: 'UP Religious Geography',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Uttar Pradesh is the largest producer of which crop in India?',
                options: ['Rice', 'Sugarcane', 'Wheat', 'Cotton'],
                correctAnswerIndex: 1,
                explanation: 'Uttar Pradesh is the largest producer of sugarcane in India, accounting for around 40-45% of national production. Major sugar-producing districts include Meerut, Bareilly, and Gorakhpur.',
                subjectTopic: 'UP Agriculture',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'Which city in UP is famous for the leather industry and is called the "Leather City"?',
                options: ['Kanpur', 'Agra', 'Moradabad', 'Firozabad'],
                correctAnswerIndex: 0,
                explanation: 'Kanpur is called the "Leather City of the World" — it is one of India\'s largest producers of leather goods, footwear, and accessories, with exports worldwide.',
                subjectTopic: 'UP Industry',
                marks: 2,
                isPremium: false,
              },
              {
                question: 'How many districts are there in Uttar Pradesh (as of 2024)?',
                options: ['70', '72', '75', '77'],
                correctAnswerIndex: 2,
                explanation: 'Uttar Pradesh has 75 districts, grouped into 18 divisions. It is the most populous state in India with over 240 million people.',
                subjectTopic: 'UP Administrative Setup',
                marks: 2,
                isPremium: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

// =============================================================================
// BANNERS (5)
// =============================================================================

const nextYear = new Date().getFullYear() + 1;

export const SEED_BANNERS: SeedBanner[] = [
  {
    title: 'SSC CGL 2025 — Complete Mock Test Series',
    subtitle: '300+ mock tests • Previous papers • Detailed solutions',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
    link: 'category:ssc',
    linkLabel: 'Start Practicing',
    order: 1,
    isActive: true,
    startsAt: `${nextYear}-01-01T00:00:00.000Z`,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'Banking Exams — IBPS PO & SBI PO Pack',
    subtitle: '200+ sectional + full-length tests • Banking awareness included',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=1200&q=80',
    link: 'category:banking',
    linkLabel: 'Unlock Now',
    order: 2,
    isActive: true,
    startsAt: `${nextYear}-01-01T00:00:00.000Z`,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'UPSC Civil Services — Premium Test Series',
    subtitle: 'Polity, History, Geography, Economy, Current Affairs — all covered',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',
    link: 'category:upsc',
    linkLabel: 'Explore Plans',
    order: 3,
    isActive: true,
    startsAt: `${nextYear}-01-01T00:00:00.000Z`,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'LIC AAO/ADO Recruitment 2025',
    subtitle: 'Insurance awareness + Quant + Reasoning — full mock series',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80',
    link: 'category:lic',
    linkLabel: 'View Tests',
    order: 4,
    isActive: true,
    startsAt: `${nextYear}-01-01T00:00:00.000Z`,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'State PSC — Assam, West Bengal, UP',
    subtitle: 'Region-specific mock tests in your regional language',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80',
    link: '',
    linkLabel: 'Browse States',
    order: 5,
    isActive: true,
    startsAt: `${nextYear}-01-01T00:00:00.000Z`,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
];

// =============================================================================
// ANNOUNCEMENTS (8)
// =============================================================================

export const SEED_ANNOUNCEMENTS: SeedAnnouncement[] = [
  {
    title: 'SSC CGL 2025 Notification Released',
    message: 'Staff Selection Commission has released the official notification for Combined Graduate Level Examination 2025. Online application opens on the SSC portal. 17,727 vacancies announced across various Group B and C posts.',
    type: 'success',
    imageUrl: '',
    link: 'https://ssc.gov.in',
    linkLabel: 'View Notification',
    isPinned: true,
    isPublished: true,
    order: 1,
    expiresAt: `${nextYear}-06-30T23:59:59.000Z`,
  },
  {
    title: 'IBPS PO 2025 — Application Window Open',
    message: 'Institute of Banking Personnel Selection (IBPS) has opened the online application for Probationary Officer (PO) recruitment 2025. Last date to apply is 28th August. Preliminary exam in October 2025.',
    type: 'info',
    imageUrl: '',
    link: 'https://ibps.in',
    linkLabel: 'Apply Now',
    isPinned: true,
    isPublished: true,
    order: 2,
    expiresAt: `${nextYear}-09-30T23:59:59.000Z`,
  },
  {
    title: 'RRB NTPC Result 2025 Declared',
    message: 'Railway Recruitment Board has declared the NTPC Graduate Level result 2025 (CEN 05/2024). Candidates can check their results on the official RRB regional websites using their registration number and date of birth.',
    type: 'success',
    imageUrl: '',
    link: 'https://rrbcdg.gov.in',
    linkLabel: 'Check Result',
    isPinned: false,
    isPublished: true,
    order: 3,
    expiresAt: `${nextYear}-12-31T23:59:59.000Z`,
  },
  {
    title: 'UPSC Civil Services Prelims 2025 — Admit Card Released',
    message: 'Union Public Service Commission has released the e-admit card for Civil Services Preliminary Examination 2025. Download from upsconline.nic.in using your registration ID. Exam date: 26th May 2025.',
    type: 'info',
    imageUrl: '',
    link: 'https://upsconline.nic.in',
    linkLabel: 'Download Admit Card',
    isPinned: false,
    isPublished: true,
    order: 4,
    expiresAt: `${nextYear}-05-31T23:59:59.000Z`,
  },
  {
    title: 'LIC AAO 2025 Recruitment — 500 Vacancies',
    message: 'Life Insurance Corporation of India has announced 500 vacancies for Assistant Administrative Officer (AAO) 2025. Online registration begins 15th September. Graduates in any discipline eligible.',
    type: 'promo',
    imageUrl: '',
    link: 'https://licindia.in',
    linkLabel: 'Apply Online',
    isPinned: false,
    isPublished: true,
    order: 5,
    expiresAt: `${nextYear}-10-15T23:59:59.000Z`,
  },
  {
    title: 'APSC CCE 2025 — Prelims on 15th June',
    message: 'Assam Public Service Commission has scheduled the Combined Competitive Examination (CCE) Prelims 2025 for 15th June. Syllabus updated. Download revised notification from apsc.nic.in.',
    type: 'info',
    imageUrl: '',
    link: 'https://apsc.nic.in',
    linkLabel: 'View Schedule',
    isPinned: false,
    isPublished: true,
    order: 6,
    expiresAt: `${nextYear}-06-30T23:59:59.000Z`,
  },
  {
    title: 'WBCS 2025 Notification — Apply Before 30th September',
    message: 'West Bengal Public Service Commission has released the WBCS (Executive) 2025 notification. Online application closes on 30th September. Preliminary exam in January 2026.',
    type: 'warning',
    imageUrl: '',
    link: 'https://wbpsc.gov.in',
    linkLabel: 'Apply Now',
    isPinned: false,
    isPublished: true,
    order: 7,
    expiresAt: `${nextYear}-09-30T23:59:59.000Z`,
  },
  {
    title: 'Maintenance Notice — App Update Tonight',
    message: 'ExamVault will undergo scheduled maintenance tonight between 1:00 AM to 3:00 AM IST. Some features may be temporarily unavailable. Sorry for the inconvenience.',
    type: 'warning',
    imageUrl: '',
    link: '',
    linkLabel: '',
    isPinned: false,
    isPublished: true,
    order: 8,
    expiresAt: `${nextYear}-12-31T23:59:59.000Z`,
  },
];

// =============================================================================
// UPCOMING EXAMS (10)
// =============================================================================

export const SEED_UPCOMING_EXAMS: SeedUpcomingExam[] = [
  {
    name: 'RRB NTPC 2025 (CEN 05/2024)',
    organization: 'Railway Recruitment Board',
    categoryIdSlug: 'indian-railways', // assumes existing Indian Railways category
    examDate: `${nextYear}-07-15T09:00:00.000Z`,
    applicationStartDate: `${nextYear - 1}-02-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear - 1}-03-01T23:59:59.000Z`,
    notificationUrl: 'https://rrbcdg.gov.in',
    syllabusUrl: 'https://rrbcdg.gov.in/notifications.aspx',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    description: 'Non-Technical Popular Categories (NTPC) recruitment for Graduate and Undergraduate posts — Station Master, Goods Guard, Senior Clerk, Junior Clerk, etc. CBT 1, CBT 2, Typing Skill Test, Document Verification.',
    tags: ['Railway', 'NTPC', 'Graduate', 'CBT'],
    isPublished: true,
    order: 1,
  },
  {
    name: 'SSC CGL 2025 (Tier 1)',
    organization: 'Staff Selection Commission',
    categoryIdSlug: 'ssc',
    examDate: `${nextYear}-09-01T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-06-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-07-01T23:59:59.000Z`,
    notificationUrl: 'https://ssc.gov.in',
    syllabusUrl: 'https://ssc.gov.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    description: 'Combined Graduate Level Examination for recruitment to Group B and C posts in Central Government ministries and departments. Tier 1 (CBT), Tier 2 (CBT + DEST), Document Verification.',
    tags: ['SSC', 'CGL', 'Graduate', 'Group B'],
    isPublished: true,
    order: 2,
  },
  {
    name: 'IBPS PO 2025 (Prelims)',
    organization: 'Institute of Banking Personnel Selection',
    categoryIdSlug: 'banking',
    examDate: `${nextYear}-10-12T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-08-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-08-28T23:59:59.000Z`,
    notificationUrl: 'https://ibps.in',
    syllabusUrl: 'https://ibps.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    description: 'Probationary Officer (PO) recruitment for participating public sector banks. Selection process: Prelims (English, Quant, Reasoning), Mains (Objective + Descriptive), Interview.',
    tags: ['Banking', 'PO', 'IBPS', 'Public Sector'],
    isPublished: true,
    order: 3,
  },
  {
    name: 'SBI PO 2025 (Prelims)',
    organization: 'State Bank of India',
    categoryIdSlug: 'banking',
    examDate: `${nextYear}-11-02T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-09-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-10-05T23:59:59.000Z`,
    notificationUrl: 'https://sbi.co.in/careers',
    syllabusUrl: 'https://sbi.co.in/careers/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    description: 'State Bank of India Probationary Officer recruitment. Three-phase selection: Preliminary Exam, Main Exam (Objective + Descriptive), Phase III (Group Discussion + Interview).',
    tags: ['Banking', 'PO', 'SBI'],
    isPublished: true,
    order: 4,
  },
  {
    name: 'UPSC Civil Services 2025 (Prelims)',
    organization: 'Union Public Service Commission',
    categoryIdSlug: 'upsc',
    examDate: `${nextYear}-05-26T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-02-14T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-03-06T23:59:59.000Z`,
    notificationUrl: 'https://upsc.gov.in',
    syllabusUrl: 'https://upsc.gov.in/examinations/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    description: 'Civil Services Examination (CSE) for IAS, IPS, IFS, IRS, and other Group A services. Three stages: Preliminary (GS Paper 1 + CSAT), Main (9 descriptive papers), Personality Test (Interview).',
    tags: ['UPSC', 'IAS', 'Civil Services', 'Group A'],
    isPublished: true,
    order: 5,
  },
  {
    name: 'LIC AAO 2025',
    organization: 'Life Insurance Corporation of India',
    categoryIdSlug: 'lic',
    examDate: `${nextYear}-10-25T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-09-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-10-09T23:59:59.000Z`,
    notificationUrl: 'https://licindia.in',
    syllabusUrl: 'https://licindia.in/careers',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    description: 'Assistant Administrative Officer (AAO) recruitment — Generalist/IT/Chartered Accountant/Actuarial/Statistical streams. Selection: Prelims, Mains, Interview. 500+ vacancies.',
    tags: ['LIC', 'AAO', 'Insurance'],
    isPublished: true,
    order: 6,
  },
  {
    name: 'APSC CCE 2025 (Prelims)',
    organization: 'Assam Public Service Commission',
    categoryIdSlug: 'assam-apsc',
    examDate: `${nextYear}-06-15T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-03-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-04-15T23:59:59.000Z`,
    notificationUrl: 'https://apsc.nic.in',
    syllabusUrl: 'https://apsc.nic.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    description: 'Combined Competitive Examination (CCE) for Assam Civil Service (ACS), Assam Police Service (APS), and other state civil services. Prelims (2 GS papers), Mains (Essay + 6 optional + GS), Interview.',
    tags: ['APSC', 'CCE', 'Assam', 'ACS'],
    isPublished: true,
    order: 7,
  },
  {
    name: 'WBCS 2025 (Prelims)',
    organization: 'West Bengal Public Service Commission',
    categoryIdSlug: 'wbcs',
    examDate: `${nextYear}-01-12T09:00:00.000Z`,
    applicationStartDate: `${nextYear - 1}-09-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear - 1}-09-30T23:59:59.000Z`,
    notificationUrl: 'https://wbpsc.gov.in',
    syllabusUrl: 'https://wbpsc.gov.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1577563908413-9a595f754d00?w=800&q=80',
    description: 'West Bengal Civil Service (Executive) Examination for recruitment to Group A, B, C, D posts. Prelims (Objective, 8 papers), Mains (6 descriptive + language), Personality Test.',
    tags: ['WBCS', 'West Bengal', 'Executive'],
    isPublished: true,
    order: 8,
  },
  {
    name: 'UPPSC PCS 2025 (Prelims)',
    organization: 'Uttar Pradesh Public Service Commission',
    categoryIdSlug: 'uppsc',
    examDate: `${nextYear}-07-20T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-04-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-05-21T23:59:59.000Z`,
    notificationUrl: 'https://uppsc.up.nic.in',
    syllabusUrl: 'https://uppsc.up.nic.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    description: 'Provincial Civil Service (PCS) Upper Subordinate Examination for recruitment to Deputy Collector, DSP, BDO, and other Group A & B posts in Uttar Pradesh. Prelims, Mains, Interview.',
    tags: ['UPPSC', 'PCS', 'Uttar Pradesh', 'Group A'],
    isPublished: true,
    order: 9,
  },
  {
    name: 'SSC CHSL 2025 (Tier 1)',
    organization: 'Staff Selection Commission',
    categoryIdSlug: 'ssc',
    examDate: `${nextYear}-08-01T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-05-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-06-15T23:59:59.000Z`,
    notificationUrl: 'https://ssc.gov.in',
    syllabusUrl: 'https://ssc.gov.in/syllabus',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    description: 'Combined Higher Secondary Level (10+2) Examination for recruitment to Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), Postal Assistant/Sorting Assistant, and Data Entry Operator posts.',
    tags: ['SSC', 'CHSL', '10+2', 'Clerk'],
    isPublished: true,
    order: 10,
  },
];
