// =============================================================================
// ExamVault — Assam Secretariat (Junior Assistant) bilingual question pool
// Target: HSLC+ clerical level — English / GK / Reasoning / Computer Knowledge
//
// Format: each question, option, and explanation is BILINGUAL
//   question  -> "English\nঅসমীয়া"
//   option    -> "English / অসমীয়া"
//   expl      -> "English\nঅসমীয়া"
//
// 4 subjects × 20 questions = 80 bilingual items.
// correctAnswerIndex is distributed evenly across 0,1,2,3 (5 each per subject).
// =============================================================================
import type { QuestionPoolMap } from './structure';

export const SECRETARIAT_POOLS: QuestionPoolMap = {
  // ===========================================================================
  // sec-english — General English (20)
  // Topics: Grammar (tense, voice, narration, articles, prepositions,
  //         conjunctions, subject-verb agreement), Vocabulary (synonyms,
  //         antonyms, one-word substitution, spelling, idioms), Drafting
  //         (formal letters, précis).
  // ===========================================================================
  'sec-english': [
    {
      question: "Choose the correct verb form: He ____ to the office every day.\nসঠিক ক্ৰিয়াৰূপ বাছক: তেওঁ প্ৰতিদিনে কাৰ্যালয়লৈ ____।",
      options: [
        'goes / যায়',
        'go / যাওক',
        'going / গৈ',
        'went / গৈছিল',
      ],
      correctAnswerIndex: 0,
      explanation: "The subject 'He' is third-person singular, so the verb takes the '-s' ending — 'goes' is correct.\n'He' তৃতীয় পুৰুষ একবচন, সেয়ে ক্ৰিয়াৰ সৈতে '-s' লাগে — 'goes' শুদ্ধ।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Choose the correct passive voice of: \"She writes a letter.\"\n\"তাই এখন চিঠি লিখে\" ৰ সঠিক কৰ্মবাচ্য ৰূপ বাছক।",
      options: [
        'She is writing a letter / তাই এখন চিঠি লিখি আছে',
        'A letter is written by her / তাইৰ দ্বাৰা এখন চিঠি লিখা যায়',
        'A letter was written by her / তাইৰ দ্বাৰা এখন চিঠি লিখা হৈছিল',
        'She has written a letter / তাই এখন চিঠি লিখিছে',
      ],
      correctAnswerIndex: 1,
      explanation: "Active 'writes' (simple present) becomes passive 'is written' (simple present): is/am/are + past participle.\nকৰ্তৃবাচ্য 'writes' (সাধাৰণ বৰ্তমান) কৰ্মবাচ্যত 'is written' (সাধাৰণ বৰ্তমান) হয়: is/am/are + past participle।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Choose the correct indirect speech of: He said, \"I am busy.\"\nতেওঁ ক'লে, \"মই ব্যস্ত\" — ইয়াৰ সঠিক পৰোক্ষ ভাষণ বাছক।",
      options: [
        'He said that he is busy / তেওঁ ক’লে যে তেওঁ ব্যস্ত',
        'He told that he is busy / তেওঁ ক’লে যে তেওঁ ব্যস্ত',
        'He said that he was busy / তেওঁ ক’লে যে তেওঁ ব্যস্ত আছিল',
        'He says that he was busy / তেওঁ কয় যে তেওঁ ব্যস্ত আছিল',
      ],
      correctAnswerIndex: 2,
      explanation: "In indirect speech the present tense backshifts to past ('am' → 'was'), and 'said' is followed by 'that'; first person becomes third.\nপৰোক্ত ভাষণত বৰ্তমান কাল অতীতলৈ পৰিৱৰ্তন হয় ('am' → 'was'); 'said' ৰ পিছত 'that' ব্যৱহৃত হয়; প্ৰথম পুৰুষ তৃতীয় পুৰুষলৈ যায়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Fill in the blank with the correct article: She is ____ honest officer.\nসঠিক article ৰে খালী ঠাই পূৰ কৰা: তেওঁ ____ সৎ বিষয়া।",
      options: [
        'a / এটা',
        'an / এজন',
        'the / সেইজন',
        'no article / কোনো article নালাগে',
      ],
      correctAnswerIndex: 1,
      explanation: "'Honest' begins with a vowel sound (silent 'h'), so 'an' is used before it.\n'Honest' শব্দৰ আৰম্ভণিত স্বৰবৰ্ণৰ ধ্বনি ('h' নীৰৱ), সেয়ে ইয়াৰ আগত 'an' ব্যৱহৃত হয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Fill in the blank with the correct preposition: He is fond ____ music.\nসঠিক preposition ৰে খালী ঠাই পূৰ কৰা: তেওঁ সংগীত ____ অনুৰাগী।",
      options: [
        'in / -ত',
        'for / বাবে',
        'to / লৈ',
        'of / -ৰ প্ৰতি',
      ],
      correctAnswerIndex: 3,
      explanation: "The fixed phrase is 'fond of' — meaning 'having a liking for'.\nনিৰ্দিষ্ট বাক্যাংশ হ’ল 'fond of' — অৰ্থাৎ 'ভাল পোৱা'।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Fill in the blank with the correct conjunction: Work hard ____ you will fail.\nসঠিক conjunction ৰে খালী ঠাই পূৰ কৰা: কঠোৰ পৰিশ্ৰম কৰা ____ তুমি অসফল হ’বা।",
      options: [
        'and / আৰু',
        'but / কিন্তু',
        'or / নহ’লে',
        'so / গতিকে',
      ],
      correctAnswerIndex: 2,
      explanation: "'Or' joins two alternatives in a negative/imperative sense — work hard, otherwise you will fail.\n'Or' দুটা বিকল্প সংযোগ কৰে (নহ’লে) — কঠোৰ পৰিশ্ৰম কৰা, নহ’লে তুমি অসফল হ’বা।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Choose the correct verb: The news ____ good today.\nসঠিক ক্ৰিয়া বাছক: আজি সংবাদ ____ ভাল।",
      options: [
        'is / আছে',
        'are / আছে (বহুবচন)',
        'were / আছিল (বহুবচন)',
        'have / আছে',
      ],
      correctAnswerIndex: 0,
      explanation: "'News' is an uncountable noun and always takes a singular verb.\n'News' এটা অগণনীয় বিশেষ্য আৰু সদায় একবচন ক্ৰিয়া লয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Choose the synonym of \"Abundant\".\n\"Abundant\" ৰ সমাৰ্থক শব্দ বাছক।",
      options: [
        'Scarce / দুৰ্লভ',
        'Empty / খালী',
        'Poor / দুখীয়া',
        'Plentiful / প্ৰচুৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "'Abundant' means existing in large quantities; 'plentiful' is its synonym.\n'Abundant' মানে প্ৰচুৰ পৰিমাণে থকা; 'plentiful' ইয়াৰ সমাৰ্থক।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Choose the antonym of \"Ancient\".\n\"Ancient\" ৰ বিপৰীতাৰ্থক শব্দ বাছক।",
      options: [
        'Old / পুৰণি',
        'Modern / আধুনিক',
        'Past / অতীত',
        'Antique / পুৰণি',
      ],
      correctAnswerIndex: 1,
      explanation: "'Ancient' means very old; its antonym is 'modern' — relating to the present time.\n'Ancient' মানে অতি পুৰণি; ইয়াৰ বিপৰীত শব্দ 'modern' — বৰ্তমান কালৰ।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Choose the one-word substitution for: \"A person who writes books.\"\nএটা শব্দৰ সংযোজন বাছক: \"যিজনে কিতাপ লিখে।\"",
      options: [
        'Editor / সম্পাদক',
        'Publisher / প্ৰকাশক',
        'Author / লেখক',
        'Printer / মূদ্ৰক',
      ],
      correctAnswerIndex: 2,
      explanation: "An 'author' is a person who writes books or other literary works.\n'Author' হ’ল এজন ব্যক্তি যিয়ে কিতাপ বা সাহিত্য ৰচনা কৰে।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Choose the one-word substitution for: \"One who eats everything.\"\nএটা শব্দৰ সংযোজন বাছক: \"যিয়ে সকলো খায়।\"",
      options: [
        'Omnivore / সৰ্বভোজী',
        'Carnivore / মাংসাহাৰী',
        'Herbivore / তৃণভোজী',
        'Insectivore / পতংগভোজী',
      ],
      correctAnswerIndex: 0,
      explanation: "'Omni' = all, 'vore' = eater; an omnivore eats both plant and animal matter.\n'Omni' = সকলো, 'vore' = ভোজী; omnivore উদ্ভিদ আৰু প্ৰাণী উভয় গ্ৰহণ কৰে।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Which of the following sentences is grammatically correct?\nতলৰ কোনটো বাক্য ব্যাকৰণগতভাৱে শুদ্ধ?",
      options: [
        'Neither of the boys are present / ল’ৰা দুজনৰ কোনোজনো উপস্থিত নাই (অশুদ্ধ)',
        'Neither of the boy are present / ল’ৰা দুজনৰ কোনোজনো উপস্থিত নাই (অশুদ্ধ)',
        'Neither of the boys were present / ল’ৰা দুজনৰ কোনোজনো উপস্থিত নাছিল (অশুদ্ধ)',
        'Neither of the boys is present / ল’ৰা দুজনৰ কোনোজনো উপস্থিত নাই (শুদ্ধ)',
      ],
      correctAnswerIndex: 3,
      explanation: "'Neither' is treated as singular and takes a singular verb — 'is'.\n'Neither' একবচন হিচাপে গণ্য হয় আৰু একবচন ক্ৰিয়া 'is' লয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "What does the idiom \"Bite the bullet\" mean?\n\"Bite the bullet\" বাক্যাংশটোৰ অৰ্থ কি?",
      options: [
        'To eat quickly / সোনকালে খোৱা',
        'To endure pain bravely / সাহসেৰে কষ্ট সহ্য কৰা',
        'To fight / যুঁজ কৰা',
        'To escape / পলাই যোৱা',
      ],
      correctAnswerIndex: 1,
      explanation: "'Bite the bullet' means to face a difficult or unpleasant situation bravely without complaining.\n'Bite the bullet' মানে এটা কঠিন বা অপ্ৰিয় পৰিস্থিতি বিনা অভিযোগে সাহসেৰে সন্মুখীন কৰা।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Choose the correct tense form: By next year, she ____ her degree.\nসঠিক tense ৰূপ বাছক: আগামী বছৰলৈ তেওঁ নিজৰ ডিগ্ৰী ____।",
      options: [
        'completes / সম্পূৰ্ণ কৰে',
        'completed / সম্পূৰ্ণ কৰিছিল',
        'will have completed / সম্পূৰ্ণ কৰি উঠিব',
        'will complete / সম্পূৰ্ণ কৰিব',
      ],
      correctAnswerIndex: 2,
      explanation: "The Future Perfect tense ('will have + past participle') is used for an action that will be completed by a certain future time.\nFuture Perfect ('will have + past participle') এটা নিৰ্দিষ্ট ভৱিষ্যত সময়ৰ ভিতৰত সম্পূৰ্ণ হ’ব লাগিব বুজাবলৈ ব্যৱহৃত হয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "In a formal letter, \"Yours sincerely\" is used when:\nএটা আনুষ্ঠানিক চিঠিত, \"Yours sincerely\" কেতিয়া ব্যৱহাৰ কৰা হয়?",
      options: [
        'The recipient is known by name / প্ৰাপকৰ নাম জনা আছে',
        'The recipient is unknown / প্ৰাপক অজ্ঞাত',
        'It is an official letter to a department / ই এটা বিভাগলৈ চৰকাৰী চিঠি',
        'It is a business circular / ই এটা ব্যৱসায়িক পৰিপত্ৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "'Yours sincerely' is used when the recipient's name is known (e.g., Dear Mr Das); 'Yours faithfully' is used with 'Dear Sir/Madam'.\n'Yours sincerely' তেতিয়া ব্যৱহৃত হয় যেতিয়া প্ৰাপকৰ নাম জনা থাকে (যেনে Dear Mr Das); 'Dear Sir/Madam' ৰ সৈতে 'Yours faithfully' ব্যৱহাৰ কৰা হয়।",
      subjectTopic: 'Drafting',
      marks: 1,
    },
    {
      question: "A précis should ideally be approximately how much of the original passage?\nএটা précis আদৰ্শভাৱে মূল অনুচ্ছেদৰ প্ৰায় কিমান হ’ব লাগে?",
      options: [
        'Equal in length / সমান দৈৰ্ঘ্যৰ',
        'Half in length / আধা দৈৰ্ঘ্যৰ',
        'Double the length / দুগুণ দৈৰ্ঘ্যৰ',
        'About one-third in length / প্ৰায় এক-তৃতীয়াংশ দৈৰ্ঘ্যৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "A précis is generally about one-third the length of the original passage, retaining only the main ideas.\nপ্ৰচিছ সাধাৰণতে মূল অনুচ্ছেদৰ প্ৰায় এক-তৃতীয়াংশ দৈৰ্ঘ্যৰ হয়, কেৱল মুখ্য ভাবসমূহ বজাই ৰাখি।",
      subjectTopic: 'Drafting',
      marks: 1,
    },
    {
      question: "Choose the correct passive voice of: \"They built the bridge in 1990.\"\n\"১৯৯০ চনত তেওঁলোকে সেতুখন নিৰ্মাণ কৰিছিল\" ৰ সঠিক কৰ্মবাচ্য ৰূপ বাছক।",
      options: [
        'The bridge is built by them / দলটোৱে সেতুখন নিৰ্মাণ কৰে',
        'The bridge was built by them in 1990 / ১৯৯০ চনত দলটোৱে সেতুখন নিৰ্মাণ কৰিছিল',
        'The bridge has been built by them / দলটোৱে সেতুখন নিৰ্মাণ কৰিছে',
        'The bridge had been built by them / দলটোৱে সেতুখন নিৰ্মাণ কৰি থৈছিল',
      ],
      correctAnswerIndex: 1,
      explanation: "Active 'built' (simple past) becomes passive 'was/were built' (simple past).\nকৰ্তৃবাচ্য 'built' (সাধাৰণ অতীত) কৰ্মবাচ্যত 'was/were built' (সাধাৰণ অতীত) হয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Fill in the blank with the correct preposition: He has been working here ____ 2010.\nসঠিক preposition ৰে খালী ঠাই পূৰ কৰা: তেওঁ ২০১০ চনৰ পৰা ইয়াত কাম কৰি আছে ____ 2010.",
      options: [
        'for / বাবে (সময়খণ্ড)',
        'from / -ৰ পৰা',
        'since / পৰা (নিৰ্দিষ্ট সময়)',
        'at / ত',
      ],
      correctAnswerIndex: 2,
      explanation: "'Since' is used with a point of time (2010); 'for' is used with a period (5 years).\n'Since' এটা নিৰ্দিষ্ট সময়বিন্দুৰ সৈতে (২০১০); 'for' এটা সময়খণ্ডৰ সৈতে (৫ বছৰ) ব্যৱহৃত হয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
    {
      question: "Choose the correctly spelt word.\nশুদ্ধ বানানৰ শব্দটো বাছক।",
      options: [
        'Accommodation / বাসস্থান',
        'Accomodation / বাসস্থান (ভুল)',
        'Acommodation / বাসস্থান (ভুল)',
        'Accomoddation / বাসস্থান (ভুল)',
      ],
      correctAnswerIndex: 0,
      explanation: "'Accommodation' has two 'c's and two 'm's — A-C-C-O-M-M-O-D-A-T-I-O-N.\n'Accommodation' ত দুটা 'c' আৰু দুটা 'm' আছে — A-C-C-O-M-M-O-D-A-T-I-O-N।",
      subjectTopic: 'Vocabulary',
      marks: 1,
    },
    {
      question: "Choose the correct indirect speech of: She said to me, \"Where do you live?\"\nতেওঁ মোক সুধিলে, \"তুমি ক'ত থাকা?\" — ইয়াৰ সঠিক পৰোক্ত ভাষণ বাছক।",
      options: [
        'She asked me where do you live / তেওঁ মোক সুধিলে তুমি ক’ত থাকা',
        'She asked me where I live / তেওঁ মোক সুধিলে মই ক’ত থাকোঁ',
        'She said me where I lived / তেওঁ মোক ক’লে মই ক’ত থাকো',
        'She asked me where I lived / তেওঁ মোক সুধিলে মই ক’ত থাকো',
      ],
      correctAnswerIndex: 3,
      explanation: "In indirect speech, the wh-question becomes assertive (no do/does), the tense backshifts (live → lived), and 'said to' becomes 'asked'.\nপৰোক্ত ভাষণত wh-প্ৰশ্ন বিবৃতিমূলক হয় (do/does নাথাকে), কাল পিছুৱায় (live → lived), আৰু 'said to' → 'asked' হয়।",
      subjectTopic: 'Grammar',
      marks: 1,
    },
  ],

  // ===========================================================================
  // sec-gk — General Knowledge (20)
  // Mix of Assam GK (capital, rivers, festivals, personalities, parks) and
  // India GK (constitution, parliament, geography, presidents).
  // ===========================================================================
  'sec-gk': [
    {
      question: "What is the capital of Assam?\nঅসমৰ ৰাজধানী কি?",
      options: [
        'Dispur / দিছপুৰ',
        'Guwahati / গুৱাহাটী',
        'Dibrugarh / ডিব্ৰুগড়',
        'Jorhat / যোৰহাট',
      ],
      correctAnswerIndex: 0,
      explanation: "Dispur, a locality in Guwahati, is the capital of Assam.\nগুৱাহাটীৰ এটা অঞ্চল দিছপুৰ অসমৰ ৰাজধানী।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which is the oldest oil refinery in Assam?\nঅসমৰ আটাইতকৈ পুৰণি তেল পৰিশোধনাগাৰ কোনটো?",
      options: [
        'Guwahati Refinery / গুৱাহাটী পৰিশোধনাগাৰ',
        'Digboi Refinery / ডিগবৈ পৰিশোধনাগাৰ',
        'Bongaigaon Refinery / বঙাইগাঁও পৰিশোধনাগাৰ',
        'Numaligarh Refinery / নুমালিগড় পৰিশোধনাগাৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "Digboi Refinery, commissioned in 1901, is the oldest oil refinery in Assam and one of the oldest in the world.\n১৯০১ চনত স্থাপিত ডিগবৈ পৰিশোধনাগাৰ অসমৰ আৰু বিশ্বৰ অন্যতম পুৰণি।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which is the longest river in Assam?\nঅসমৰ দীৰ্ঘতম নদী কোনখন?",
      options: [
        'Barak / বৰাক',
        'Subansiri / সোৱনশিৰি',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
        'Manas / মানস',
      ],
      correctAnswerIndex: 2,
      explanation: "The Brahmaputra flows about 918 km through Assam and is the longest river in the state.\nব্ৰহ্মপুত্ৰ নদী অসমৰ মাজেদি প্ৰায় ৯১৮ কিলোমিটাৰ বৈ গৈছে আৰু ৰাজ্যখনৰ দীৰ্ঘতম নদী।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "How many times is the Bihu festival celebrated in a year?\nবিহু উৎসৱ বছৰত কিমানবাৰ উদযাপন কৰা হয়?",
      options: [
        'Once / এবাৰ',
        'Twice / দুবাৰ',
        'Four times / চাৰিবাৰ',
        'Thrice / তিনিবাৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "Bihu is celebrated three times a year — Rongali (Bohag), Kongali (Kati) and Bhogali (Magh) Bihu.\nবিহু বছৰত তিনিবাৰ উদযাপন কৰা হয় — ৰঙালী (বহাগ), কোংগালী (কাতি) আৰু ভোগালী (মাঘ) বিহু।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Who composed the Assamese state song \"O Mur Apunar Dex\"?\nঅসমীয়া ৰাজ্যিক গীত \"O Mur Apunar Dex\" কোনে ৰচনা কৰিছিল?",
      options: [
        'Jyotiprasad Agarwala / জ্যোতিপ্ৰসাদ আগৰৱালা',
        'Lakshminath Bezbaruah / লক্ষ্মীনাথ বেজবৰুৱা',
        'Bishnuprasad Raba / বিষ্ণুপ্ৰসাদ ৰাভা',
        'Bhupen Hazarika / ভূপেন হাজৰিকা',
      ],
      correctAnswerIndex: 1,
      explanation: "'O Mur Apunar Dex' was composed by Lakshminath Bezbaruah in 1909; it was adopted as the state song of Assam in 1927.\n'O Mur Apunar Dex' ১৯০৯ চনত লক্ষ্মীনাথ বেজবৰুৱাই ৰচনা কৰিছিল; ১৯২৭ চনত ই অসমৰ ৰাজ্যিক গীত হিচাপে গৃহীত হয়।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which national park in Assam is famous for the one-horned rhinoceros?\nঅসমৰ কোন ৰাষ্ট্ৰীয় উদ্যান এশিঙীয়া গঁড়ৰ বাবে বিখ্যাত?",
      options: [
        'Kaziranga / কাজিৰঙা',
        'Manas / মানস',
        'Dibru-Saikhowa / দিব্ৰু-চাইকুৱা',
        'Nameri / নামেৰি',
      ],
      correctAnswerIndex: 0,
      explanation: "Kaziranga National Park, a UNESCO World Heritage Site, hosts about two-thirds of the world's one-horned rhinoceroses.\nইউনেস্কো বিশ্ব ঐতিহ্য কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যানত বিশ্বৰ প্ৰায় দুই-তৃতীয়াংশ এশিঙীয়া গঁড় আছে।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Who was the first Chief Minister of Assam?\nঅসমৰ প্ৰথম মুখ্যমন্ত্ৰী কোন আছিল?",
      options: [
        'Bishnuram Medhi / বিষ্ণুৰাম মেধি',
        'Sarat Chandra Sinha / শৰৎ চন্দ্ৰ সিনহা',
        'Gopinath Bordoloi / গোপীনাথ বৰদলৈ',
        'Hiteswar Saikia / হিতেশ্বৰ শইকীয়া',
      ],
      correctAnswerIndex: 2,
      explanation: "Gopinath Bordoloi was the first Chief Minister of Assam (1946–1950) and a Bharat Ratna awardee.\nগোপীনাথ বৰদলৈ অসমৰ প্ৰথম মুখ্যমন্ত্ৰী (১৯৪৬–১৯৫০) আছিল আৰু ভাৰত ৰত্ন বঁটা বিজয়ী।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Kati Bihu is also known as:\nকাতি বিহুক আন এটা নামেৰেও জনা যায়:",
      options: [
        'Rongali Bihu / ৰঙালী বিহু',
        'Bhogali Bihu / ভোগালী বিহু',
        'Magh Bihu / মাঘ বিহু',
        'Kongali Bihu / কোংগালী বিহু',
      ],
      correctAnswerIndex: 3,
      explanation: "Kati Bihu is celebrated in autumn when granaries are empty, hence the name 'Kongali' (poor) Bihu.\nকাতি বিহু শৰত কালত উদযাপন কৰা হয় যেতিয়া গোদাউৰি খালী থাকে, সেয়ে ইয়াক 'কোংগালী' (দুখীয়া) বিহু বোলে।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which is the largest river island in the world, located in Assam?\nঅসমত অৱস্থিত বিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপটো কোনটো?",
      options: [
        'Umananda / উমানন্দ',
        'Majuli / মাজুলী',
        'Peacock Island / ময়ূৰ দ্বীপ',
        'Diu / দিউ',
      ],
      correctAnswerIndex: 1,
      explanation: "Majuli, in the Brahmaputra river, is recognised as the largest river island in the world.\nব্ৰহ্মপুত্ৰ নদীৰ মাজত থকা মাজুলী বিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপ হিচাপে স্বীকৃত।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Assam is world-famous for the production of which of the following?\nঅসম তলৰ কোনটোৰ উৎপাদনৰ বাবে বিশ্ববিখ্যাত?",
      options: [
        'Tea / চাহ',
        'Coffee / কফি',
        'Rubber / ৰবৰ',
        'Silk / পাট',
      ],
      correctAnswerIndex: 0,
      explanation: "Assam is one of the largest tea-producing regions in the world, known for its strong CTC tea.\nঅসম বিশ্বৰ অন্যতম বৃহৎ চাহ উৎপাদক অঞ্চল, ইয়াৰ গভীৰ CTC চাহৰ বাবে জনাজাত।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "When was the Constitution of India adopted?\nভাৰতৰ সংবিধান কেতিয়া গৃহীত হৈছিল?",
      options: [
        '26 January 1950 / ২৬ জানুৱাৰী ১৯৫০',
        '15 August 1947 / ১৫ আগষ্ট ১৯৪৭',
        '26 November 1949 / ২৬ নৱেম্বৰ ১৯৪৯',
        '2 October 1950 / ২ অক্টোবৰ ১৯৫০',
      ],
      correctAnswerIndex: 2,
      explanation: "The Constitution was adopted on 26 November 1949 and came into force on 26 January 1950.\nসংবিধান ২৬ নৱেম্বৰ ১৯৪৯ ত গৃহীত হৈছিল আৰু ২৬ জানুৱাৰী ১৯৫০ ত কাৰ্যকৰ হয়।",
      subjectTopic: 'Constitution',
      marks: 1,
    },
    {
      question: "The Upper House of the Indian Parliament is called:\nভাৰতীয় সংসদৰ উচ্চ সদনটোক কোৱা হয়:",
      options: [
        'Lok Sabha / লোকসভা',
        'Vidhan Sabha / বিধানসভা',
        'Vidhan Parishad / বিধান পৰিষদ',
        'Rajya Sabha / ৰাজ্যসভা',
      ],
      correctAnswerIndex: 3,
      explanation: "The Rajya Sabha (Council of States) is the Upper House; the Lok Sabha is the Lower House.\nৰাজ্যসভা (Council of States) হ’ল উচ্চ সদন; লোকসভা হ’ল নিম্ন সদন।",
      subjectTopic: 'Constitution',
      marks: 1,
    },
    {
      question: "Which is the longest river in India?\nভাৰতৰ দীৰ্ঘতম নদী কোনখন?",
      options: [
        'Ganga / গংগা',
        'Yamuna / যমুনা',
        'Godavari / গোদাৱৰী',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "The Ganga, about 2,525 km long, is considered the longest river in India.\nপ্ৰায় ২,৫২৫ কিলোমিটাৰ দৈৰ্ঘ্যৰ গংগা ভাৰতৰ দীৰ্ঘতম নদী হিচাপে গণ্য কৰা হয়।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "Who was the Chairman of the Constituent Assembly of India?\nভাৰতৰ গণপৰিষদৰ সভাপতি কোন আছিল?",
      options: [
        'Dr. B. R. Ambedkar / ডঃ বি আৰ আম্বেদকাৰ',
        'Dr. Rajendra Prasad / ডঃ ৰাজেন্দ্ৰ প্ৰসাদ',
        'Jawaharlal Nehru / জৱাহৰলাল নেহৰু',
        'Sardar Patel / সৰ্দাৰ পটেল',
      ],
      correctAnswerIndex: 1,
      explanation: "Dr. Rajendra Prasad was the President (Chairman) of the Constituent Assembly; Dr. Ambedkar chaired the Drafting Committee.\nডঃ ৰাজেন্দ্ৰ প্ৰসাদ গণপৰিষদৰ সভাপতি আছিল; ডঃ আম্বেদকাৰে খচৰা সমিতিৰ নেতৃত্ব দিছিল।",
      subjectTopic: 'Constitution',
      marks: 1,
    },
    {
      question: "How many members are nominated to the Rajya Sabha by the President of India?\nভাৰতৰ ৰাষ্ট্ৰপতিয়ে ৰাজ্যসভালৈ কিমানজন সদস্য মনোনীত কৰে?",
      options: [
        '10 / ১০',
        '14 / ১৪',
        '12 / ১২',
        '8 / ৮',
      ],
      correctAnswerIndex: 2,
      explanation: "The President nominates 12 members to the Rajya Sabha from fields like literature, science, art and social service.\nৰাষ্ট্ৰপতিয়ে সাহিত্য, বিজ্ঞান, কলা আৰু সমাজসেৱাৰ ক্ষেত্ৰৰ পৰা ৰাজ্যসভালৈ ১২ জন সদস্য মনোনীত কৰে।",
      subjectTopic: 'Constitution',
      marks: 1,
    },
    {
      question: "Which is the highest mountain peak entirely within Indian territory?\nসম্পূৰ্ণভাৱে ভাৰতীয় ভূখণ্ডৰ ভিতৰত থকা আটাইতকৈ উচ্চতম শৃংগটো কোনটো?",
      options: [
        'Nanda Devi / নন্দা দেৱী',
        'K2 / কে২',
        'Mount Everest / মাউণ্ট এভাৰেষ্ট',
        'Kanchenjunga / কাঞ্চনজংঘা',
      ],
      correctAnswerIndex: 3,
      explanation: "Kanchenjunga (8,586 m) is the highest peak entirely within India; K2 lies in PoK and Everest in Nepal.\nকাঞ্চনজংঘা (৮,৫৮৬ মিটাৰ) সম্পূৰ্ণভাৱে ভাৰতৰ ভিতৰত থকা আটাইতকৈ উচ্চ শৃংগ; কে২ PoK ত আৰু এভাৰেষ্ট নেপালত।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "Fundamental Rights are enshrined in which Part of the Indian Constitution?\nমৌলিক অধিকাৰ ভাৰতীয় সংবিধানৰ কোন ভাগত সন্নিবিষ্ট আছে?",
      options: [
        'Part III / তৃতীয় ভাগ',
        'Part IV / চতুৰ্থ ভাগ',
        'Part II / দ্বিতীয় ভাগ',
        'Part V / পঞ্চম ভাগ',
      ],
      correctAnswerIndex: 0,
      explanation: "Fundamental Rights (Articles 12–35) are in Part III; Part IV contains the Directive Principles.\nমৌলিক অধিকাৰ (অনুচ্ছেদ ১২–৩৫) তৃতীয় ভাগত আছে; চতুৰ্থ ভাগত ৰাষ্ট্ৰ নীতি নিৰ্দেশক থাকে।",
      subjectTopic: 'Constitution',
      marks: 1,
    },
    {
      question: "What is the state animal of Assam?\nঅসমৰ ৰাজ্যিক জন্তু কি?",
      options: [
        'Royal Bengal Tiger / ৰয়েল বেংগল বাঘ',
        'One-horned rhinoceros / এশিঙীয়া গঁড়',
        'Asian elephant / এছিয়ান হাতী',
        'Hoolock gibbon / হুলক গিবন',
      ],
      correctAnswerIndex: 1,
      explanation: "The one-horned rhinoceros (Indian rhinoceros) is the state animal of Assam.\nএশিঙীয়া গঁড় (Indian rhinoceros) অসমৰ ৰাজ্যিক জন্তু।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "The Bihu dance is associated with which state?\nবিহু নৃত্য কোন ৰাজ্যৰ সৈতে জড়িত?",
      options: [
        'Manipur / মণিপুৰ',
        'Meghalaya / মেঘালয়',
        'Assam / অসম',
        'Tripura / ত্ৰিপুৰা',
      ],
      correctAnswerIndex: 2,
      explanation: "Bihu is the folk dance of Assam, performed mainly during Rongali Bihu in mid-April.\nবিহু অসমৰ লোকনৃত্য, মূলতঃ এপ্ৰিল মাহৰ মাজভাগত ৰঙালী বিহুৰ সময়ত পৰিবেশন কৰা হয়।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Who was the first President of India?\nভাৰতৰ প্ৰথম ৰাষ্ট্ৰপতি কোন আছিল?",
      options: [
        'Dr. S. Radhakrishnan / ডঃ এছ ৰাধাকৃষ্ণণ',
        'Zakir Husain / জাকিৰ হুছেইন',
        'V. V. Giri / ভিভি গিৰি',
        'Dr. Rajendra Prasad / ডঃ ৰাজেন্দ্ৰ প্ৰসাদ',
      ],
      correctAnswerIndex: 3,
      explanation: "Dr. Rajendra Prasad was the first President of India (1950–1962).\nডঃ ৰাজেন্দ্ৰ প্ৰসাদ ভাৰতৰ প্ৰথম ৰাষ্ট্ৰপতি (১৯৫০–১৯৬২) আছিল।",
      subjectTopic: 'India GK',
      marks: 1,
    },
  ],

  // ===========================================================================
  // sec-reasoning — Reasoning (20)
  // Verbal & non-verbal: analogy, classification, series, coding-decoding,
  // blood relations, direction sense.
  // ===========================================================================
  'sec-reasoning': [
    {
      question: "Dog : Puppy :: Cat : ?\nকুকুৰা : পোৱালি :: মেকুৰী : ?",
      options: [
        'Kitten / পোৱালি',
        'Cub / পোৱালি (সিংহৰ)',
        'Calf / পোৱালি (গৰুৰ)',
        'Foal / পোৱালি (ঘোঁৰাৰ)',
      ],
      correctAnswerIndex: 0,
      explanation: "A puppy is the young one of a dog; the young one of a cat is a kitten.\nকুকুৰাৰ পোৱালিক puppy বোলে; মেকুৰীৰ পোৱালিক kitten বোলে।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Hand : Glove :: Foot : ?\nহাত : গ্লাভ :: ভৰি : ?",
      options: [
        'Sock / মোজা',
        'Shoe / জোতা',
        'Toe / আঙুলি',
        'Sandal / চেণ্ডেল',
      ],
      correctAnswerIndex: 1,
      explanation: "A glove is worn on the hand; a shoe is worn on the foot — the closest single-item analogy.\nগ্লাভ হাতত পিন্ধা হয়; জোতা ভৰিত পিন্ধা হয় — আটাইতকৈ ওচৰৰ সমতুল্য বস্তু।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Find the next term: 2, 4, 8, 16, ?\nপৰৱৰ্তী পদটো বিচাৰক: 2, 4, 8, 16, ?",
      options: [
        '24 / ২৪',
        '30 / ৩০',
        '32 / ৩২',
        '18 / ১৮',
      ],
      correctAnswerIndex: 2,
      explanation: "Each term is doubled: 16 × 2 = 32.\nপ্ৰতিটো পদ দুগুণ হয়: 16 × 2 = 32।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Find the next term: 1, 4, 9, 16, 25, ?\nপৰৱৰ্তী পদটো বিচাৰক: 1, 4, 9, 16, 25, ?",
      options: [
        '30 / ৩০',
        '49 / ৪৯',
        '35 / ৩৫',
        '36 / ৩৬',
      ],
      correctAnswerIndex: 3,
      explanation: "These are perfect squares (1², 2², 3², 4², 5²); the next is 6² = 36.\nএইবোৰ পূর্ণবৰ্গ (1², 2², 3², 4², 5²); পৰৱৰ্তী হ’ল 6² = 36।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "If CAT is coded as 24 (3+1+20), then DOG is coded as:\nযদি CAT ক 24 (3+1+20) হিচাপে কোড কৰা হয়, তেন্তে DOG ক কি হিচাপে কোড কৰা হ’ব?",
      options: [
        '26 / ২৬',
        '27 / ২৭',
        '28 / ২৮',
        '25 / ২৫',
      ],
      correctAnswerIndex: 0,
      explanation: "D=4, O=15, G=7; sum = 4 + 15 + 7 = 26.\nD=4, O=15, G=7; যোগফল = 4 + 15 + 7 = 26।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "Find the odd one out: Apple, Mango, Carrot, Banana.\nবেলেগটো বিচাৰক: আপেল, আম, গাজৰ, কেলা।",
      options: [
        'Apple / আপেল',
        'Carrot / গাজৰ',
        'Mango / আম',
        'Banana / কেলা',
      ],
      correctAnswerIndex: 1,
      explanation: "Carrot is a vegetable; the others (apple, mango, banana) are fruits.\nগাজৰ এটা শাক-পাচন; বাকীবোৰ (আপেল, আম, কেলা) ফল।",
      subjectTopic: 'Classification',
      marks: 1,
    },
    {
      question: "Find the odd one out: Sparrow, Crow, Bat, Pigeon.\nবেলেগটো বিচাৰক: চৰাই, কাউৰী, বাদুলি, পাৰা।",
      options: [
        'Sparrow / চৰাই',
        'Crow / কাউৰী',
        'Bat / বাদুলি',
        'Pigeon / পাৰা',
      ],
      correctAnswerIndex: 2,
      explanation: "A bat is a mammal, not a bird; the others are birds.\nবাদুলি এটা স্তন্যপায়ী, চৰাই নহয়; বাকীবোৰ চৰাই।",
      subjectTopic: 'Classification',
      marks: 1,
    },
    {
      question: "Pointing to a man, a woman said, \"His mother is the only daughter of my mother.\" How is the woman related to the man?\nএজন মানুহক দেখুৱাই এগৰাকী মহিলাই ক’লে, \"তেওঁৰ মাক মোৰ মাকৰ একমাত্ৰ কন্যা।\" মহিলাগৰাকী মানুহজনৰ কি আপোন?",
      options: [
        'Sister / ভগ্নী',
        'Aunt / খুড়ীয়েক',
        'Daughter / জীয়েক',
        'Mother / মাক',
      ],
      correctAnswerIndex: 3,
      explanation: "'The only daughter of my mother' = the woman herself; so the woman is the man's mother.\n'মোৰ মাকৰ একমাত্ৰ কন্যা' = মহিলাগৰাকী নিজেই; গতিকে মহিলাগৰাকী মানুহজনৰ মাক।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "A man walks 3 km north, then turns east and walks 4 km. How far is he from the starting point?\nএজন মানুহে ৩ কিমি উত্তৰলৈ খোজ কাঢ়িলে, তাৰ পিছত পূবলৈ ঘুৰি ৪ কিমি খোজ কাঢ়িলে। আৰম্ভণি স্থানৰ পৰা তেওঁ কিমান দূৰত আছে?",
      options: [
        '5 km / ৫ কিমি',
        '7 km / ৭ কিমি',
        '12 km / ১২ কিমি',
        '1 km / ১ কিমি',
      ],
      correctAnswerIndex: 0,
      explanation: "Using Pythagoras: √(3² + 4²) = √(9 + 16) = √25 = 5 km.\nপাইথাগোৰাছ সূত্ৰ: √(3² + 4²) = √(9 + 16) = √25 = ৫ কিমি।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "Find the next term: 3, 6, 9, 12, ?\nপৰৱৰ্তী পদটো বিচাৰক: 3, 6, 9, 12, ?",
      options: [
        '18 / ১৮',
        '15 / ১৫',
        '14 / ১৪',
        '21 / ২১',
      ],
      correctAnswerIndex: 1,
      explanation: "The series increases by 3 each time: 12 + 3 = 15.\nশ্ৰেণীটো প্ৰতিবাৰ ৩ কৈ বাঢ়ে: 12 + 3 = 15।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Doctor : Hospital :: Teacher : ?\nডাক্তৰ : চিকিৎসালয় :: শিক্ষয়িত্ৰী : ?",
      options: [
        'Student / ছাত্ৰ',
        'Class / শ্ৰেণী',
        'School / বিদ্যালয়',
        'College / মহাবিদ্যালয়',
      ],
      correctAnswerIndex: 2,
      explanation: "A doctor works in a hospital; a teacher works in a school — the workplace analogy.\nডাক্তৰে চিকিৎসালয়ত কাম কৰে; শিক্ষকে বিদ্যালয়ত কাম কৰে — কৰ্মস্থানৰ সমতুল্যতা।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "If A=1, B=2, C=3, ..., then BAD = ?\nযদি A=1, B=2, C=3, ..., তেন্তে BAD = ?",
      options: [
        '8 / ৮',
        '9 / ৯',
        '6 / ৬',
        '7 / ৭',
      ],
      correctAnswerIndex: 3,
      explanation: "B=2, A=1, D=4; sum = 2 + 1 + 4 = 7.\nB=2, A=1, D=4; যোগফল = 2 + 1 + 4 = 7।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "Find the odd one out: Triangle, Square, Circle, Cube.\nবেলেগটো বিচাৰক: ত্ৰিভুজ, বৰ্গ, বৃত্ত, ঘনক।",
      options: [
        'Cube / ঘনক',
        'Triangle / ত্ৰিভুজ',
        'Square / বৰ্গ',
        'Circle / বৃত্ত',
      ],
      correctAnswerIndex: 0,
      explanation: "Cube is a three-dimensional (solid) figure; the others are two-dimensional (plane) figures.\nঘনক এটা ত্ৰিমাত্ৰিক (গোটা) আকৃতি; বাকীবোৰ দ্বিমাত্ৰিক (সমতল) আকৃতি।",
      subjectTopic: 'Classification',
      marks: 1,
    },
    {
      question: "A is the father of B, but B is not the son of A. How is B related to A?\nA, B ৰ দেউতাক, কিন্তু B, A ৰ পুত্ৰ নহয়। B, A ৰ কেনেকৈ আপোন?",
      options: [
        'Niece / ভতিজী',
        'Daughter / জীয়েক',
        'Nephew / ভতিজা',
        'Cousin / সম্পৰ্কীয় ভাই-ভনী',
      ],
      correctAnswerIndex: 1,
      explanation: "B is A's child but not a son, so B must be A's daughter.\nB, A ৰ সন্তান কিন্তু পুত্ৰ নহয়, সেয়ে B, A ৰ জীয়েক।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "If South-East becomes North, then what does North become?\nযদি দক্ষিণ-পূব উত্তৰ হয়, তেন্তে উত্তৰ কি হ’ব?",
      options: [
        'North-East / উত্তৰ-পূব',
        'North-West / উত্তৰ-পশ্চিম',
        'South-West / দক্ষিণ-পশ্চিম',
        'South-East / দক্ষিণ-পূব',
      ],
      correctAnswerIndex: 2,
      explanation: "SE→N is a 135° anticlockwise rotation; applying the same to N gives South-West.\nSE→N হ’ল ১৩৫° ঘড়ীৰ বিপৰীত দিশত ঘূৰ্ণন; একেই ঘূর্ণন N ত প্ৰয়োগ কৰিলে দক্ষিণ-পশ্চিম পোৱা যায়।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "If TABLE is coded as UBCMF (each letter +1), then CHAIR is coded as:\nযদি TABLE ক UBCMF (প্ৰতিটো আখৰ +1) হিচাপে কোড কৰা হয়, তেন্তে CHAIR ক কি হিচাপে কোড কৰা হ’ব?",
      options: [
        'DJBJS / DJBJS',
        'DIKBR / DIKBR',
        'EIBJS / EIBJS',
        'DIBJS / DIBJS',
      ],
      correctAnswerIndex: 3,
      explanation: "Shift each letter forward by 1: C→D, H→I, A→B, I→J, R→S = DIBJS.\nপ্ৰতিটো আখৰ ১ আগুৱাই নিয়ক: C→D, H→I, A→B, I→J, R→S = DIBJS।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "Find the next term: 1, 1, 2, 6, 24, ?\nপৰৱৰ্তী পদটো বিচাৰক: 1, 1, 2, 6, 24, ?",
      options: [
        '120 / ১২০',
        '60 / ৬০',
        '30 / ৩০',
        '720 / ৭২০',
      ],
      correctAnswerIndex: 0,
      explanation: "These are factorials: 0!=1, 1!=1, 2!=2, 3!=6, 4!=24; the next is 5! = 120.\nএইবোৰ ফেক্টৰিয়েল: 0!=1, 1!=1, 2!=2, 3!=6, 4!=24; পৰৱৰ্তী 5! = 120।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Clock : Time :: Thermometer : ?\nঘড়ী : সময় :: থাৰ্মোমিটাৰ : ?",
      options: [
        'Heat / উষ্ণতা',
        'Temperature / তাপমাত্ৰা',
        'Mercury / পাৰা',
        'Doctor / ডাক্তৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "A clock measures time; a thermometer measures temperature.\nঘড়ীয়ে সময় জোখে; থাৰ্মোমিটাৰে তাপমাত্ৰা জোখে।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Find the odd one out: Rose, Lotus, Marigold, Mango.\nবেলেগটো বিচাৰক: গোলাপ, পদুম, গোলমৰীয়া, আম।",
      options: [
        'Rose / গোলাপ',
        'Lotus / পদুম',
        'Mango / আম',
        'Marigold / গোলমৰীয়া',
      ],
      correctAnswerIndex: 2,
      explanation: "Mango is a fruit-bearing tree; rose, lotus and marigold are flowers.\nআম এজোপা ফলৰ গছ; গোলাপ, পদুম আৰু গোলমৰীয়া ফুল।",
      subjectTopic: 'Classification',
      marks: 1,
    },
    {
      question: "Introducing a man, a woman said, \"He is the son of my grandfather's only son.\" How is the man related to the woman?\nএজন মানুহক পৰিচয় দি এগৰাকী মহিলাই ক’লে, \"তেওঁ মোৰ ককাদেউতাকৰ একমাত্ৰ পুত্ৰৰ পুত্ৰ।\" মানুহজন মহিলাগৰাকীৰ কি আপোন?",
      options: [
        'Father / দেউতাক',
        'Uncle / খুড়া',
        'Cousin / সম্পৰ্কীয় ভাই',
        'Brother / ককাই-ভাই',
      ],
      correctAnswerIndex: 3,
      explanation: "Grandfather's only son = the woman's father; her father's son = her brother (since the person is male).\nককাদেউতাকৰ একমাত্ৰ পুত্ৰ = মহিলাগৰাকীৰ দেউতাক; দেউতাকৰ পুত্ৰ = তেওঁৰ ভাই (যিহেতু ব্যক্তিজন পুৰুষ)।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
  ],

  // ===========================================================================
  // sec-computer — Computer Knowledge (20)
  // MS Office shortcuts/functions, internet, computer fundamentals
  // (hardware, OS, memory, I/O), networking basics.
  // ===========================================================================
  'sec-computer': [
    {
      question: "Which shortcut key is used to select all text in MS Word?\nMS Word ত সকলো টেক্সট নিৰ্বাচন কৰিবলৈ কোনটো শৰ্টকাট কি ব্যৱহাৰ কৰা হয়?",
      options: [
        'Ctrl + A / Ctrl + A',
        'Ctrl + S / Ctrl + S',
        'Ctrl + C / Ctrl + C',
        'Ctrl + V / Ctrl + V',
      ],
      correctAnswerIndex: 0,
      explanation: "Ctrl + A selects the entire document in MS Word.\nMS Word ত Ctrl + A এ সম্পূৰ্ণ দস্তাবেজ নিৰ্বাচন কৰে।",
      subjectTopic: 'MS Word',
      marks: 1,
    },
    {
      question: "What does the SUM function do in MS Excel?\nMS Excel ত SUM ফাংচনে কি কৰে?",
      options: [
        'Multiplies numbers / সংখ্যা গুণ কৰে',
        'Adds numbers / সংখ্যা যোগ কৰে',
        'Divides numbers / সংখ্যা হৰণ কৰে',
        'Subtracts numbers / সংখ্যা বিয়োগ কৰে',
      ],
      correctAnswerIndex: 1,
      explanation: "=SUM(range) adds all the numbers in the given range of cells.\n=SUM(range) এ নিৰ্দিষ্ট কোষৰ পৰিসৰৰ সকলো সংখ্যা যোগ কৰে।",
      subjectTopic: 'MS Excel',
      marks: 1,
    },
    {
      question: "Which key starts a PowerPoint slideshow from the beginning?\nPowerPoint ত প্ৰদৰ্শন আৰম্ভণিৰ পৰা আৰম্ভ কৰিবলৈ কোনটো কি ব্যৱহাৰ কৰা হয়?",
      options: [
        'F1 / F1',
        'F7 / F7',
        'F5 / F5',
        'F12 / F12',
      ],
      correctAnswerIndex: 2,
      explanation: "F5 starts the slideshow from the first slide; Shift+F5 starts from the current slide.\nF5 এ প্ৰথম স্লাইডৰ পৰা প্ৰদৰ্শন আৰম্ভ কৰে; Shift+F5 এ বৰ্তমান স্লাইডৰ পৰা আৰম্ভ কৰে।",
      subjectTopic: 'MS PowerPoint',
      marks: 1,
    },
    {
      question: "What does \"WWW\" stand for?\n\"WWW\" ৰ সম্পূৰ্ণ ৰূপ কি?",
      options: [
        'Wide World Web / Wide World Web',
        'World Web Wide / World Web Wide',
        'Web World Wide / Web World Wide',
        'World Wide Web / World Wide Web',
      ],
      correctAnswerIndex: 3,
      explanation: "WWW stands for World Wide Web, an information system on the Internet.\nWWW ৰ সম্পূৰ্ণ ৰূপ World Wide Web, ইণ্টাৰনেটৰ এটা তথ্য ব্যৱস্থা।",
      subjectTopic: 'Internet',
      marks: 1,
    },
    {
      question: "Which of the following is called the \"brain\" of the computer?\nতলৰ কোনটোক কম্পিউটাৰৰ \"মগজু\" বোলা হয়?",
      options: [
        'CPU / CPU',
        'RAM / RAM',
        'Hard disk / হাৰ্ড ডিস্ক',
        'Monitor / মনিটৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "The CPU (Central Processing Unit) controls all operations and is called the brain of the computer.\nCPU (Central Processing Unit) এ সকলো কাৰ্য নিয়ন্ত্ৰণ কৰে আৰু ইয়াক কম্পিউটাৰৰ মগজু বোলা হয়।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "Which of the following is an operating system?\nতলৰ কোনটো এটা অপাৰেটিং চিষ্টেম?",
      options: [
        'MS Word / MS Word',
        'Windows / Windows',
        'MS Excel / MS Excel',
        'Photoshop / ফটোশ্বপ',
      ],
      correctAnswerIndex: 1,
      explanation: "Microsoft Windows is an operating system; the others are application software.\nমাইক্ৰ’ছফট উইণ্ড’জ এটা অপাৰেটিং চিষ্টেম; বাকীবোৰ এপ্লিকেচন ছফ্টৱেৰ।",
      subjectTopic: 'OS',
      marks: 1,
    },
    {
      question: "RAM stands for:\nRAM ৰ সম্পূৰ্ণ ৰূপ কি?",
      options: [
        'Read Access Memory / Read Access Memory',
        'Rapid Access Memory / Rapid Access Memory',
        'Random Access Memory / Random Access Memory',
        'Random Active Memory / Random Active Memory',
      ],
      correctAnswerIndex: 2,
      explanation: "RAM = Random Access Memory; it is the volatile working memory of a computer.\nRAM = Random Access Memory; ই কম্পিউটাৰৰ অস্থায়ী কাৰ্য স্মৃতি।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "Which of the following is an input device?\nতলৰ কোনটো এটা ইনপুট ডিভাইচ?",
      options: [
        'Printer / প্ৰিণ্টাৰ',
        'Monitor / মনিটৰ',
        'Speaker / স্পিকাৰ',
        'Keyboard / কীব’ৰ্ড',
      ],
      correctAnswerIndex: 3,
      explanation: "A keyboard sends data into the computer (input); printer, monitor and speaker are output devices.\nকীব’ৰ্ডে কম্পিউটাৰলৈ তথ্য পঠিয়ায় (ইনপুট); প্ৰিণ্টাৰ, মনিটৰ আৰু স্পিকাৰ আউটপুট ডিভাইচ।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "What does \"LAN\" stand for?\n\"LAN\" ৰ সম্পূৰ্ণ ৰূপ কি?",
      options: [
        'Local Area Network / Local Area Network',
        'Large Area Network / Large Area Network',
        'Long Area Network / Long Area Network',
        'Limited Area Network / Limited Area Network',
      ],
      correctAnswerIndex: 0,
      explanation: "LAN = Local Area Network; it connects computers within a small area like an office.\nLAN = Local Area Network; ই এটা কাৰ্যালয়ৰ দৰে সৰু অঞ্চলৰ কম্পিউটাৰ সংযোগ কৰে।",
      subjectTopic: 'Networking',
      marks: 1,
    },
    {
      question: "In MS Excel, every formula must begin with which symbol?\nMS Excel ত প্ৰতিটো সূত্ৰ কোনটো চিহ্নৰে আৰম্ভ হ’ব লাগিব?",
      options: [
        '+ (plus) / + (যোগ)',
        '= (equals) / = (সমান)',
        '- (minus) / - (বিয়োগ)',
        '@ (at) / @ (এট)',
      ],
      correctAnswerIndex: 1,
      explanation: "Excel formulas always begin with the '=' sign so Excel knows to evaluate the entry.\nExcel সূত্ৰ সদায় '=' চিহ্নৰে আৰম্ভ হয় যাতে Excel লৈ জানিব পাৰে ইয়াক গণনা কৰিব লাগিব।",
      subjectTopic: 'MS Excel',
      marks: 1,
    },
    {
      question: "Which shortcut key is used to copy text in MS Word?\nMS Word ত টেক্সট কপি কৰিবলৈ কোনটো শৰ্টকাট কি ব্যৱহাৰ কৰা হয়?",
      options: [
        'Ctrl + V / Ctrl + V',
        'Ctrl + X / Ctrl + X',
        'Ctrl + C / Ctrl + C',
        'Ctrl + P / Ctrl + P',
      ],
      correctAnswerIndex: 2,
      explanation: "Ctrl + C copies the selected text; Ctrl + V pastes; Ctrl + X cuts.\nCtrl + C এ নিৰ্বাচিত টেক্সট কপি কৰে; Ctrl + V পেষ্ট কৰে; Ctrl + X কাট কৰে।",
      subjectTopic: 'MS Word',
      marks: 1,
    },
    {
      question: "Which of the following is a web browser?\nতলৰ কোনটো এটা ৱেব ব্ৰাউজাৰ?",
      options: [
        'MS Word / MS Word',
        'MS Excel / MS Excel',
        'Photoshop / ফটোশ্বপ',
        'Google Chrome / গুগল ক্ৰোম',
      ],
      correctAnswerIndex: 3,
      explanation: "Google Chrome is a web browser used to access websites; the others are application software.\nগুগল ক্ৰোম এটা ৱেব ব্ৰাউজাৰ যি ৱেবছাইট চাবলৈ ব্যৱহৃত হয়; বাকীবোৰ এপ্লিকেচন ছফ্টৱেৰ।",
      subjectTopic: 'Internet',
      marks: 1,
    },
    {
      question: "Which device is used to point and click on the screen?\nস্ক্ৰীণত পইণ্ট আৰু ক্লিক কৰিবলৈ কোনটো ডিভাইচ ব্যৱহাৰ কৰা হয়?",
      options: [
        'Mouse / মাউছ',
        'Keyboard / কীব’ৰ্ড',
        'Printer / প্ৰিণ্টাৰ',
        'Scanner / স্কেনাৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "A mouse is a pointing device used to interact with on-screen objects.\nমাউছ এটা পইণ্টিং ডিভাইচ যি স্ক্ৰীণৰ বস্তুৰ সৈতে ক্ৰিয়া কৰিবলৈ ব্যৱহৃত হয়।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "The \"Desktop\" is a feature of which of the following?\n\"Desktop\" তলৰ কোনটোৰ এটা বৈশিষ্ট্য?",
      options: [
        'Application software / এপ্লিকেচন ছফ্টৱেৰ',
        'Operating system / অপাৰেটিং চিষ্টেম',
        'Hardware / হাৰ্ডৱেৰ',
        'Network / নেটৱৰ্ক',
      ],
      correctAnswerIndex: 1,
      explanation: "The Desktop is the main workspace of a graphical operating system like Windows.\nDesktop হ’ল Windows ৰ দৰে গ্ৰাফিকেল অপাৰেটিং চিষ্টেমৰ মুখ্য কৰ্মক্ষেত্ৰ।",
      subjectTopic: 'OS',
      marks: 1,
    },
    {
      question: "Which of the following memory is volatile?\nতলৰ কোনটো স্মৃতি প্ৰণয়নশীল (volatile)?",
      options: [
        'Hard disk / হাৰ্ড ডিস্ক',
        'ROM / ROM',
        'RAM / RAM',
        'CD-ROM / CD-ROM',
      ],
      correctAnswerIndex: 2,
      explanation: "RAM is volatile — its contents are lost when the power is switched off; ROM and disks are non-volatile.\nRAM প্ৰণয়নশীল — বিদ্যুৎ বন্ধ কৰিলে ইয়াৰ বিষয়বস্তু হেৰায়; ROM আৰু ডিস্ক অপ্ৰণয়নশীল।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "Which of the following is an output device?\nতলৰ কোনটো এটা আউটপুট ডিভাইচ?",
      options: [
        'Keyboard / কীব’ৰ্ড',
        'Mouse / মাউছ',
        'Scanner / স্কেনাৰ',
        'Monitor / মনিটৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "A monitor displays information from the computer (output); keyboard, mouse and scanner are input devices.\nমনিটৰে কম্পিউটাৰৰ তথ্য প্ৰদৰ্শন কৰে (আউটপুট); কীব’ৰ্ড, মাউছ আৰু স্কেনাৰ ইনপুট ডিভাইচ।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
    {
      question: "PowerPoint presentations are saved with which file extension by default?\nPowerPoint প্ৰদৰ্শন অবিকল্পিতভাৱে কোনটো ফাইল এক্সটেনচনৰে সংৰক্ষিত হয়?",
      options: [
        '.pptx / .pptx',
        '.docx / .docx',
        '.xlsx / .xlsx',
        '.pdf / .pdf',
      ],
      correctAnswerIndex: 0,
      explanation: "Modern PowerPoint saves files with the .pptx extension (XML-based format introduced in 2007).\nআধুনিক PowerPoint এ .pptx এক্সটেনচনৰে ফাইল সংৰক্ষণ কৰে (২০০৭ চনত আৰম্ভ কৰা XML-ভিত্তিক ফৰমেট)।",
      subjectTopic: 'MS PowerPoint',
      marks: 1,
    },
    {
      question: "Which shortcut key is used to undo an action in MS Word?\nMS Word ত এটা কাৰ্য undo কৰিবলৈ কোনটো শৰ্টকাট কি ব্যৱহাৰ কৰা হয়?",
      options: [
        'Ctrl + Y / Ctrl + Y',
        'Ctrl + Z / Ctrl + Z',
        'Ctrl + A / Ctrl + A',
        'Ctrl + U / Ctrl + U',
      ],
      correctAnswerIndex: 1,
      explanation: "Ctrl + Z undoes the last action; Ctrl + Y redoes it.\nCtrl + Z এ অন্তিম কাৰ্য undo কৰে; Ctrl + Y এ redo কৰে।",
      subjectTopic: 'MS Word',
      marks: 1,
    },
    {
      question: "What does \"IP\" stand for in computer networking?\nকম্পিউটাৰ নেটৱৰ্কিঙত \"IP\" ৰ সম্পূৰ্ণ ৰূপ কি?",
      options: [
        'Internal Protocol / Internal Protocol',
        'Inter Protocol / Inter Protocol',
        'Internet Protocol / Internet Protocol',
        'Internet Provider / Internet Provider',
      ],
      correctAnswerIndex: 2,
      explanation: "IP = Internet Protocol; it defines addresses for devices on a network (e.g., 192.168.1.1).\nIP = Internet Protocol; ই নেটৱৰ্কত থকা ডিভাইচবোৰৰ ঠিকনা নিৰ্ধাৰণ কৰে (যেনে 192.168.1.1)।",
      subjectTopic: 'Networking',
      marks: 1,
    },
    {
      question: "A collection of 8 bits is called:\n৮টা বিটৰ সংগ্ৰহক কি বোলা হয়?",
      options: [
        'Bit / বিট',
        'Nibble / নিবল',
        'Word / ৱৰ্ড',
        'Byte / বাইট',
      ],
      correctAnswerIndex: 3,
      explanation: "8 bits = 1 byte; a nibble is 4 bits. A byte can represent 256 different values (0–255).\n৮ বিট = ১ বাইট; এটা nibble হ’ল ৪ বিট। এটা byte এ ২৫৬টা ভিন্ন মান (০–২৫৫) প্ৰতিনিধিত্ব কৰিব পাৰে।",
      subjectTopic: 'Hardware',
      marks: 1,
    },
  ],
};
