// =============================================================================
// ExamVault — Assam Police (Constable / SI) PART A
// Bilingual question pool — General Knowledge (police-gk) + Reasoning (police-reasoning)
//
// Format (CRITICAL — every field is bilingual EN + অসমীয়া):
//   question  -> "English\nঅসমীয়া"
//   option    -> "English / অসমীয়া"
//   expl      -> "English\nঅসমীয়া"
//
// police-gk       : 30 questions (Assam GK, India GK, Current Affairs)
// police-reasoning: 30 questions (Series, Analogy, Coding, Blood Relations,
//                                 Direction, Syllogism)
// Total = 60 bilingual items.
//
// correctAnswerIndex is distributed across 0,1,2,3 in each pool
// (per-30 distribution: 0→8, 1→8, 2→7, 3→7) so test slicing produces a
// balanced answer key.
//
// Level: HSLC to Graduation (Assam Police Constable / SI recruitment).
// All answers are verifiable from standard references.
// =============================================================================
import type { QuestionPoolMap } from './structure';

export const POLICE_POOLS_A: QuestionPoolMap = {
  // ===========================================================================
  // police-gk — General Knowledge (30)
  // ===========================================================================
  'police-gk': [
    // --- Assam GK (20) ---
    {
      question: "What is the capital of Assam?\nঅসমৰ ৰাজধানী কি?",
      options: [
        'Dispur / দিছপুৰ',
        'Guwahati / গুৱাহাটী',
        'Tezpur / তেজপুৰ',
        'Jorhat / যোৰহাট',
      ],
      correctAnswerIndex: 0,
      explanation: "Dispur, a locality within Guwahati, is the capital of Assam.\nগুৱাহাটীৰ ভিতৰত থকা দিছপুৰ অসমৰ ৰাজধানী।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "As of 2024, how many districts are there in Assam?\n২০২৪ চন অনুসৰি অসমত কিমানটা জিলা আছে?",
      options: [
        '33 / ৩৩',
        '35 / ৩৫',
        '34 / ৩৪',
        '27 / ২৭',
      ],
      correctAnswerIndex: 1,
      explanation: "As of 2024, Assam has 35 districts; Tamulpur (created in January 2022) is the most recently formed district.\n২০২৪ চন অনুসৰি অসমত ৩৫টা জিলা আছে; ২০২২ চনৰ জানুৱাৰীত গঠন হোৱা তামুলপুৰ আটাইতকৈ নতুন জিলা।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which is the longest river in Assam?\nঅসমৰ আটাইতকৈ দীঘল নদী কোনখন?",
      options: [
        'Barak / বৰাক',
        'Subansiri / সুবনসিৰি',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
        'Manas / মানস',
      ],
      correctAnswerIndex: 2,
      explanation: "The Brahmaputra flows about 916 km through Assam, making it the longest river in the state.\nব্ৰহ্মপুত্ৰ নদী অসমেদি প্ৰায় ৯১৬ কিঃমিঃ বৈ গৈ অসমৰ আটাইতকৈ দীঘল নদী।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "How many times is Bihu celebrated in a year?\nবছৰত কিমানবাৰ বিহু উদযাপন কৰা হয়?",
      options: [
        '1 / ১',
        '2 / ২',
        '4 / ৪',
        '3 / ৩',
      ],
      correctAnswerIndex: 3,
      explanation: "Bihu is celebrated three times a year — Rongali (Bohag) in April, Kongali (Kati) in October, and Bhogali (Magh) in January.\nবছৰত তিনিবাৰ বিহু উদযাপন কৰা হয় — এপ্ৰিলত ৰঙালী (বহাগ), অক্টোবৰত কঙালী (কাতি) আৰু জানুৱাৰীত ভোগালী (মাঘ)।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Dr. Bhupen Hazarika was a famous —\nড॰ ভূপেন হাজৰিকা এগৰাকী বিখ্যাত — আছিল?",
      options: [
        'Singer / গায়ক',
        'Politician / ৰাজনীতিবিদ',
        'Sportsperson / ক্ৰীড়াবিদ',
        'Scientist / বিজ্ঞানী',
      ],
      correctAnswerIndex: 0,
      explanation: "Dr. Bhupen Hazarika was an iconic Indian playback singer, lyricist and composer from Assam, popularly known as the Bard of Brahmaputra.\nড॰ ভূপেন হাজৰিকা অসমৰ এগৰাকী কিংবদন্তি প্লেবেক গায়ক, গীতিকাৰ আৰু সুৰকাৰ আছিল, যাক ব্ৰহ্মপুত্ৰৰ বৰগীত বুলি জনা যায়।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Who was the first Chief Minister of Assam?\nঅসমৰ প্ৰথমগৰাকী মুখ্যমন্ত্ৰী কোন আছিল?",
      options: [
        'Bishnuram Medhi / বিষ্ণুৰাম মেধি',
        'Gopinath Bordoloi / গোপীনাথ বৰদলৈ',
        'Sarat Chandra Sinha / শৰৎ চন্দ্ৰ সিনহা',
        'Fakhruddin Ali Ahmed / ফখৰুদ্দিন আলি আহমেদ',
      ],
      correctAnswerIndex: 1,
      explanation: "Gopinath Bordoloi was the first Chief Minister of Assam (1946–1950) and was honoured with the Bharat Ratna in 1999.\nগোপীনাথ বৰদলৈ অসমৰ প্ৰথমগৰাকী মুখ্যমন্ত্ৰী (১৯৪৬–১৯৫০) আছিল আৰু ১৯৯৯ চনত তেওঁক ভাৰত ৰত্ন সন্মান প্ৰদান কৰা হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Kaziranga National Park is famous for which animal?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান কোনটো জন্তুৰ বাবে বিখ্যাত?",
      options: [
        'Bengal Tiger / ৰয়েল বেংগল বাঘ',
        'Asian Elephant / এচিয়ান হাতী',
        'One-horned Rhinoceros / এশিঙীয়া গঁড়',
        'Snow Leopard / হিমালয়ৰ বৰফুৱা বাঘ',
      ],
      correctAnswerIndex: 2,
      explanation: "Kaziranga National Park, a UNESCO World Heritage Site, harbours the world's largest population of the Indian one-horned rhinoceros.\nইউনেস্কো বিশ্ব ঐতিহ্য কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যানত ভাৰতীয় এশিঙীয়া গঁড়ৰ বিশ্বৰ আটাইতকৈ ডাঙৰ জনসংখ্যা আছে।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Lachit Borphukan is remembered for which battle?\nলাচিত বৰফুকন কোনটো যুদ্ধৰ বাবে সোঁৱৰণ কৰা হয়?",
      options: [
        'Battle of Panipat / পানিপথৰ যুদ্ধ',
        'Battle of Haldighati / হলদিয়াঘাটিৰ যুদ্ধ',
        'Battle of Buxar / বক্সৰৰ যুদ্ধ',
        'Battle of Saraighat / শৰাইঘাটৰ যুদ্ধ',
      ],
      correctAnswerIndex: 3,
      explanation: "Lachit Borphukan led the Ahom army to victory against the Mughal forces led by Raja Ram Singh in the Battle of Saraighat in 1671.\nলাচিত বৰফুকনে ১৬৭১ চনত শৰাইঘাটৰ যুদ্ধত ৰাজা ৰাম সিংহৰ নেতৃত্বাধীন মোগল সেনাৰ বিৰুদ্ধে আহোম সেনাক বিজয়লৈ নেতৃত্ব দিছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Digboi is famously known for —\nডিগবৈ কিৰ বাবে বিখ্যাত?",
      options: [
        "Asia's first oil refinery / এচিয়াৰ প্ৰথম তেল পৰিশোধনাগাৰ",
        'Coal mining / কয়লা খনন',
        'Tea gardens / চাহ বাগিচা',
        'Hydroelectric power / জলবিদ্যুৎ শক্তি',
      ],
      correctAnswerIndex: 0,
      explanation: "Digboi in Tinsukia district houses Asia's first oil refinery (commissioned in 1901); commercial oil drilling began here in 1889.\nতিনিচুকীয়া জিলাৰ ডিগবৈত এচিয়াৰ প্ৰথম তেল পৰিশোধনাগাৰ অৱস্থিত (১৯০১ চনত স্থাপন); ইয়াত ১৮৮৯ চনৰ পৰা বাণিজ্যিক তেল খনন আৰম্ভ হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "The Bogibeel Bridge connects which two districts?\nবগিবিল দলংয়ে কোন দুটা জিলাক সংযোগ কৰে?",
      options: [
        'Dhubri and Phulbari / ধুবুৰী আৰু ফুলবাৰী',
        'Dibrugarh and Dhemaji / ডিব্ৰুগড় আৰু ধেমাজি',
        'Guwahati and North Guwahati / গুৱাহাটী আৰু উত্তৰ গুৱাহাটী',
        'Tezpur and Biswanath / তেজপুৰ আৰু বিশ্বনাথ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Bogibeel Bridge, India's longest rail-cum-road bridge over the Brahmaputra (4.94 km), connects Dibrugarh (south bank) with Dhemaji (north bank).\nবগিবিল দলং, ব্ৰহ্মপুত্ৰৰ ওপৰত ভাৰতৰ আটাইতকৈ দীঘল ৰেল-পথ দলং (৪.৯৪ কিঃমিঃ), ডিব্ৰুগড় (দক্ষিণ পাৰ) আৰু ধেমাজি (উত্তৰ পাৰ) সংযোগ কৰে।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "What is the State Animal of Assam?\nঅসমৰ ৰাজ্যিক জন্তু কি?",
      options: [
        'Tiger / বাঘ',
        'Elephant / হাতী',
        'One-horned Rhinoceros / এশিঙীয়া গঁড়',
        'Hoolock Gibbon / হলৌ গাবোন',
      ],
      correctAnswerIndex: 2,
      explanation: "The Indian one-horned rhinoceros (Rhinoceros unicornis) is the State Animal of Assam.\nভাৰতীয় এশিঙীয়া গঁড় (Rhinoceros unicornis) অসমৰ ৰাজ্যিক জন্তু।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Majuli, one of the world's largest river islands, is located in which river?\nবিশ্বৰ অন্যতম বৃহৎ নদী দ্বীপ মাজুলী কোনখন নদীত অৱস্থিত?",
      options: [
        'Barak / বৰাক',
        'Subansiri / সুবনসিৰি',
        'Manas / মানস',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "Majuli, recognised by the Guinness Book as the largest river island, lies in the Brahmaputra in upper Assam.\nমাজুলী, গিনিজ বুকত সৰ্ববৃহৎ নদী দ্বীপ হিচাপে স্বীকৃত, ওপৰ অসমৰ ব্ৰহ্মপুত্ৰ নদীত অৱস্থিত।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Which state is the largest producer of tea in India?\nভাৰতত কোনখন ৰাজ্য চাহৰ আটাইতকৈ ডাঙৰ উৎপাদক?",
      options: [
        'Assam / অসম',
        'West Bengal / পশ্চিম বংগ',
        'Tamil Nadu / তামিলনাডু',
        'Kerala / কেৰালা',
      ],
      correctAnswerIndex: 0,
      explanation: "Assam is the largest tea-producing state in India, contributing more than half of India's total tea output.\nঅসম ভাৰতৰ আটাইতকৈ ডাঙৰ চাহ উৎপাদক ৰাজ্য, ভাৰতৰ মুঠ চাহ উৎপাদনৰ আধাতকৈ অধিক অসমে যোগান ধৰে।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Rongali Bihu is celebrated in which month?\nৰঙালী বিহু কোনটো মাহত উদযাপন কৰা হয়?",
      options: [
        'January / জানুৱাৰী',
        'April / এপ্ৰিল',
        'October / অক্টোবৰ',
        'December / ডিচেম্বৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "Rongali or Bohag Bihu marks the Assamese New Year and is celebrated in mid-April.\nৰঙালী বা বহাগ বিহুৱে অসমীয়া নৱবৰ্ষ আৰম্ভ কৰে আৰু এপ্ৰিল মাহৰ মাজভাগত উদযাপন কৰা হয়।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Srimanta Sankardeva was a 15th–16th century —\nশ্ৰীমন্ত শংকৰদেৱ পোন্ধৰো ষোল্ল শতিকাৰ এগৰাকী — আছিল?",
      options: [
        'King / ৰজা',
        'Warrior / যোদ্ধা',
        'Saint-scholar / সন্ত-পণ্ডিত',
        'Musician / সংগীতজ্ঞ',
      ],
      correctAnswerIndex: 2,
      explanation: "Srimanta Sankardeva (1449–1568) was a saint-scholar who founded the Ekasarana Dharma and pioneered Neo-Vaishnavism in Assam.\nশ্ৰীমন্ত শংকৰদেৱ (১৪৪৯–১৫৬৮) এগৰাকী সন্ত-পণ্ডিত আছিল যিয়ে একশৰণ ধৰ্ম প্ৰতিষ্ঠা কৰিছিল আৰু অসমত নৱ-বৈষ্ণৱবাদৰ সূচনা কৰিছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "The Lokapriya Gopinath Bordoloi International Airport is located at —\nলোকপ্ৰিয় গোপীনাথ বৰদলৈ আন্তঃৰাষ্ট্ৰীয় বিমানবন্দৰ ক'ত অৱস্থিত?",
      options: [
        'Dibrugarh / ডিব্ৰুগড়',
        'Jorhat / যোৰহাট',
        'Tezpur / তেজপুৰ',
        'Guwahati / গুৱাহাটী',
      ],
      correctAnswerIndex: 3,
      explanation: "The Lokapriya Gopinath Bordoloi International Airport is located at Borjhar in Guwahati.\nলোকপ্ৰিয় গোপীনাথ বৰদলৈ আন্তঃৰাষ্ট্ৰীয় বিমানবন্দৰ গুৱাহাটীৰ বৰঝাৰত অৱস্থিত।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Over which river is the Saraighat Bridge built?\nশৰাইঘাট দলং কোনখন নদীৰ ওপৰত নিৰ্মিত?",
      options: [
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
        'Ganga / গংগা',
        'Barak / বৰাক',
        'Yamuna / যমুনা',
      ],
      correctAnswerIndex: 0,
      explanation: "The Saraighat Bridge, the first rail-cum-road bridge over the Brahmaputra, was opened to traffic in 1962 at Guwahati.\nশৰাইঘাট দলং, ব্ৰহ্মপুত্ৰৰ ওপৰত প্ৰথম ৰেল-পথ দলং, ১৯৬২ চনত গুৱাহাটীত যাতায়াতৰ বাবে মুকলি কৰা হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Assam was constituted as a separate Chief Commissioner's Province in which year?\nঅসম কোনচনত এক সুকীয়া মুখ্য আয়ুক্তৰ প্ৰদেশ হিচাপে গঠন কৰা হৈছিল?",
      options: [
        '1826 / ১৮২৬',
        '1874 / ১৮৭৪',
        '1905 / ১৯০৫',
        '1912 / ১৯১২',
      ],
      correctAnswerIndex: 1,
      explanation: "In 1874, Assam was separated from Bengal and constituted as a Chief Commissioner's Province with its capital at Shillong.\n১৮৭৪ চনত অসমক বংগৰ পৰা পৃথক কৰি শ্বিলঙক ৰাজধানী হিচাপে এক মুখ্য আয়ুক্তৰ প্ৰদেশ হিচাপে গঠন কৰা হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "The Talatal Ghar, a famous Ahom monument, is located at —\nবিখ্যাত আহোম স্মৃতিচিহ্ন তালাতল ঘৰ ক'ত অৱস্থিত?",
      options: [
        'Guwahati / গুৱাহাটী',
        'Tezpur / তেজপুৰ',
        'Sivasagar / শিৱসাগৰ',
        'Jorhat / যোৰহাট',
      ],
      correctAnswerIndex: 2,
      explanation: "The Talatal Ghar, the largest of the Ahom monuments, is located at Rangpur (present-day Sivasagar).\nআহোম স্মৃতিচিহ্নসমূহৰ ভিতৰত আটাইতকৈ ডাঙৰ তালাতল ঘৰ ৰঙাপুৰত (বৰ্তমান শিৱসাগৰ) অৱস্থিত।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    {
      question: "Kushal Konwar, a freedom fighter from Assam, was hanged in connection with —\nঅসমৰ স্বাধীনতা সংগ্ৰামী কুশল কোঁৱৰ কোনটো ঘটনাৰ সৈতে জড়িত হৈ ফাঁচী দিয়া হৈছিল?",
      options: [
        'Battle of Saraighat / শৰাইঘাটৰ যুদ্ধ',
        'Sepoy Mutiny 1857 / চিপাহী বিদ্ৰোহ ১৮৫৭',
        'Non-Cooperation Movement 1921 / অসহযোগ আন্দোলন ১৯২১',
        'Quit India Movement (Sarupathar train derailment) / ভাৰত ত্যাগ আন্দোলন (সৰুপথাৰ ৰেল দুৰ্ঘটনা)',
      ],
      correctAnswerIndex: 3,
      explanation: "Kushal Konwar was hanged on 15 June 1943 for his alleged role in the Sarupathar train derailment during the Quit India Movement of 1942.\nকুশল কোঁৱৰক ১৯৪২ চনৰ ভাৰত ত্যাগ আন্দোলনৰ সময়ত সৰুপথাৰ ৰেল দুৰ্ঘটনাত তেওঁৰ কথিত ভূমিকাৰ বাবে ১৫ জুন ১৯৪৩ ত ফাঁচী দিয়া হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 1,
    },
    // --- India GK (8) ---
    {
      question: "What is the national capital of India?\nভাৰতৰ ৰাষ্ট্ৰীয় ৰাজধানী কি?",
      options: [
        'New Delhi / নতুন দিল্লী',
        'Mumbai / মুম্বাই',
        'Kolkata / কলকাতা',
        'Chennai / চেন্নাই',
      ],
      correctAnswerIndex: 0,
      explanation: "New Delhi is the national capital of India, situated within the National Capital Territory of Delhi.\nনতুন দিল্লী ভাৰতৰ ৰাষ্ট্ৰীয় ৰাজধানী, যি দিল্লী ৰাষ্ট্ৰীয় ৰাজধানী অঞ্চলৰ ভিতৰত অৱস্থিত।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "Which is the longest river in India?\nভাৰতৰ আটাইতকৈ দীঘল নদী কোনখন?",
      options: [
        'Yamuna / যমুনা',
        'Ganga / গংগা',
        'Godavari / গোদাৱৰী',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Ganga, at about 2,525 km, is the longest river entirely within India.\nগংগা নদী প্ৰায় ২,৫২৫ কিঃমিঃ দৈৰ্ঘ্যৰ সৈতে ভাৰতৰ ভিতৰতে থকা আটাইতকৈ দীঘল নদী।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "The Constitution of India was adopted by the Constituent Assembly on —\nভাৰতৰ সংবিধান গণপৰিষদে কেতিয়া গ্ৰহণ কৰিছিল?",
      options: [
        '15 August 1947 / ১৫ আগষ্ট ১৯৪৭',
        '26 January 1950 / ২৬ জানুৱাৰী ১৯৫০',
        '26 November 1949 / ২৬ নৱেম্বৰ ১৯৪৯',
        '9 December 1946 / ৯ ডিচেম্বৰ ১৯৪৬',
      ],
      correctAnswerIndex: 2,
      explanation: "The Constituent Assembly adopted the Constitution of India on 26 November 1949; it came into effect on 26 January 1950.\nগণপৰিষদে ভাৰতৰ সংবিধান ২৬ নৱেম্বৰ ১৯৪৯ ত গ্ৰহণ কৰিছিল; ২৬ জানুৱাৰী ১৯৫০ ত ই কাৰ্যকৰ হৈছিল।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "Who was the first President of India?\nভাৰতৰ প্ৰথমগৰাকী ৰাষ্ট্ৰপতি কোন আছিল?",
      options: [
        'Dr. S. Radhakrishnan / ড॰ এছ॰ ৰাধাকৃষ্ণন',
        'Jawaharlal Nehru / জৱাহৰলাল নেহৰু',
        'V. V. Giri / ভি॰ ভি॰ গিৰি',
        'Dr. Rajendra Prasad / ড॰ ৰাজেন্দ্ৰ প্ৰসাদ',
      ],
      correctAnswerIndex: 3,
      explanation: "Dr. Rajendra Prasad was the first President of India, serving from 1950 to 1962.\nড॰ ৰাজেন্দ্ৰ প্ৰসাদ ভাৰতৰ প্ৰথমগৰাকী ৰাষ্ট্ৰপতি আছিল, যিয়ে ১৯৫০ ৰ পৰা ১৯৬২ লৈ কাৰ্যনিৰ্বাহ কৰিছিল।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "How many Fundamental Duties are enshrined in the Indian Constitution?\nভাৰতীয় সংবিধানত কিমানটা মৌলিক কৰ্তব্য সন্নিবিষ্ট আছে?",
      options: [
        '11 / ১১',
        '10 / ১০',
        '12 / ১২',
        '9 / ৯',
      ],
      correctAnswerIndex: 0,
      explanation: "Originally ten, the number of Fundamental Duties (Part IVA, Article 51A) became eleven after the 86th Amendment of 2002 added the duty regarding education of children.\nমূলতঃ দহটা মৌলিক কৰ্তব্য (Part IVA, Article 51A), ২০০২ চনৰ ৮৬তম সংশোধনীয়ে শিশুৰ শিক্ষা সম্পৰ্কীয় কৰ্তব্য যোগ কৰাৰ পিছত এঘাৰটা হয়।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "The Tropic of Cancer passes through how many Indian states?\nকৰ্কটক্ৰান্তি ৰেখা ভাৰতৰ কিমানখন ৰাজ্যৰ মাজেদি পাৰ হৈ যায়?",
      options: [
        '7 / ৭',
        '8 / ৮',
        '6 / ৬',
        '9 / ৯',
      ],
      correctAnswerIndex: 1,
      explanation: "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram.\nকৰ্কটক্ৰান্তি ৰেখা ভাৰতৰ ৮খন ৰাজ্যৰ মাজেদি পাৰ হয়: গুজৰাট, ৰাজস্থান, মধ্যপ্ৰদেশ, ছত্তীছগঢ়, ঝাৰখণ্ড, পশ্চিম বংগ, ত্ৰিপুৰা আৰু মিজোৰাম।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: "Which is widely regarded as the national sport of India?\nভাৰতৰ ৰাষ্ট্ৰীয় খেল হিচাপে কোনটো বহুলভাৱে গণ্য কৰা হয়?",
      options: [
        'Cricket / ক্ৰিকেট',
        'Football / ফুটবল',
        'Hockey / হকী',
        'Kabaddi / কাবাডি',
      ],
      correctAnswerIndex: 2,
      explanation: "Field hockey is widely regarded as India's national sport, with India winning eight Olympic gold medals.\nফিল্ড হকীক বহুলভাৱে ভাৰতৰ ৰাষ্ট্ৰীয় খেল হিচাপে গণ্য কৰা হয়, ভাৰতে আঠটা অলিম্পিক স্বৰ্ণ পদক জিকিছে।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    {
      question: 'Who is known as the "Iron Man of India"?\n"ভাৰতৰ লোহা পুৰুষ" হিচাপে কোনক জনা যায়?',
      options: [
        'Jawaharlal Nehru / জৱাহৰলাল নেহৰু',
        'Subhas Chandra Bose / সুভাষ চন্দ্ৰ বসু',
        'Mahatma Gandhi / মহাত্মা গান্ধী',
        'Sardar Vallabhbhai Patel / সৰদাৰ বল্লভভাই পটেল',
      ],
      correctAnswerIndex: 3,
      explanation: "Sardar Vallabhbhai Patel is called the Iron Man of India for unifying 562 princely states into the Indian Union.\nসৰদাৰ বল্লভভাই পটেলক ৫৬২টা দেশীয় ৰাজ্যক ভাৰতীয় সংঘত একত্ৰিত কৰাৰ বাবে ভাৰতৰ লোহা পুৰুষ বুলি কোৱা হয়।",
      subjectTopic: 'India GK',
      marks: 1,
    },
    // --- Current Affairs (2) ---
    {
      question: "Chandrayaan-3 made a historic soft landing on the Moon's south pole in which month and year?\nচন্দ্ৰযান-৩-এ কোনটো মাহ আৰু বছৰত চন্দ্ৰৰ দক্ষিণ মেৰুত ঐতিহাসিক কোমল অৱতৰণ কৰিছিল?",
      options: [
        'August 2023 / আগষ্ট ২০২৩',
        'July 2019 / জুলাই ২০১৯',
        'September 2022 / ছেপ্তেম্বৰ ২০২২',
        'October 2023 / অক্টোবৰ ২০২৩',
      ],
      correctAnswerIndex: 0,
      explanation: "Chandrayaan-3's Vikram lander soft-landed on the lunar south pole on 23 August 2023, making India the first country to do so.\nচন্দ্ৰযান-৩ৰ বিক্ৰম লেণ্ডাৰে ২৩ আগষ্ট ২০২৩ ত চন্দ্ৰৰ দক্ষিণ মেৰুত কোমল অৱতৰণ কৰিছিল, যাৰ ফলত ভাৰত প্ৰথম দেশ হিচাপে পৰিগণিত হয়।",
      subjectTopic: 'Current Affairs',
      marks: 1,
    },
    {
      question: "The G20 Summit 2023 was hosted by which city?\n২০২৩ চনৰ জি-২০ শৃংখলা সন্মিলন কোনখন চহৰে আয়োজন কৰিছিল?",
      options: [
        'Bali / বালি',
        'New Delhi / নতুন দিল্লী',
        'Osaka / অচাকা',
        'Riyadh / ৰিয়াদ',
      ],
      correctAnswerIndex: 1,
      explanation: "India hosted the G20 Summit on 9–10 September 2023 in New Delhi under the theme Vasudhaiva Kutumbakam.\nভাৰতে ৯–১০ ছেপ্তেম্বৰ ২০২৩ ত নতুন দিল্লীত বসুধৈৱ কুটুম্বকম বিষয়বস্তুৰ অধীনত জি-২০ শৃংখলা সন্মিলন আয়োজন কৰিছিল।",
      subjectTopic: 'Current Affairs',
      marks: 1,
    },
  ],

  // ===========================================================================
  // police-reasoning — Reasoning (30)
  // ===========================================================================
  'police-reasoning': [
    // --- Series (5) ---
    {
      question: "What comes next in the series 2, 4, 8, 16, ?\nশ্ৰেণীটোত পৰৱৰ্তী পদ কি: 2, 4, 8, 16, ?",
      options: [
        '32 / ৩২',
        '24 / ২৪',
        '30 / ৩০',
        '64 / ৬৪',
      ],
      correctAnswerIndex: 0,
      explanation: "Each term doubles the previous; 16 × 2 = 32.\nপ্ৰতিটো পদ আগৰ পদৰ দুগুণ; ১৬ × ২ = ৩২।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Find the next number: 1, 4, 9, 16, 25, ?\nপৰৱৰ্তী সংখ্যাটো উলিওৱা: 1, 4, 9, 16, 25, ?",
      options: [
        '49 / ৪৯',
        '36 / ৩৬',
        '30 / ৩০',
        '48 / ৪৮',
      ],
      correctAnswerIndex: 1,
      explanation: "These are perfect squares (1², 2², 3², 4², 5²), so the next is 6² = 36.\nএইবোৰ পূর্ণ বৰ্গ (১², ২², ৩², ৪², ৫²), গতিকে পৰৱৰ্তীটো ৬² = ৩৬।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Complete the series: 3, 6, 9, 12, ?\nশ্ৰেণীটো সম্পূৰ্ণ কৰা: 3, 6, 9, 12, ?",
      options: [
        '18 / ১৮',
        '21 / ২১',
        '15 / ১৫',
        '9 / ৯',
      ],
      correctAnswerIndex: 2,
      explanation: "This is an arithmetic progression with common difference 3; 12 + 3 = 15.\nএইটো সাধাৰণ পাৰ্থক্য ৩ ৰ এটা সমান্তৰ প্ৰগতি; ১২ + ৩ = ১৫।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "What comes next: 1, 1, 2, 6, 24, ?\nপৰৱৰ্তী পদ উলিওৱা: 1, 1, 2, 6, 24, ?",
      options: [
        '30 / ৩০',
        '36 / ৩৬',
        '60 / ৬০',
        '120 / ১২০',
      ],
      correctAnswerIndex: 3,
      explanation: "Each term is multiplied by 1, 2, 3, 4, 5 successively; 24 × 5 = 120 (factorial sequence).\nপ্ৰতিটো পদ ক্ৰমান্বয়ে ১, ২, ৩, ৪, ৫ ৰে পূৰণ কৰা হয়; ২৪ × ৫ = ১২০ (ক্ৰমগুণন শ্ৰেণী)।",
      subjectTopic: 'Series',
      marks: 1,
    },
    {
      question: "Find the next term: 5, 10, 20, 40, ?\nপৰৱৰ্তী পদ উলিওৱা: 5, 10, 20, 40, ?",
      options: [
        '80 / ৮০',
        '60 / ৬০',
        '100 / ১০০',
        '50 / ৫০',
      ],
      correctAnswerIndex: 0,
      explanation: "Each term doubles; 40 × 2 = 80.\nপ্ৰতিটো পদ দুগুণ হয়; ৪০ × ২ = ৮০।",
      subjectTopic: 'Series',
      marks: 1,
    },
    // --- Analogy (5) ---
    {
      question: "Dog : Puppy :: Cat : ?\nকুকুৰ : কুকুৰাৰ পোৱালি :: মেকুৰী : ?",
      options: [
        'Puppy / কুকুৰাৰ পোৱালি',
        'Kitten / মেকুৰীৰ পোৱালি',
        'Cub / বাঘৰ পোৱালি',
        'Calf / গৰুৰ পোৱালি',
      ],
      correctAnswerIndex: 1,
      explanation: "A puppy is the young one of a dog; the young one of a cat is a kitten.\nকুকুৰাৰ পোৱালিক puppy বোলে; মেকুৰীৰ পোৱালিক kitten বোলে।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Hand : Glove :: Foot : ?\nহাত : গ্লাভ :: ভৰি : ?",
      options: [
        'Shoe / জোতা',
        'Sandal / চেণ্ডেল',
        'Sock / মোজা',
        'Boot / বুট',
      ],
      correctAnswerIndex: 2,
      explanation: "A glove covers the hand; a sock covers the foot.\nগ্লাভে হাত ঢাকে; মোজাই ভৰি ঢাকে।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Doctor : Hospital :: Teacher : ?\nডাক্তৰ : চিকিৎসালয় :: শিক্ষক : ?",
      options: [
        'College / মহাবিদ্যালয়',
        'Office / কাৰ্যালয়',
        'Student / ছাত্ৰ',
        'School / বিদ্যালয়',
      ],
      correctAnswerIndex: 3,
      explanation: "A doctor works in a hospital; a teacher works in a school.\nডাক্তৰে চিকিৎসালয়ত কাম কৰে; শিক্ষকে বিদ্যালয়ত কাম কৰে।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Eye : Sight :: Ear : ?\nচকু : দৰ্শন :: কাণ : ?",
      options: [
        'Hearing / শ্ৰৱণ',
        'Smell / গন্ধ',
        'Sound / শব্দ',
        'Taste / স্বাদ',
      ],
      correctAnswerIndex: 0,
      explanation: "The eye is the organ of sight; the ear is the organ of hearing.\nচকু দৰ্শনৰ অংগ; কাণ শ্ৰৱণৰ অংগ।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    {
      question: "Pen : Write :: Knife : ?\nকলম : লিখা :: ছুৰি : ?",
      options: [
        'Sharp / জোঙা',
        'Cut / কটা',
        'Blade / ব্লেড',
        'Steel / তীখা',
      ],
      correctAnswerIndex: 1,
      explanation: "A pen is used to write; a knife is used to cut.\nকলমেৰে লিখা হয়; ছুৰিৰে কটা হয়।",
      subjectTopic: 'Analogy',
      marks: 1,
    },
    // --- Coding (5) ---
    {
      question: "If CAT is coded as 24 (3+1+20), then DOG = ?\nযদি CAT ক 24 (3+1+20) হিচাপে সংকেত কৰা হয়, তেন্তে DOG = ?",
      options: [
        '27 / ২৭',
        '24 / ২৪',
        '26 / ২৬',
        '22 / ২২',
      ],
      correctAnswerIndex: 2,
      explanation: "D = 4, O = 15, G = 7; 4 + 15 + 7 = 26.\nD = ৪, O = ১৫, G = ৭; ৪ + ১৫ + ৭ = ২৬।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "In a certain code, TABLE is written as UBCMF (each letter +1). How is CHAIR written?\nএটা সংকেতত TABLE ক UBCMF লিখা হয় (প্ৰতিটো আখৰ +1)। CHAIR ক কেনেকৈ লিখা হ'ব?",
      options: [
        'DBCJT / ডিবিচিজেটি',
        'DBHQU / ডিবিএইচকিউইউ',
        'EJCJT / ইজেচিজেটি',
        'DIBJS / ডিআইবিজেএছ',
      ],
      correctAnswerIndex: 3,
      explanation: "Each letter is shifted by +1: C→D, H→I, A→B, I→J, R→S, giving DIBJS.\nপ্ৰতিটো আখৰ +1 কৰি স্থানান্তৰ কৰা হয়: C→D, H→I, A→B, I→J, R→S, ফলত DIBJS।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "If A = 1, B = 2, C = 3, ..., then BAD = ?\nযদি A = 1, B = 2, C = 3, ..., তেন্তে BAD = ?",
      options: [
        '7 / ৭',
        '8 / ৮',
        '6 / ৬',
        '5 / ৫',
      ],
      correctAnswerIndex: 0,
      explanation: "B = 2, A = 1, D = 4; 2 + 1 + 4 = 7.\nB = ২, A = ১, D = ৪; ২ + ১ + ৪ = ৭।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "In a code RUN is written as WTO (each letter +3). How is CAT written?\nএটা সংকেতত RUN ক WTO লিখা হয় (প্ৰতিটো আখৰ +3)। CAT ক কেনেকৈ লিখা হ'ব?",
      options: [
        'DBV / ডিবিভি',
        'FDW / এফডিডাব্লিউ',
        'EDW / ইডাব্লিউ',
        'FBV / এফবিভি',
      ],
      correctAnswerIndex: 1,
      explanation: "Each letter is shifted +3: C→F, A→D, T→W, giving FDW.\nপ্ৰতিটো আখৰ +3 কৰি স্থানান্তৰ: C→F, A→D, T→W, ফলত FDW।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    {
      question: "If 'WATER' is coded as 'YCVGT' (each letter +2), how is FIRE coded?\nযদি 'WATER' ক 'YCVGT' সংকেত কৰা হয় (প্ৰতিটো আখৰ +2), তেন্তে FIRE ক কেনেকৈ সংকেত কৰা হ'ব?",
      options: [
        'GJQF / জিজেকিউএফ',
        'HKSF / এইচকেএছএফ',
        'HKTG / এইচকেটিজি',
        'GJTG / জিজেটিজি',
      ],
      correctAnswerIndex: 2,
      explanation: "Each letter is shifted +2: F→H, I→K, R→T, E→G, giving HKTG.\nপ্ৰতিটো আখৰ +2 কৰি স্থানান্তৰ: F→H, I→K, R→T, E→G, ফলত HKTG।",
      subjectTopic: 'Coding',
      marks: 1,
    },
    // --- Blood Relations (5) ---
    {
      question: "Pointing to a photograph, a man said, \"She is the daughter of my grandfather's only son.\" How is she related to him?\nএজন মানুহে এখন ফটোৰ ফালে আঙুলিয়াই ক'লে, \"তাই মোৰ ককাদেউতাকৰ একমাত্ৰ পুত্ৰৰ জীয়েক।\" তাই তেওঁৰ কি হয়?",
      options: [
        'Daughter / জীয়েক',
        'Cousin / ককাদেউতাকৰ জীয়েক বা খুড়াদেউতাকৰ জীয়েক',
        'Niece / ভানিজ বা ভতিজী',
        'Sister / ভগ্নী',
      ],
      correctAnswerIndex: 3,
      explanation: "Grandfather's only son is the man's father; the father's daughter is the man's sister.\nককাদেউতাকৰ একমাত্ৰ পুত্ৰ মানুহজনৰ দেউতাক; দেউতাকৰ জীয়েক মানুহজনৰ ভগ্নী।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "A is the brother of B. B is the sister of C. How is A related to C?\nA, Bৰ ভায়েক। B, Cৰ ভগ্নী। A, Cৰ লগত কেনেদৰে জড়িত?",
      options: [
        'Brother / ভায়েক',
        'Cousin / ককাদেউতাকৰ ল\'ৰা বা খুড়াদেউতাকৰ ল\'ৰা',
        'Uncle / ককাই বা খুড়া',
        'Father / দেউতাক',
      ],
      correctAnswerIndex: 0,
      explanation: "Since A and B are siblings, and B and C are siblings, all three share parents; A is C's brother.\nযিহেতু A আৰু B ভাই-ভনী, আৰু B আৰু C ভাই-ভনী, তিনিওৰে পিতৃ-মাতৃ একে; A, Cৰ ভায়েক।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "Introducing a woman, a man said, \"Her mother is the only daughter of my mother.\" How is the woman related to the man?\nএগৰাকী মহিলাক পৰিচয় কৰাই দি এজন মানুহে ক'লে, \"তাইৰ মাক মোৰ মাকৰ একমাত্ৰ জীয়েক।\" মহিলাগৰাকী মানুহজনৰ কি হয়?",
      options: [
        'Sister / ভগ্নী',
        'Daughter / জীয়েক',
        'Niece / ভানিজ',
        'Wife / পত্নী',
      ],
      correctAnswerIndex: 1,
      explanation: "The only daughter of my mother is the speaker himself (the man); so the woman's mother is the man — the woman is his daughter.\nমোৰ মাকৰ একমাত্ৰ জীয়েক হ'ল কথাষাৰ কোৱাজন মানুহ নিজেই; গতিকে মহিলাগৰাকীৰ মাক সেই মানুহজন — মহিলাগৰাকী তেওঁৰ জীয়েক।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "Raj is the father of Sita. Sita is the sister of Mohan. How is Mohan related to Raj?\nৰাজ সীতাৰ দেউতাক। সীতা মোহনৰ ভগ্নী। মোহন ৰাজৰ লগত কেনেদৰে জড়িত?",
      options: [
        'Nephew / ভতিজা',
        'Brother / ভায়েক',
        'Son / পুত্ৰ',
        'Cousin / ককাদেউতাকৰ ল\'ৰা বা খুড়াদেউতাকৰ ল\'ৰা',
      ],
      correctAnswerIndex: 2,
      explanation: "Since Sita and Mohan are siblings, and Raj is Sita's father, Raj is also Mohan's father; Mohan is Raj's son.\nযিহেতু সীতা আৰু মোহন ভাই-ভনী, আৰু ৰাজ সীতাৰ দেউতাক, ৰাজ মোহনৰো দেউতাক; মোহন ৰাজৰ পুত্ৰ।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    {
      question: "Priya's mother is the only daughter of Sunita's father. How is Sunita related to Priya?\nপ্ৰিয়াৰ মাক সুনীতাৰ দেউতাকৰ একমাত্ৰ জীয়েক। সুনীতা প্ৰিয়াৰ লগত কেনেদৰে জড়িত?",
      options: [
        'Aunt / খুড়ীয়েক বা ককাইমাক',
        'Sister / ভগ্নী',
        'Grandmother / আইতাই',
        'Mother / মাক',
      ],
      correctAnswerIndex: 3,
      explanation: "The only daughter of Sunita's father is Sunita herself; so Sunita is Priya's mother.\nসুনীতাৰ দেউতাকৰ একমাত্ৰ জীয়েক হ'ল সুনীতা নিজেই; গতিকে সুনীতা প্ৰিয়াৰ মাক।",
      subjectTopic: 'Blood Relations',
      marks: 1,
    },
    // --- Direction (5) ---
    {
      question: "A man walks 3 km north, then turns right and walks 4 km. How far is he from the starting point?\nএজন মানুহে ৩ কিঃমিঃ উত্তৰ দিশে খোজ কাঢ়ে, তাৰ পিছত সোঁফালে ঘুৰি ৪ কিঃমিঃ খোজ কাঢ়ে। আৰম্ভণিৰ স্থানৰ পৰা তেওঁ কিমান দূৰত?",
      options: [
        '5 km / ৫ কিঃমিঃ',
        '7 km / ৭ কিঃমিঃ',
        '4 km / ৪ কিঃমিঃ',
        '3 km / ৩ কিঃমিঃ',
      ],
      correctAnswerIndex: 0,
      explanation: "This forms a 3-4-5 right triangle; √(3² + 4²) = 5 km.\nএইটো এটা ৩-৪-৫ সমকোণী ত্ৰিভুজ গঠন কৰে; √(৩² + ৪²) = ৫ কিঃমিঃ।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "If South-East becomes North, then what does North become?\nযদি দক্ষিণ-পূব উত্তৰ হয়, তেন্তে উত্তৰ কি হ'ব?",
      options: [
        'North-West / উত্তৰ-পশ্চিম',
        'South-West / দক্ষিণ-পশ্চিম',
        'South-East / দক্ষিণ-পূব',
        'North-East / উত্তৰ-পূব',
      ],
      correctAnswerIndex: 1,
      explanation: "Each direction rotates 135° anti-clockwise; North (rotated 135° anti-clockwise) becomes South-West.\nপ্ৰতিটো দিশ ১৩৫° ঘড়িৰ বিপৰীত দিশত ঘূৰে; উত্তৰ (১৩৫° ঘড়িৰ বিপৰীত দিশত ঘূৰিলে) দক্ষিণ-পশ্চিম হয়।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "A person is facing north. He turns 90° clockwise, then turns 180°. Which direction is he now facing?\nএজন ব্যক্তি উত্তৰ দিশলৈ মুখ কৰি আছে। তেওঁ ঘড়িৰ দিশত ৯০° ঘূৰে, তাৰ পিছত ১৮০° ঘূৰে। তেওঁ এতিয়া কোন দিশলৈ মুখ কৰি আছে?",
      options: [
        'East / পূব',
        'South / দক্ষিণ',
        'West / পশ্চিম',
        'North / উত্তৰ',
      ],
      correctAnswerIndex: 2,
      explanation: "Facing north → 90° clockwise → east; then 180° → west.\nউত্তৰ → ৯০° ঘড়িৰ দিশত → পূব; তাৰ পিছত ১৮০° → পশ্চিম।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "Ramesh walks 4 km east, then turns left and walks 3 km. How far is he from the start?\nৰমেশে ৪ কিঃমিঃ পূবলৈ খোজ কাঢ়ে, তাৰ পিছত বাওঁফালে ঘুৰি ৩ কিঃমিঃ খোজ কাঢ়ে। আৰম্ভণিৰ পৰা তেওঁ কিমান দূৰত?",
      options: [
        '3 km / ৩ কিঃমিঃ',
        '4 km / ৪ কিঃমিঃ',
        '7 km / ৭ কিঃমিঃ',
        '5 km / ৫ কিঃমিঃ',
      ],
      correctAnswerIndex: 3,
      explanation: "3-4-5 right triangle; √(4² + 3²) = 5 km.\n৩-৪-৫ সমকোণী ত্ৰিভুজ; √(৪² + ৩²) = ৫ কিঃমিঃ।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    {
      question: "A man walks 2 km south, then turns west and walks 2 km. In which direction is he from the start?\nএজন মানুহে ২ কিঃমিঃ দক্ষিণে খোজ কাঢ়ে, তাৰ পিছত পশ্চিমলৈ ঘুৰি ২ কিঃমিঃ খোজ কাঢ়ে। আৰম্ভণিৰ পৰা তেওঁ কোন দিশত আছে?",
      options: [
        'South-West / দক্ষিণ-পশ্চিম',
        'South-East / দক্ষিণ-পূব',
        'North-West / উত্তৰ-পশ্চিম',
        'North-East / উত্তৰ-পূব',
      ],
      correctAnswerIndex: 0,
      explanation: "He is 2 km south and 2 km west of the start, placing him in the South-West quadrant.\nতেওঁ আৰম্ভণিৰ পৰা ২ কিঃমিঃ দক্ষিণে আৰু ২ কিঃমিঃ পশ্চিমে, অৰ্থাৎ দক্ষিণ-পশ্চিম চতুৰ্থাংশত আছে।",
      subjectTopic: 'Direction',
      marks: 1,
    },
    // --- Syllogism (5) ---
    {
      question: "Statements: All dogs are animals. All animals are living beings. Conclusions: I. All dogs are living beings. II. Some living beings are dogs.\nবক্তব্য: সকলো কুকুৰ জন্তু। সকলো জন্তু জীৱ। সিদ্ধান্ত: I. সকলো কুকুৰ জীৱ। II. কিছুমান জীৱ কুকুৰ।",
      options: [
        'Only I follows / কেৱল I অনুসৰণ কৰে',
        'Both I and II follow / I আৰু II দুয়োটাই অনুসৰণ কৰে',
        'Only II follows / কেৱল II অনুসৰণ কৰে',
        'Neither follows / কোনোটোৱেই অনুসৰণ নকৰে',
      ],
      correctAnswerIndex: 1,
      explanation: "Both conclusions follow by transitive syllogism: dogs ⊆ animals ⊆ living beings, so all dogs are living beings and some living beings are dogs.\nদুয়োটা সিদ্ধান্ত সঞ্চাৰী ন্যায়ৰ দ্বাৰা অনুসৰণ কৰে: কুকুৰ ⊆ জন্তু ⊆ জীৱ, গতিকে সকলো কুকুৰ জীৱ আৰু কিছুমান জীৱ কুকুৰ।",
      subjectTopic: 'Syllogism',
      marks: 1,
    },
    {
      question: "Statements: All men are mortal. Socrates is a man. Conclusion: Socrates is mortal.\nবক্তব্য: সকলো মানুহ মৰণশীল। ছক্ৰেটিছ এজন মানুহ। সিদ্ধান্ত: ছক্ৰেটিছ মৰণশীল।",
      options: [
        'Does not follow / অনুসৰণ নকৰে',
        'Cannot be determined / নিৰ্ধাৰণ কৰিব নোৱাৰি',
        'Follows / অনুসৰণ কৰে',
        'Partially follows / আংশিকভাৱে অনুসৰণ কৰে',
      ],
      correctAnswerIndex: 2,
      explanation: "This is the classic Barbara syllogism; the conclusion follows necessarily from the two premises.\nএইটো ক্লাছিক বাৰ্বাৰা ন্যায়; সিদ্ধান্তটো দুটা বক্তব্যৰ পৰা অনিবাৰ্যভাৱে অনুসৰণ কৰে।",
      subjectTopic: 'Syllogism',
      marks: 1,
    },
    {
      question: "Statements: Some pens are pencils. No pencil is an eraser. Conclusions: I. Some pens are not erasers. II. No pen is an eraser.\nবক্তব্য: কিছুমান কলম পেঞ্চিল। কোনো পেঞ্চিল ইৰেজাৰ নহয়। সিদ্ধান্ত: I. কিছুমান কলম ইৰেজাৰ নহয়। II. কোনো কলম ইৰেজাৰ নহয়।",
      options: [
        'Only II follows / কেৱল II অনুসৰণ কৰে',
        'Both follow / দুয়োটাই অনুসৰণ কৰে',
        'Neither follows / কোনোটোৱেই অনুসৰণ নকৰে',
        'Only I follows / কেৱল I অনুসৰণ কৰে',
      ],
      correctAnswerIndex: 3,
      explanation: "Pens that are pencils cannot be erasers, so 'some pens are not erasers' follows; but pens that are not pencils may be erasers, so II does not follow.\nযিবোৰ কলম পেঞ্চিল সেইবোৰ ইৰেজাৰ নহ'ব পাৰে, গতিকে 'কিছুমান কলম ইৰেজাৰ নহয়' অনুসৰণ কৰে; কিন্তু যিবোৰ কলম পেঞ্চিল নহয় সেইবোৰ ইৰেজাৰ হ'ব পাৰে, গতিকে II অনুসৰণ নকৰে।",
      subjectTopic: 'Syllogism',
      marks: 1,
    },
    {
      question: "Statements: All doctors are graduates. Some graduates are women. Conclusion: Some doctors are women.\nবক্তব্য: সকলো ডাক্তৰ স্নাতক। কিছুমান স্নাতক মহিলা। সিদ্ধান্ত: কিছুমান ডাক্তৰ মহিলা।",
      options: [
        'Does not follow / অনুসৰণ নকৰে',
        'Follows / অনুসৰণ কৰে',
        'Probably follows / সম্ভৱতঃ অনুসৰণ কৰে',
        'Cannot be determined / নিৰ্ধাৰণ কৰিব নোৱাৰি',
      ],
      correctAnswerIndex: 0,
      explanation: "The women graduates need not be doctors; the middle term 'graduates' is not distributed, so the conclusion does not necessarily follow.\nমহিলা স্নাতকসকল ডাক্তৰ হ'বই লাগিব নোৱাৰে; মধ্য পদ 'স্নাতক' বিতৰিত নহয়, গতিকে সিদ্ধান্তটো অনিবাৰ্যভাৱে অনুসৰণ নকৰে।",
      subjectTopic: 'Syllogism',
      marks: 1,
    },
    {
      question: "Statements: No apple is mango. No mango is banana. Conclusions: I. No apple is banana. II. Some apples are bananas.\nবক্তব্য: কোনো আপেল আম নহয়। কোনো আম কল নহয়। সিদ্ধান্ত: I. কোনো আপেল কল নহয়। II. কিছুমান আপেল কল।",
      options: [
        'Only I follows / কেৱল I অনুসৰণ কৰে',
        'Neither I nor II follows / I বা II কোনোটোৱেই অনুসৰণ নকৰে',
        'Both follow / দুয়োটাই অনুসৰণ কৰে',
        'Only II follows / কেৱল II অনুসৰণ কৰে',
      ],
      correctAnswerIndex: 1,
      explanation: "Two negative premises about apple-mango and mango-banana do not determine the apple-banana relationship; neither conclusion necessarily follows.\nআপেল-আম আৰু আম-কল সম্পৰ্কে দুটা নেতিবাচক বক্তব্যই আপেল-কল সম্পৰ্ক নিৰ্ধাৰণ নকৰে; কোনোটো সিদ্ধান্তই অনিবাৰ্যভাৱে অনুসৰণ নকৰে।",
      subjectTopic: 'Syllogism',
      marks: 1,
    },
  ],
};
