import type { QuestionPoolMap } from './structure';

// ADRE — Assam General Knowledge (অসমীয়া সাধাৰণ জ্ঞান)
// Heavily Assam-focused, class IX-X level. All fields bilingual EN + অসমীয়া.
export const ADRE_POOLS_GK: QuestionPoolMap = {
  'adre-gk': [
    {
      question: 'What is the capital of Assam?\nঅসমৰ ৰাজধানী কি?',
      options: ['Dispur / দিছপুৰ', 'Guwahati / গুৱাহাটী', 'Jorhat / যোৰহাট', 'Dibrugarh / ডিব্ৰুগড়'],
      correctAnswerIndex: 0,
      explanation: 'Dispur, a locality of Guwahati, is the capital of Assam.\nগুৱাহাটীৰ এটা অঞ্চল দিছপুৰ অসমৰ ৰাজধানী।',
      subjectTopic: 'Assam Districts',
      marks: 1,
    },
    {
      question: 'Which is the state animal of Assam?\nঅসমৰ ৰাজ্যিক পশু কোনটো?',
      options: ['Tiger / বাঘ', 'One-horned rhinoceros / এশিয়াগঁয়ে গণ্ডা', 'Elephant / হাতী', 'Asiatic lion / এশিয়াৰ সিংহ'],
      correctAnswerIndex: 1,
      explanation: 'The one-horned rhinoceros is the state animal of Assam.\nএশিয়াগঁয়ে গণ্ডা অসমৰ ৰাজ্যিক পশু।',
      subjectTopic: 'State Symbols',
      marks: 1,
    },
    {
      question: 'What is the state bird of Assam?\nঅসমৰ ৰাজ্যিক চৰাই কোনটো?',
      options: ['Peacock / ময়ূৰ', 'White-winged wood duck (Deo Hans) / দেও হাঁহ', 'Parrot / ভাটৌ', 'Eagle / ঈগল'],
      correctAnswerIndex: 1,
      explanation: 'The white-winged wood duck, locally called Deo Hans, is the state bird of Assam.\nদেও হাঁহ নামেৰে জনাজাত বগা-ডেউকাৰ হাঁহ অসমৰ ৰাজ্যিক চৰাই।',
      subjectTopic: 'State Symbols',
      marks: 1,
    },
    {
      question: 'Which is the state flower of Assam?\nঅসমৰ ৰাজ্যিক ফুল কোনটো?',
      options: ['Lotus /পদুম', 'Rose / গোলাপ', 'Foxtail orchid (Kopou Phool) / কপৌ ফুল', 'Marigold / গাঁদা ফুল'],
      correctAnswerIndex: 2,
      explanation: 'The foxtail orchid, known as Kopou Phool, is the state flower of Assam.\nকপৌ ফুল নামেৰে জনাজাক অৰ্কিড অসমৰ ৰাজ্যিক ফুল।',
      subjectTopic: 'State Symbols',
      marks: 1,
    },
    {
      question: 'What is the state tree of Assam?\nঅসমৰ ৰাজ্যিক গছ কোনটো?',
      options: ['Hollong / হলং', 'Banyan / বট', 'Neem / নিম', 'Teak / চেগুন'],
      correctAnswerIndex: 0,
      explanation: 'Hollong is the state tree of Assam.\nহলং অসমৰ ৰাজ্যিক গছ।',
      subjectTopic: 'State Symbols',
      marks: 1,
    },
    {
      question: 'Which is the main river of Assam?\nঅসমৰ মুখ্য নদী কোনখন?',
      options: ['Ganga / গঙ্গা', 'Yamuna / যমুনা', 'Brahmaputra / ব্ৰহ্মপুত্ৰ', 'Godavari / গোদাৱৰী'],
      correctAnswerIndex: 2,
      explanation: 'The Brahmaputra is the main river flowing through Assam.\nব্ৰহ্মপুত্ৰ অসমেদি বৈ যোৱা মুখ্য নদী।',
      subjectTopic: 'Rivers',
      marks: 1,
    },
    {
      question: 'Which is the largest river island in the world, located in Assam?\nঅসমত অৱস্থিত বিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপটো কোনটো?',
      options: ['Majuli / মাজুলী', 'Umananda / উমানন্দ', 'Pabho / পাভ', 'Sualkuchi / শুৱালকুছি'],
      correctAnswerIndex: 0,
      explanation: 'Majuli, in the Brahmaputra, is the largest river island in the world.\nব্ৰহ্মপুত্ৰত থকা মাজুলী বিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপ।',
      subjectTopic: 'Rivers',
      marks: 1,
    },
    {
      question: 'Kaziranga National Park is famous for which animal?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান কোনটো পশুৰ বাবে বিখ্যাত?',
      options: ['Tiger / বাঘ', 'One-horned rhinoceros / এশিয়াগঁয়ে গণ্ডা', 'Lion / সিংহ', 'Snow leopard / হিমায়ুৰ'],
      correctAnswerIndex: 1,
      explanation: 'Kaziranga is famous for the one-horned rhinoceros.\nকাজিৰঙা এশিয়াগঁয়ে গণ্ডাৰ বাবে বিখ্যাত।',
      subjectTopic: 'National Parks',
      marks: 1,
    },
    {
      question: 'In which year was Kaziranga National Park declared a UNESCO World Heritage Site?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান কোন বছৰত ইউনেস্কো বিশ্ব ঐতিহ্য স্থল হিচাপে স্বীকৃতি পায়?',
      options: ['1980 / ১৯৮০', '1985 / ১৯৮৫', '1990 / ১৯৯০', '1995 / ১৯৯৫'],
      correctAnswerIndex: 1,
      explanation: 'Kaziranga was declared a UNESCO World Heritage Site in 1985.\n১৯৮৫ চনত কাজিৰঙাই ইউনেস্কো বিশ্ব ঐতিহ্য স্থলৰ স্বীকৃতি পায়।',
      subjectTopic: 'National Parks',
      marks: 1,
    },
    {
      question: 'Where was the first oil well drilled in Asia?\nএছিয়াত প্ৰথম তেলৰ খোৱা ক’ত খন্দা হৈছিল?',
      options: ['Digboi / ডিগবৈ', 'Nazira / নাজিৰা', 'Duliajan / ডুলিয়াজান', 'Bongaigaon / বঙাইগাঁও'],
      correctAnswerIndex: 0,
      explanation: 'The first oil well in Asia was drilled at Digboi, Assam in 1889.\n১৮৮৯ চনত অসমৰ ডিগবৈত এছিয়াৰ প্ৰথম তেলৰ খোৱা খন্দা হৈছিল।',
      subjectTopic: 'Economy',
      marks: 1,
    },
    {
      question: 'What is the length of the Bogibeel Bridge?\nবগীবিল দলংৰ দৈৰ্ঘ্য কিমান?',
      options: ['4.94 km / ৪.৯৪ কিমি', '5.94 km / ৫.৯৪ কিমি', '3.94 km / ৩.৯৪ কিমি', '2.94 km / ২.৯৪ কিমি'],
      correctAnswerIndex: 0,
      explanation: 'The Bogibeel Bridge is 4.94 km long — India\'s longest rail-cum-road bridge.\nবগীবিল দলং ৪.৯৪ কিমি দীঘল — ভাৰতৰ আটাইতকৈ দীঘল ৰে’ল-পথ দলং।',
      subjectTopic: 'Economy',
      marks: 1,
    },
    {
      question: 'In which year was the Saraighat Bridge, the first across the Brahmaputra, opened?\nব্ৰহ্মপুত্ৰৰ ওপৰেৰে প্ৰথম দলং শৰাইঘাট দলং কোন বছৰত মুকলি কৰা হয়?',
      options: ['1952 / ১৯৫২', '1962 / ১৯৬২', '1972 / ১৯৭২', '1982 / ১৯৮২'],
      correctAnswerIndex: 1,
      explanation: 'The Saraighat Bridge was opened in 1962 — the first bridge across the Brahmaputra.\n১৯৬২ চনত শৰাইঘাট দলং মুকলি কৰা হয় — ব্ৰহ্মপুত্ৰৰ ওপৰেৰে প্ৰথম দলং।',
      subjectTopic: 'Economy',
      marks: 1,
    },
    {
      question: 'In which year did the Battle of Saraighat take place?\nশৰাইঘাটৰ যুদ্ধ কোন বছৰত সংঘটিত হৈছিল?',
      options: ['1661 / ১৬৬১', '1671 / ১৬৭১', '1681 / ১৬৮১', '1691 / ১৬৯১'],
      correctAnswerIndex: 1,
      explanation: 'The Battle of Saraighat was fought in 1671 on the Brahmaputra.\n১৬৭১ চনত ব্ৰহ্মপুত্ৰত শৰাইঘাটৰ যুদ্ধ হৈছিল।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Who led the Ahom army to victory in the Battle of Saraighat?\nশৰাইঘাটৰ যুদ্ধত আহোম সেনাক বিজয় লাভ কৰোৱা সেনাপতি কোন আছিল?',
      options: ['Lachit Borphukan / লচিত বৰফুকন', 'Chao Pha / চাওফা', 'Momai Tamuli / মোমাই তামুলী', 'Badan Barphukan / বদন বৰফুকন'],
      correctAnswerIndex: 0,
      explanation: 'Lachit Borphukan led the Ahoms to victory over the Mughals in 1671.\n১৬৭১ চনত লচিত বৰফুকনে আহোমক মোগলৰ ওপৰত বিজয় লাভ কৰায়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'The Treaty of Yandabo (1826) was signed between the British and which country?\nইয়াণ্ডাবু সন্ধি (১৮২৬) ব্ৰিটিছ আৰু কোন দেশৰ মাজত স্বাক্ষৰিত হৈছিল?',
      options: ['Burmese / বাৰ্মা', 'French / ফ্ৰান্স', 'Dutch / ডাচ', 'Portuguese / পৰ্তুগীজ'],
      correctAnswerIndex: 0,
      explanation: 'The Treaty of Yandabo (1826) ended the First Anglo-Burmese War and brought Assam under British control.\nইয়াণ্ডাবু সন্ধি (১৮২৬) প্ৰথম ইংৰাজ-বাৰ্মা যুদ্ধৰ অন্ত পেলাই অসমক ব্ৰিটিছৰ অধীনলৈ আনে।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Who was the first Chief Minister of Assam?\nঅসমৰ প্ৰথম মুখ্যমন্ত্ৰী কোন আছিল?',
      options: ['Gopinath Bordoloi / গোপীনাথ বৰদলৈ', 'Bishnuram Medhi / বিষ্ণুৰাম মেধি', 'Sarat Chandra Sinha / শৰৎ চন্দ্ৰ সিংহ', 'Hiteswar Saikia / হিতেশ্বৰ শইকীয়া'],
      correctAnswerIndex: 0,
      explanation: 'Gopinath Bordoloi was the first Chief Minister of Assam; he was awarded the Bharat Ratna.\nগোপীনাথ বৰদলৈ অসমৰ প্ৰথম মুখ্যমন্ত্ৰী আছিল; তেওঁক ভাৰত ৰত্ন বঁটা প্ৰদান কৰা হয়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Which Assamese personality was honoured with the Bharat Ratna in 2019?\n২০১৯ চনত কোনজন অসমীয়া ব্যক্তিক ভাৰত ৰত্ন বঁটা প্ৰদান কৰা হয়?',
      options: ['Bhupen Hazarika / ভূপেন হাজৰিকা', 'Jyoti Prasad Agarwala / জ্যোতিপ্ৰসাদ আগৰৱালা', 'Bishnu Prasad Rabha / বিষ্ণুপ্ৰসাদ ৰাভা', 'Mamoni Raisom Goswami / মামণি ৰয়ছম গোস্বামী'],
      correctAnswerIndex: 0,
      explanation: 'Dr Bhupen Hazarika, the legendary musician, was awarded the Bharat Ratna in 2019.\nকিংবদন্তী সংগীতজ্ঞ ড° ভূপেন হাজৰিকাক ২০১৯ চনত ভাৰত ৰত্ন বঁটা দিয়া হয়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'By what title is Jyoti Prasad Agarwala fondly known?\nজ্যোতিপ্ৰসাদ আগৰৱালাক কি উপাধিৰে জনা যায়?',
      options: ['Rupkonwar / ৰূপকোঁৱৰ', 'Kalaguru / কলাগুৰু', 'Sahityarathi / সাহিত্যৰথী', 'Asom Kesari / অসম কেশৰী'],
      correctAnswerIndex: 0,
      explanation: 'Jyoti Prasad Agarwala is fondly called Rupkonwar (prince of beauty).\nজ্যোতিপ্ৰসাদ আগৰৱালাক ৰূপকোঁৱৰ বুলি জনা যায়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Which was the first Assamese film, released in 1935?\n১৯৩৫ চনত মুক্তি পোৱা প্ৰথম অসমীয়া চলচ্চিত্ৰ কোনখন?',
      options: ['Joymoti / জয়মতী', 'Piyoli Phukan / পিয়লি ফুকন', 'Indramalati / ইন্দ্ৰমালতী', 'Siraj / চিৰাজ'],
      correctAnswerIndex: 0,
      explanation: 'Joymoti (1935), directed by Jyoti Prasad Agarwala, was the first Assamese film.\nজ্যোতিপ্ৰসাদ আগৰৱালা পৰিচালিত জয়মতী (১৯৩৫) প্ৰথম অসমীয়া চলচ্চিত্ৰ।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'By what title is Bishnu Prasad Rabha popularly known?\nবিষ্ণুপ্ৰসাদ ৰাভাক কি উপাধিৰে জনা যায়?',
      options: ['Kalaguru / কলাগুৰু', 'Rupkonwar / ৰূপকোঁৱৰ', 'Sahityarathi / সাহিত্যৰথী', 'Geetashree / গীতশ্ৰী'],
      correctAnswerIndex: 0,
      explanation: 'Bishnu Prasad Rabha is popularly known as Kalaguru (master of arts).\nবিষ্ণুপ্ৰসাদ ৰাভাক কলাগুৰু বুলি জনা যায়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Who is known as the "Sahityarathi" (Charioteer of Literature) of Assam?\nঅসমৰ "সাহিত্যৰথী" বুলি কাক জনা যায়?',
      options: ['Lakshminath Bezbaruah / লক্ষ্মীনাথ বেজবৰুয়া', 'Hemchandra Barua / হেমচন্দ্ৰ বৰুয়া', 'Ananda Chandra Agarwala / আনন্দ চন্দ্ৰ আগৰৱালা', 'Chandra Kumar Agarwala / চন্দ্ৰকুমাৰ আগৰৱালা'],
      correctAnswerIndex: 0,
      explanation: 'Lakshminath Bezbaruah is honoured as the Sahityarathi of Assamese literature.\nলক্ষ্মীনাথ বেজবৰুয়াক অসমীয়া সাহিত্যৰ সাহিত্যৰথী বুলি সন্মান কৰা হয়।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'As of 2023, how many districts are there in Assam?\n২০২৩ চনৰ তথ্য অনুসৰি অসমত মুঠ কিমানখন জিলা আছে?',
      options: ['31 / ৩১', '33 / ৩৩', '35 / ৩৫', '37 / ৩৭'],
      correctAnswerIndex: 2,
      explanation: 'As of 2023, Assam has 35 districts.\n২০২৩ চনৰ তথ্য অনুসৰি অসমত ৩৫খন জিলা আছে।',
      subjectTopic: 'Assam Districts',
      marks: 1,
    },
    {
      question: 'How many types of Bihu are celebrated in Assam?\nঅসমত কিমান প্ৰকাৰৰ বিহু পালন কৰা হয়?',
      options: ['Two / দুই', 'Three / তিনি', 'Four / চাৰি', 'Five / পাঁচ'],
      correctAnswerIndex: 1,
      explanation: "Three Bihus are celebrated: Rongali (Bohag), Kongali (Kati), and Bhogali (Magh).\nতিনি প্ৰকাৰৰ বিহু পালন কৰা হয়: ৰঙালী (ব'হাগ), কঙালী (কাতি) আৰু ভোগালী (মাঘ)।",
      subjectTopic: 'Festivals',
      marks: 1,
    },
    {
      question: 'In which Assamese month is Rongali Bihu celebrated?\nৰঙালী বিহু কোন অসমীয়া মাহত উদযাপন কৰা হয়?',
      options: ['Bohag / ব\'হাগ', 'Kati / কাতি', 'Magh / মাঘ', 'Jaistha / জেঠ'],
      correctAnswerIndex: 0,
      explanation: 'Rongali Bihu is celebrated in the month of Bohag (mid-April).\nব\'হাগ মাহত (এপ্ৰিল মাজভাগ) ৰঙালী বিহু উদযাপন কৰা হয়।',
      subjectTopic: 'Festivals',
      marks: 1,
    },
    {
      question: 'Which silk variety is unique to Assam?\nকোনবিধ ৰেচম অসমৰ বিশেষত্ব?',
      options: ['Mulberry silk / মূলবেৰী ৰেচম', 'Muga silk / মুগা ৰেচম', 'Tussar silk / টুচাৰ ৰেচম', 'Eri silk / এৰি ৰেচম'],
      correctAnswerIndex: 1,
      explanation: 'Muga silk, a golden-yellow silk, is unique to Assam and has a GI tag.\nসোণোৱালী-হালধীয়া ৰঙৰ মুগা ৰেচম অসমৰ বিশেষত্ব আৰু ইয়াৰ জি আই টেগ আছে।',
      subjectTopic: 'Economy',
      marks: 1,
    },
    {
      question: 'Pobitora Wildlife Sanctuary is known for having the highest density of which animal?\nপবিতৰা অভয়াৰণ্য কোনটো পশুৰ সৰ্বোচ্চ ঘনত্বৰ বাবে জনাজাত?',
      options: ['Tiger / বাঘ', 'One-horned rhinoceros / এশিয়াগঁয়ে গণ্ডা', 'Wild buffalo / বনৰীয়া ম’হ', 'Asiatic elephant / এশিয়াৰ হাতী'],
      correctAnswerIndex: 1,
      explanation: 'Pobitora has the highest density of one-horned rhinoceros in the world.\nপবিতৰাত বিশ্বৰ ভিতৰতে এশিয়াগঁয়ে গণ্ডাৰ সৰ্বোচ্চ ঘনত্ব আছে।',
      subjectTopic: 'National Parks',
      marks: 1,
    },
    {
      question: 'On the bank of which river is Guwahati situated?\nগুৱাহাটী নগৰ কোনখন নদীৰ পাৰত অৱস্থিত?',
      options: ['Barak / বৰাক', 'Brahmaputra / ব্ৰহ্মপুত্ৰ', 'Subansiri / সুৱনশিৰি', 'Manas / মানস'],
      correctAnswerIndex: 1,
      explanation: 'Guwahati is situated on the south bank of the Brahmaputra.\nগুৱাহাটী ব্ৰহ্মপুত্ৰ নদীৰ দক্ষিণ পাৰত অৱস্থিত।',
      subjectTopic: 'Rivers',
      marks: 1,
    },
    {
      question: 'In ancient times, Assam was known by which name?\nপ্ৰাচীন কালত অসম কি নামেৰে জনাজাত আছিল?',
      options: ['Magadha / মগধ', 'Kamarupa (Pragjyotisha) / কামৰূপ (প্ৰগজ্যোতিষ)', 'Anga / অংগ', 'Vanga / বংগ'],
      correctAnswerIndex: 1,
      explanation: 'In ancient times Assam was known as Pragjyotisha and later Kamarupa.\nপ্ৰাচীন কালত অসম প্ৰগজ্যোতিষ আৰু পিছত কামৰূপ নামেৰে জনাজাত আছিল।',
      subjectTopic: 'Assam Districts',
      marks: 1,
    },
    {
      question: 'Who founded the Ahom kingdom in 1228?\n১২২৮ চনত আহোম ৰাজ্য কোনে প্ৰতিষ্ঠা কৰিছিল?',
      options: ['Sukapha / চুকাফা', 'Suhungmung / চুহুংমুং', 'Pramatta Singha / প্ৰমত্ত সিংহ', 'Rudra Singha / ৰুদ্ৰ সিংহ'],
      correctAnswerIndex: 0,
      explanation: 'Chaolung Sukapha founded the Ahom kingdom in 1228.\nচাওলুং চুকাফাই ১২২৮ চনত আহোম ৰাজ্য প্ৰতিষ্ঠা কৰিছিল।',
      subjectTopic: 'Personalities',
      marks: 1,
    },
    {
      question: 'Which wildlife sanctuary / national park in Assam is also a UNESCO World Heritage Site along with Kaziranga?\nকাজিৰঙাৰ লগত অসমৰ কোনটো অভয়াৰণ্য/ৰাষ্ট্ৰীয় উদ্যানো ইউনেস্কো বিশ্ব ঐতিহ্য স্থল?',
      options: ['Manas National Park / মানস ৰাষ্ট্ৰীয় উদ্যান', 'Nameri National Park / নামেৰি ৰাষ্ট্ৰীয় উদ্যান', 'Orang National Park / ওৰাং ৰাষ্ট্ৰীয় উদ্যান', 'Dibru-Saikhowa National Park / ডিব্ৰু-চৈকোৱা ৰাষ্ট্ৰীয় উদ্যান'],
      correctAnswerIndex: 0,
      explanation: 'Manas National Park, a tiger reserve, is also a UNESCO World Heritage Site.\nমানস ৰাষ্ট্ৰীয় উদ্যান, এখন বাঘ সংৰক্ষিত এলেকা, ইউনেস্কো বিশ্ব ঐতিহ্য স্থল।',
      subjectTopic: 'National Parks',
      marks: 1,
    },
  ],
};
