// =============================================================================
// ExamVault — APSC (Assam Public Service Commission) PART A
// Bilingual question pool — General Studies (apsc-gs) + History (apsc-history)
//
// Format (CRITICAL — every field is bilingual EN + অসমীয়া):
//   question  -> "English\nঅসমীয়া"
//   option    -> "English / অসমীয়া"
//   expl      -> "English\nঅসমীয়া"
//
// apsc-gs       : 40 questions (History, Geography, Polity, Economy,
//                                Science, Current Affairs, Assam GK)
// apsc-history  : 40 questions (Ancient India, Medieval India, Modern India,
//                                Assam History, Freedom Movement)
// Total = 80 bilingual items.
//
// correctAnswerIndex is distributed evenly (10 × 0, 10 × 1, 10 × 2, 10 × 3)
// within each subject so test slicing produces a balanced answer key.
// =============================================================================
import type { QuestionPoolMap } from './structure';

export const APSC_POOLS_A: QuestionPoolMap = {
  // ===========================================================================
  // apsc-gs — General Studies (40)
  // ===========================================================================
  'apsc-gs': [
    // --- History (6) ---
    {
      question: "Who was the founder of the Mauryan Empire?\nমৌৰ্য সাম্ৰাজ্যৰ প্ৰতিষ্ঠাপক কোন আছিল?",
      options: [
        'Chandragupta Maurya / চন্দ্ৰগুপ্ত মৌৰ্য',
        'Ashoka / অশোক',
        'Bindusara / বিন্দুসাৰ',
        'Chanakya / চাণক্য',
      ],
      correctAnswerIndex: 0,
      explanation: "Chandragupta Maurya founded the Mauryan Empire around 322 BCE with the guidance of Chanakya (Kautilya).\nখ্ৰীষ্টপূৰ্ব ৩২২ৰ আশে-পাশে চন্দ্ৰগুপ্ত মৌৰ্যই চাণক্য (কৌটিল্য)ৰ পৰামৰ্শৰে মৌৰ্য সাম্ৰাজ্য প্ৰতিষ্ঠা কৰিছিল।",
      subjectTopic: 'History',
      marks: 2,
    },
    {
      question: "The Battle of Plassey was fought in which year?\nপলাশীৰ যুদ্ধ কতবাৰত সংঘটিত হৈছিল?",
      options: [
        '1756 / ১৭৫৬',
        '1757 / ১৭৫৭',
        '1761 / ১৭৬১',
        '1764 / ১৭৬৪',
      ],
      correctAnswerIndex: 1,
      explanation: "The Battle of Plassey was fought on 23 June 1757 between the British East India Company under Robert Clive and Siraj-ud-Daulah, the Nawab of Bengal.\nপলাশীৰ যুদ্ধ ২৩ জুন ১৭৫৭ত ৰবাৰ্ট ক্লাইভৰ নেতৃত্বাধীন ব্ৰিটিছ ইষ্ট ইণ্ডিয়া কোম্পানী আৰু বংগৰ নবাব ছিৰাজ-উদ-দৌলাৰ মাজত সংঘটিত হৈছিল।",
      subjectTopic: 'History',
      marks: 2,
    },
    {
      question: "The construction of the Qutub Minar was begun by which ruler?\nকুতুব মিনাৰৰ নিৰ্মাণ কোনজন ৰজাই আৰম্ভ কৰিছিল?",
      options: [
        'Akbar / আকবৰ',
        'Shah Jahan / শাহজাহান',
        'Qutb-ud-din Aibak / কুতুব-উদ-দিন আইবক',
        'Alauddin Khalji / আলাউদ্দিন খলজী',
      ],
      correctAnswerIndex: 2,
      explanation: "Construction of the Qutub Minar was begun by Qutb-ud-din Aibak in 1199 and completed by Iltutmish; later Firoz Shah Tughlaq repaired its top storeys.\nকুতুব মিনাৰৰ নিৰ্মাণ ১১৯৯ত কুতুব-উদ-দিন আইবকে আৰম্ভ কৰিছিল আৰু ইলতুতমিছে সম্পূৰ্ণ কৰিছিল; পিছত ফিৰোজ শাহ তুগলকে ওপৰৰ তলাবোৰ মেৰামতি কৰিছিল।",
      subjectTopic: 'History',
      marks: 2,
    },
    {
      question: "The Quit India Movement was launched in which year?\nভাৰত ত্যাগ আন্দোলন কতবাৰত আৰম্ভ কৰা হৈছিল?",
      options: [
        '1930 / ১৯৩০',
        '1935 / ১৯৩৫',
        '1940 / ১৯৪০',
        '1942 / ১৯৪২',
      ],
      correctAnswerIndex: 3,
      explanation: "The Quit India Movement was launched by Mahatma Gandhi on 8 August 1942 at the Bombay session of the All-India Congress Committee, demanding an end to British rule.\nভাৰত ত্যাগ আন্দোলন মহাত্মা গান্ধীয়ে ৮ আগষ্ট ১৯৪২ত বোম্বাই অধিবেশনত আৰম্ভ কৰিছিল, ব্ৰিটিছ শাসনৰ অন্ত দাবি কৰি।",
      subjectTopic: 'History',
      marks: 2,
    },
    {
      question: "Who was the first Mughal emperor of India?\nভাৰতৰ প্ৰথম মোগল সম্ৰাট কোন আছিল?",
      options: [
        'Babur / বাবৰ',
        'Humayun / হুমায়ুন',
        'Akbar / আকবৰ',
        'Jahangir / জাহাংগীৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "Babur became the first Mughal emperor of India after defeating Ibrahim Lodi at the First Battle of Panipat in 1526.\nবাবৰে ১৫২৬ত পানিপথৰ প্ৰথম যুদ্ধত ইব্ৰাহিম লোদীক পৰাস্ত কৰি ভাৰতৰ প্ৰথম মোগল সম্ৰাট হৈছিল।",
      subjectTopic: 'History',
      marks: 2,
    },
    {
      question: "The Indus Valley Civilization site of Lothal is located in which Indian state?\nসিন্ধু উপত্যকা সভ্যতাৰ লোথাল স্থানটো ভাৰতৰ কোন ৰাজ্যত অৱস্থিত?",
      options: [
        'Punjab / পঞ্জাৱ',
        'Gujarat / গুজৰাট',
        'Rajasthan / ৰাজস্থান',
        'Haryana / হৰিয়ানা',
      ],
      correctAnswerIndex: 1,
      explanation: "Lothal, a dockyard site of the Indus Valley Civilization, is located in the Bhal region of Gujarat, on the Sabarmati river.\nসিন্ধু উপত্যকা সভ্যতাৰ নৌ-বন্দৰ লোথাল গুজৰাটৰ ভল অঞ্চলত, সবৰমতী নদীৰ পাৰত অৱস্থিত।",
      subjectTopic: 'History',
      marks: 2,
    },
    // --- Geography (6) ---
    {
      question: "Which is the longest river in India?\nভাৰতৰ দীঘলীয়া নদী কোনখন?",
      options: [
        'Yamuna / যমুনা',
        'Godavari / গোদাৱৰী',
        'Ganga / গংগা',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 2,
      explanation: "The Ganga is the longest river entirely within India, about 2,525 km long, originating from Gangotri Glacier in Uttarakhand.\nগংগা নদী সম্পূৰ্ণৰূপে ভাৰতৰ ভিতৰতে থকা দীঘলীয়া নদী, প্ৰায় ২,৫২৫ কিঃমিঃ দীঘল, উত্তৰাখণ্ডৰ গংগোত্ৰী হিমানদৰ পৰা উৎপন্ন।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    {
      question: "Through how many Indian states does the Tropic of Cancer pass?\nকৰ্কটক্ৰান্তি ৰেখাই কিমানখন ভাৰতীয় ৰাজ্যৰ মাজেদি পাৰ হয়?",
      options: [
        '6 / ৬',
        '7 / ৭',
        '8 / ৮',
        '9 / ৯',
      ],
      correctAnswerIndex: 2,
      explanation: "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram.\nকৰ্কটক্ৰান্তি ৰেখাই ৮টা ভাৰতীয় ৰাজ্যৰ মাজেদি পাৰ হয়: গুজৰাট, ৰাজস্থান, মধ্যপ্ৰদেশ, ছত্তীছগঢ়, ঝাৰখণ্ড, পশ্চিমবংগ, ত্ৰিপুৰা আৰু মিজোৰাম।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    {
      question: "Which is the highest mountain peak in India?\nভাৰতৰ সৰ্বোচ্চ পৰ্বত শৃংগ কোনটো?",
      options: [
        'Kangchenjunga / কাঞ্চনজংঘা',
        'Nanda Devi / নন্দা দেৱী',
        'K2 / কে২',
        'Mount Everest / মাউণ্ট এভাৰেষ্ট',
      ],
      correctAnswerIndex: 0,
      explanation: "Kangchenjunga (8,586 m), located on the India–Nepal border in Sikkim, is the highest mountain peak within Indian-administered territory and the third highest in the world.\nচিক্কিমত ভাৰত–নেপাল সীমান্তত অৱস্থিত কাঞ্চনজংঘা (৮,৫৮৬ মি) ভাৰত-শাসিত অঞ্চলৰ ভিতৰত সৰ্বোচ্চ শৃংগ আৰু বিশ্বৰ তৃতীয় সৰ্বোচ্চ।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    {
      question: "The Brahmaputra River originates from which glacier?\nব্ৰহ্মপুত্ৰ নদী কোন হিমানদৰ পৰা উৎপন্ন হয়?",
      options: [
        'Gangotri / গংগোত্ৰী',
        'Angsi Glacier / আংচি হিমানদ',
        'Pindari / পিন্দাৰী',
        'Siachen / ছিয়াচেন',
      ],
      correctAnswerIndex: 1,
      explanation: "The Brahmaputra originates from the Angsi Glacier near Mount Kailash in Tibet, where it is known as the Yarlung Tsangpo; it enters India at Arunachal Pradesh.\nব্ৰহ্মপুত্ৰ নদী তিব্বতৰ কৈলাস পৰ্বতৰ ওচৰৰ আংচি হিমানদৰ পৰা উৎপন্ন, য'ত ইয়াক য়াৰলুং চাংপো বোলে; ই অৰুণাচল প্ৰদেশত ভাৰতত সোমায়।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    {
      question: "Which is the largest state in India by area?\nকালিৰ ফালৰ পৰা ভাৰতৰ আটাইতকৈ ডাঙৰ ৰাজ্য কোনখন?",
      options: [
        'Madhya Pradesh / মধ্যপ্ৰদেশ',
        'Maharashtra / মহাৰাষ্ট্ৰ',
        'Rajasthan / ৰাজস্থান',
        'Uttar Pradesh / উত্তৰ প্ৰদেশ',
      ],
      correctAnswerIndex: 2,
      explanation: "Rajasthan is the largest state in India by area, covering about 342,239 sq km, constituting around 10.4% of India's total geographical area.\nৰাজস্থান ভাৰতৰ আটাইতকৈ ডাঙৰ ৰাজ্য, প্ৰায় ৩,৪২,২৩৯ বৰ্গ কিঃমিঃ আগুৰি থাকি, যি ভাৰতৰ মুঠ ভৌগোলিক কালিৰ প্ৰায় ১০.৪%।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    {
      question: "Kaziranga National Park is famous for which animal?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান কোন জন্তুৰ বাবে বিখ্যাত?",
      options: [
        'Royal Bengal Tiger / ৰয়েল বেংগল টাইগাৰ',
        'Asiatic Lion / এচিয়াটিক সিংহ',
        'Snow Leopard / হিমবাঘ',
        'One-horned rhinoceros / এশিঙীয়া গঁড়',
      ],
      correctAnswerIndex: 3,
      explanation: "Kaziranga National Park in Assam is a UNESCO World Heritage Site, home to about two-thirds of the world's population of the Indian one-horned rhinoceros.\nঅসমৰ কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ, বিশ্বৰ ভাৰতীয় এশিঙীয়া গঁড়ৰ প্ৰায় দুই-তৃতীয়াংশ জনসংখ্যাৰ ঘৰ।",
      subjectTopic: 'Geography',
      marks: 2,
    },
    // --- Polity (6) ---
    {
      question: "Who was the permanent Chairman of the Constituent Assembly of India?\nভাৰতৰ সংবিধান সভাৰ স্থায়ী সভাপতি কোন আছিল?",
      options: [
        'Dr. Rajendra Prasad / ড° ৰাজেন্দ্ৰ প্ৰসাদ',
        'Dr. B. R. Ambedkar / ড° বি আৰ আম্বেদকাৰ',
        'Jawaharlal Nehru / জৱাহৰলাল নেহৰু',
        'Sardar Patel / সৰদাৰ পটেল',
      ],
      correctAnswerIndex: 0,
      explanation: "Dr. Rajendra Prasad was elected the permanent Chairman of the Constituent Assembly on 11 December 1946; Dr. B. R. Ambedkar headed the Drafting Committee.\nড° ৰাজেন্দ্ৰ প্ৰসাদক ১১ ডিচেম্বৰ ১৯৪৬ত সংবিধান সভাৰ স্থায়ী সভাপতি হিচাপে নিৰ্বাচিত কৰা হৈছিল; ড° বি আৰ আম্বেদকাৰে খচৰা সমিতিৰ নেতৃত্ব দিছিল।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    {
      question: "How many fundamental rights are guaranteed by the Indian Constitution at present?\nবৰ্তমানে ভাৰতীয় সংবিধানে কিমানটা মৌলিক অধিকাৰ প্ৰদান কৰে?",
      options: [
        'Five / পাঁচটা',
        'Six / ছয়টা',
        'Seven / সাতটা',
        'Eight / আঠটা',
      ],
      correctAnswerIndex: 1,
      explanation: "Originally there were seven fundamental rights; after the 44th Amendment (1978) removed the Right to Property from Article 31, six fundamental rights remain (Articles 12–35).\nআদিতে সাতটা মৌলিক অধিকাৰ আছিল; ৪৪তম সংশোধনী (১৯৭৮) ধাৰা ৩১ৰ সম্পত্তিৰ অধিকাৰ আঁতৰোৱাৰ পিছত ছয়টা মৌলিক অধিকাৰ বাকী আছে (ধাৰা ১২–৩৫)।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    {
      question: "The President of India is elected by which method?\nভাৰতৰ ৰাষ্ট্ৰপতি কোন পদ্ধতিৰে নিৰ্বাচিত হয়?",
      options: [
        'Direct vote of the people / জনগণৰ প্ৰত্যক্ষ ভোট',
        'Members of Lok Sabha only / কেৱল লোকসভাৰ সদস্যসকল',
        'Electoral College / নিৰ্বাচক মণ্ডলী',
        'Supreme Court judges / উচ্চতম ন্যায়ালয়ৰ ন্যায়াধীশসকল',
      ],
      correctAnswerIndex: 2,
      explanation: "The President is elected indirectly by an Electoral College consisting of elected members of both Houses of Parliament and the elected members of the Legislative Assemblies of States and UTs (Delhi & Puducherry), under a proportional representation system.\nৰাষ্ট্ৰপতি সংসদৰ দুয়ো সদনৰ নিৰ্বাচিত সদস্য আৰু ৰাজ্য/কেন্দ্ৰীয় অঞ্চল (দিল্লী আৰু পুডুচেৰী)ৰ বিধানসভাৰ নিৰ্বাচিত সদস্যসকলৰে গঠিত নিৰ্বাচক মণ্ডলীৰ দ্বাৰা পৰোক্ষভাৱে নিৰ্বাচিত হয়, আনুপাতিক প্ৰতিনিধিত্ব পদ্ধতিৰে।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    {
      question: "Which Article of the Indian Constitution deals with equality before law?\nভাৰতীয় সংবিধানৰ কোন ধাৰাটোৱে আইনৰ সমুখত সমতাৰ বিষয়ে প্ৰসংগ কৰে?",
      options: [
        'Article 12 / ধাৰা ১২',
        'Article 13 / ধাৰা ১৩',
        'Article 19 / ধাৰা ১৯',
        'Article 14 / ধাৰা ১৪',
      ],
      correctAnswerIndex: 3,
      explanation: "Article 14 of the Indian Constitution declares that 'the State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.'\nভাৰতীয় সংবিধানৰ ধাৰা ১৪ ৰ অনুসৰি 'ভাৰতৰ ভূখণ্ডৰ ভিতৰত ৰাজ্যই কোনো ব্যক্তিক আইনৰ সমুখত সমতা বা আইনৰ সমান সুৰক্ষা প্ৰদান কৰাৰ পৰা অস্বীকাৰ নকৰে'।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    {
      question: "Who is the head of the Union Council of Ministers in India?\nভাৰতৰ কেন্দ্ৰীয় মন্ত্ৰী পৰিষদৰ মুৰব্বী কোন?",
      options: [
        'Prime Minister / প্ৰধানমন্ত্ৰী',
        'President / ৰাষ্ট্ৰপতি',
        'Chief Justice of India / ভাৰতৰ মুখ্য ন্যায়াধীশ',
        'Speaker of Lok Sabha / লোকসভাৰ অধ্যক্ষ',
      ],
      correctAnswerIndex: 0,
      explanation: "Article 74(1) provides that there shall be a Council of Ministers with the Prime Minister at the head to aid and advise the President in the exercise of his functions.\nধাৰা ৭৪(১) অনুসৰি এটা প্ৰধানমন্ত্ৰীৰ নেতৃত্বাধীন মন্ত্ৰী পৰিষদ থাকিব যিয়ে ৰাষ্ট্ৰপতিক তেওঁৰ কাৰ্য্য পালনত সহায়-পৰামৰ্শ দিব।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    {
      question: "The Parliament of India consists of how many Houses?\nভাৰতৰ সংসদ কিমানটা সদনৰে গঠিত?",
      options: [
        'One / এটা',
        'Two / দুটা',
        'Three / তিনিটা',
        'Four / চাৰিটা',
      ],
      correctAnswerIndex: 1,
      explanation: "The Indian Parliament consists of the President and two Houses — the Lok Sabha (Lower House / House of the People) and the Rajya Sabha (Upper House / Council of States).\nভাৰতীয় সংসদ ৰাষ্ট্ৰপতি আৰু দুটা সদনৰে গঠিত — লোকসভা (নিম্ন সদন) আৰু ৰাজ্যসভা (উচ্চ সদন)।",
      subjectTopic: 'Polity',
      marks: 2,
    },
    // --- Economy (6) ---
    {
      question: "The Reserve Bank of India was established in which year?\nভাৰতীয় ৰিজাৰ্ভ বেংক কতবাৰত প্ৰতিষ্ঠা কৰা হৈছিল?",
      options: [
        '1930 / ১৯৩০',
        '1933 / ১৯৩৩',
        '1935 / ১৯৩৫',
        '1947 / ১৯৪৭',
      ],
      correctAnswerIndex: 2,
      explanation: "The Reserve Bank of India was established on 1 April 1935 under the RBI Act, 1934, and was nationalised on 1 January 1949.\nভাৰতীয় ৰিজাৰ্ভ বেংক ১ এপ্ৰিল ১৯৩৫ত RBI আইন, ১৯৩৪ অনুসৰি প্ৰতিষ্ঠা কৰা হৈছিল, আৰু ১ জানুৱাৰী ১৯৪৯ত ৰাষ্ট্ৰীয়কৰণ কৰা হৈছিল।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    {
      question: "Who is known as the father of the White Revolution in India?\nভাৰতত শ্বেত বিপ্লৱৰ পিতৃ হিচাপে কাক জনা যায়?",
      options: [
        'M. S. Swaminathan / এম এছ স্বামীনাথন',
        'Norman Borlaug / নৰ্মান বৰলাউগ',
        'C. Subramaniam / চি চুব্ৰহ্মণ্যম',
        'Verghese Kurien / ভাৰ্গিজ কুৰিয়েন',
      ],
      correctAnswerIndex: 3,
      explanation: "Verghese Kurien, founder of Amul and the Anand milk cooperative model, led Operation Flood and is called the Father of the White Revolution in India.\nআনন্দ গাখী সহকাৰী আৰু আমুলৰ প্ৰতিষ্ঠাপক ভাৰ্গিজ কুৰিয়েনে অপাৰেচন ফ্লাড চলাইছিল আৰু ভাৰতৰ শ্বেত বিপ্লৱৰ পিতৃ বুলি জনা যায়।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    {
      question: "Goods and Services Tax (GST) was implemented in India from which date?\nভাৰতত পণ্য আৰু সেৱা কৰ (GST) কোন তাৰিখৰ পৰা বলবৎ হৈছিল?",
      options: [
        '1 April 2017 / ১ এপ্ৰিল ২০১৭',
        '1 July 2017 / ১ জুলাই ২০১৭',
        '1 August 2017 / ১ আগষ্ট ২০১৭',
        '1 January 2018 / ১ জানুৱাৰী ২০১৮',
      ],
      correctAnswerIndex: 1,
      explanation: "GST was launched at midnight of 1 July 2017, replacing multiple indirect taxes like excise duty, service tax, VAT and CST through the 101st Constitutional Amendment.\nGST ১ জুলাই ২০১৭ৰ মাজনিশা আৰম্ভ কৰা হৈছিল, ১০১তম সাংবিধানিক সংশোধনীৰে এক্সাইজ, সেৱা কৰ, VAT আদি বহুতো পৰোক্ষ কৰ প্ৰতিস্থাপন কৰি।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    {
      question: "NABARD was established in which year?\nনাবাৰ্ড (NABARD) কতবাৰত প্ৰতিষ্ঠা কৰা হৈছিল?",
      options: [
        '1980 / ১৯৮০',
        '1982 / ১৯৮২',
        '1985 / ১৯৮৫',
        '1991 / ১৯৯১',
      ],
      correctAnswerIndex: 1,
      explanation: "NABARD (National Bank for Agriculture and Rural Development) was established on 12 July 1982 on the recommendation of the B. Sivaraman Committee.\nনাবাৰ্ড (কৃষি আৰু গ্ৰাম্য উন্নয়নৰ ৰাষ্ট্ৰীয় বেংক) বি শিৱৰমণ সমিতিৰ পৰামৰ্শৰে ১২ জুলাই ১৯৮২ত প্ৰতিষ্ঠা কৰা হৈছিল।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    {
      question: "Which Five-Year Plan is also known as the Mahalanobis Plan?\nকোনখন পঞ্চবাৰ্ষিক পৰিকল্পনাক মহালানবিছ পৰিকল্পনা বুলিও কোৱা হয়?",
      options: [
        'First / প্ৰথম',
        'Second / দ্বিতীয়',
        'Third / তৃতীয়',
        'Fourth / চতুৰ্থ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Second Five-Year Plan (1956–61), based on P. C. Mahalanobis's model, emphasised rapid industrialisation with focus on heavy and basic industries.\nদ্বিতীয় পঞ্চবাৰ্ষিক পৰিকল্পনা (১৯৫৬–৬১) পি চি মহালানবিছৰ আৰ্হিৰ ওপৰত আধাৰিত, ভাৰী আৰু মৌলিক উদ্যোগত গুৰুত্ব দি দ্ৰুত শিল্পায়নৰ ওপৰত গুৰুত্ব আৰোপ কৰিছিল।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    {
      question: "NITI Aayog replaced which organisation?\nনীতি আয়োগে কোনটো সংস্থাৰ ঠাই লৈছিল?",
      options: [
        'Finance Commission / বিত্ত আয়োগ',
        'Election Commission / নিৰ্বাচন আয়োগ',
        'Planning Commission / পৰিকল্পনা আয়োগ',
        'Reserve Bank of India / ভাৰতীয় ৰিজাৰ্ভ বেংক',
      ],
      correctAnswerIndex: 2,
      explanation: "NITI Aayog (National Institution for Transforming India) was formed on 1 January 2015, replacing the Planning Commission which had existed since 1950.\nনীতি আয়োগ ১ জানুৱাৰী ২০১৫ত গঠন কৰা হৈছিল, ১৯৫০ৰ পৰা অস্তিত্ব থকা পৰিকল্পনা আয়োগক প্ৰতিস্থাপন কৰি।",
      subjectTopic: 'Economy',
      marks: 2,
    },
    // --- Science (6) ---
    {
      question: "Which gas is the most abundant in the Earth's atmosphere?\nপৃথিৱীৰ বায়ুমণ্ডলত আটাইতকৈ প্ৰচুৰ গেছ কোনটো?",
      options: [
        'Nitrogen / নাইট্ৰোজেন',
        'Oxygen / অক্সিজেন',
        'Carbon dioxide / কাৰ্বন ডাইঅক্সাইড',
        'Hydrogen / হাইড্ৰোজেন',
      ],
      correctAnswerIndex: 0,
      explanation: "Nitrogen makes up about 78% of the Earth's atmosphere by volume, followed by oxygen at about 21%.\nনাইট্ৰোজেনে আয়তন অনুসৰি পৃথিৱীৰ বায়ুমণ্ডলৰ প্ৰায় ৭৮% আগুৰি আছে, তাৰ পিছত অক্সিজেন প্ৰায় ২১%।",
      subjectTopic: 'Science',
      marks: 2,
    },
    {
      question: "What is the chemical formula of water?\nপানীৰ ৰাসায়নিক সূত্ৰ কি?",
      options: [
        "CO2 / চিঅ’২",
        'H2O / এইচ২অ’',
        'NaCl / এনএচিএল',
        "O2 / অ’২",
      ],
      correctAnswerIndex: 1,
      explanation: "Water is composed of two hydrogen atoms covalently bonded to one oxygen atom, giving the formula H2O.\nপানী দুটা হাইড্ৰোজেন পৰমাণু আৰু এটা অক্সিজেন পৰমাণুৰ সহ-সংযোগী বান্ধনিৰে গঠিত, সূত্ৰ H2O।",
      subjectTopic: 'Science',
      marks: 2,
    },
    {
      question: "Who proposed the theory of relativity?\nআপেক্ষিকতাবাদৰ তত্ত্ব কোনে প্ৰস্তাৱ কৰিছিল?",
      options: [
        'Isaac Newton / আইজাক নিউটন',
        'Galileo Galilei / গেলিলিঅ’ গেলিলেই',
        'Albert Einstein / আলবাৰ্ট আইনষ্টাইন',
        'Stephen Hawking / ষ্টিফেন হকিং',
      ],
      correctAnswerIndex: 2,
      explanation: "Albert Einstein published the Special Theory of Relativity in 1905 and the General Theory of Relativity in 1915, revolutionising modern physics.\nআলবাৰ্ট আইনষ্টাইনে ১৯০৫ত বিশেষ আপেক্ষিকতাবাদ আৰু ১৯১৫ত সাধাৰণ আপেক্ষিকতাবাদ প্ৰকাশ কৰিছিল, আধুনিক পদাৰ্থ বিজ্ঞানত বৈপ্লবিক পৰিৱৰ্তন আনি।",
      subjectTopic: 'Science',
      marks: 2,
    },
    {
      question: "The SI unit of electric current is?\nবৈদ্যুতিক প্ৰবাহৰ SI একক কি?",
      options: [
        'Volt / ভোল্ট',
        'Watt / ৱাট',
        'Ohm / অহম',
        'Ampere / এম্পিয়াৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "The ampere (symbol A) is the SI base unit of electric current, named after the French mathematician André-Marie Ampère.\nএম্পিয়াৰ (চিহ্ন A) বৈদ্যুতিক প্ৰবাহৰ SI মৌলিক একক, ফৰাচী গণিতজ্ঞ আন্দ্ৰে-মেৰি এম্পিয়াৰৰ নামেৰে নামাকৰণ কৰা হৈছে।",
      subjectTopic: 'Science',
      marks: 2,
    },
    {
      question: "Vitamin C is also known as?\nভিটামিন চিক আন এটা নামেৰে কি বোলে?",
      options: [
        'Ascorbic acid / এস্কৰবিক এচিড',
        'Retinol / ৰেটিনল',
        'Thiamine / থায়ামিন',
        'Niacin / নিয়াচিন',
      ],
      correctAnswerIndex: 0,
      explanation: "Vitamin C is chemically known as ascorbic acid; its deficiency causes scurvy, a disease characterised by bleeding gums and joint pain.\nভিটামিন চি ৰাসায়নিকভাৱে এস্কৰবিক এচিড বোলে; ইয়াৰ অভাৱে স্কাৰ্ভি ৰোগ হয়, যাৰ লক্ষণ দাঁতৰ আঁহতৰ পৰা তেজ ওলোৱা আৰু জোৰ বিষ।",
      subjectTopic: 'Science',
      marks: 2,
    },
    {
      question: "Which planet is known as the Red Planet?\nকোন গ্ৰহটোক ৰঙা গ্ৰহ বোলা হয়?",
      options: [
        'Jupiter / বৃহস্পতি',
        'Mars / মংগল গ্ৰহ',
        'Venus / শুক্ৰ গ্ৰহ',
        'Saturn / শনি গ্ৰহ',
      ],
      correctAnswerIndex: 1,
      explanation: "Mars appears red due to the presence of iron oxide (rust) on its surface, hence it is called the Red Planet.\nমংগল গ্ৰহৰ পৃষ্ঠত আইৰণ অক্সাইড (মৰিচা) থকাৰ বাবে তাৰ ৰং ৰঙা দেখা যায়, সেয়ে ইয়াক ৰঙা গ্ৰহ বোলা হয়।",
      subjectTopic: 'Science',
      marks: 2,
    },
    // --- Current Affairs (5) ---
    {
      question: "Who is the Chief Minister of Assam as of 2024?\n২০২৪ চনৰ হিচাপে অসমৰ মুখ্যমন্ত্ৰী কোন?",
      options: [
        'Sarbananda Sonowal / সৰ্বানন্দ সোণোৱাল',
        'Tarun Gogoi / তৰুণ গগৈ',
        'Himanta Biswa Sarma / হিমন্ত বিশ্ব শৰ্মা',
        'Prafulla Kumar Mahanta / প্ৰফুল্ল কুমাৰ মহন্ত',
      ],
      correctAnswerIndex: 2,
      explanation: "Dr. Himanta Biswa Sarma became the 15th Chief Minister of Assam on 10 May 2021, succeeding Sarbananda Sonowal.\nড° হিমন্ত বিশ্ব শৰ্মাই ১০ মে’ ২০২১ত সৰ্বানন্দ সোণোৱালৰ পিছত অসমৰ ১৫তম মুখ্যমন্ত্ৰী হিচাপে কাৰ্য্যভাৰ গ্ৰহণ কৰে।",
      subjectTopic: 'Current Affairs',
      marks: 2,
    },
    {
      question: "India hosted the G20 Summit 2023 in which city?\nভাৰতে ২০২৩ চনত G20 শিখৰ সন্মিলন কোন চহৰত আয়োজন কৰিছিল?",
      options: [
        'Mumbai / মুম্বাই',
        'Kolkata / কলকাতা',
        'Chennai / চেন্নাই',
        'New Delhi / নতুন দিল্লী',
      ],
      correctAnswerIndex: 3,
      explanation: "India hosted the 18th G20 Summit at the Bharat Mandapam in New Delhi on 9–10 September 2023 under the theme 'Vasudhaiva Kutumbakam'.\nভাৰতে ৯–১০ ছেপ্তেম্বৰ ২০২৩ত নতুন দিল্লীৰ ভাৰত মণ্ডপমত 'বসুধৈৱ কুটুম্বকম' মূল সূত্ৰৰে ১৮তম G20 শিখৰ সন্মিলন আয়োজন কৰিছিল।",
      subjectTopic: 'Current Affairs',
      marks: 2,
    },
    {
      question: "Chandrayaan-3 successfully landed on the Moon in which year?\nচন্দ্ৰযান-৩ কতবাৰত সফলতাৰে চন্দ্ৰত অৱতৰণ কৰিছিল?",
      options: [
        '2023 / ২০২৩',
        '2022 / ২০২২',
        '2024 / ২০২৪',
        '2021 / ২০২১',
      ],
      correctAnswerIndex: 0,
      explanation: "Chandrayaan-3's Vikram lander soft-landed on the lunar south pole on 23 August 2023, making India the first country to reach that region.\nচন্দ্ৰযান-৩ৰ বিক্ৰম লেণ্ডাৰে ২৩ আগষ্ট ২০২৩ত চন্দ্ৰৰ দক্ষিণ মেৰুত কোমল অৱতৰণ কৰিছিল, যাৰ ফলত ভাৰত সেই অঞ্চলত উপনীত হোৱা প্ৰথম দেশ হিচাপে পৰিগণিত হয়।",
      subjectTopic: 'Current Affairs',
      marks: 2,
    },
    {
      question: "Who won the Nobel Peace Prize 2023?\n২০২৩ চনৰ শান্তিৰ নোবেল বঁটা কোনে লাভ কৰিছিল?",
      options: [
        'Maria Ressa / মাৰিয়া ৰেছা',
        'Narges Mohammadi / নাৰ্গেছ মহম্মদী',
        'Abiy Ahmed / আবিয় আহমেদ',
        'World Food Programme / বিশ্ব খাদ্য কাৰ্য্যসূচী',
      ],
      correctAnswerIndex: 1,
      explanation: "Iranian activist Narges Mohammadi won the 2023 Nobel Peace Prize for her fight against the oppression of women in Iran and for human rights for all.\nইৰানী কৰ্মী নাৰ্গেছ মহম্মদীয়ে ইৰানত মহিলাৰ অত্যাচাৰৰ বিৰুদ্ধে যুঁজ আৰু সকলোৰে বাবে মানৱ অধিকাৰৰ বাবে ২০২৩ চনৰ শান্তিৰ নোবেল বঁটা লাভ কৰিছিল।",
      subjectTopic: 'Current Affairs',
      marks: 2,
    },
    {
      question: "The 2024 Summer Olympic Games were held in which city?\n২০২৪ চনৰ গ্ৰীষ্মকালীন অলিম্পিক খেল কোন চহৰত অনুষ্ঠিত হৈছিল?",
      options: [
        'Tokyo / টকিঅ’',
        'Los Angeles / লছ এঞ্জেলছ',
        'Paris / পেৰিছ',
        'Beijing / বেইজিং',
      ],
      correctAnswerIndex: 2,
      explanation: "The 2024 Summer Olympics (Games of the XXXIII Olympiad) were held in Paris, France, from 26 July to 11 August 2024.\n২০২৪ চনৰ গ্ৰীষ্মকালীন অলিম্পিক (XXXIII অলিম্পিয়াড) ২৬ জুলাইৰ পৰা ১১ আগষ্ট ২০২৪লৈ ফ্ৰান্সৰ পেৰিছত অনুষ্ঠিত হৈছিল।",
      subjectTopic: 'Current Affairs',
      marks: 2,
    },
    // --- Assam GK (5) ---
    {
      question: "What is the capital of Assam?\nঅসমৰ ৰাজধানী কি?",
      options: [
        'Guwahati / গুৱাহাটী',
        'Dibrugarh / ডিব্ৰুগড়',
        'Jorhat / যোৰহাট',
        'Dispur / দিছপুৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "Dispur, a locality of Guwahati, became the capital of Assam in 1973 when it was shifted from Shillong (now capital of Meghalaya).\nগুৱাহাটীৰ এটা অঞ্চল দিছপুৰ ১৯৭৩ত অসমৰ ৰাজধানী হয়, যেতিয়া শ্বিলং (বৰ্তমান মেঘালয়ৰ ৰাজধানী)ৰ পৰা স্থানান্তৰ কৰা হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 2,
    },
    {
      question: "Who was the first Chief Minister of Assam?\nঅসমৰ প্ৰথমগৰাকী মুখ্যমন্ত্ৰী কোন আছিল?",
      options: [
        'Gopinath Bordoloi / গোপীনাথ বৰদলৈ',
        'Bishnuram Medhi / বিষ্ণুৰাম মেধি',
        'Fakhruddin Ali Ahmed / ফখৰুদ্দিন আলি আহমেদ',
        'Sarat Chandra Sinha / শৰত চন্দ্ৰ সিনহা',
      ],
      correctAnswerIndex: 0,
      explanation: "Gopinath Bordoloi became the first Chief Minister of Assam in 1946 (pre-independence) and continued after independence until 1950; he was later awarded the Bharat Ratna in 1999.\nগোপীনাথ বৰদলৈ ১৯৪৬ত (স্বাধীনতাৰ আগতে) অসমৰ প্ৰথম মুখ্যমন্ত্ৰী হৈছিল আৰু স্বাধীনতাৰ পিছতো ১৯৫০লৈ কাৰ্য্যনিৰ্বাহ কৰিছিল; তেওঁক ১৯৯৯ত মৰণোত্তৰভাৱে ভাৰত ৰত্ন বঁটা প্ৰদান কৰা হয়।",
      subjectTopic: 'Assam GK',
      marks: 2,
    },
    {
      question: "The Assam Movement (1979–1985) ended with the signing of which accord?\nঅসম আন্দোলন (১৯৭৯–১৯৮৫) কোন চুক্তি স্বাক্ষৰৰে সমাপ্ত হৈছিল?",
      options: [
        'Shillong Accord / শ্বিলং চুক্তি',
        'Assam Accord / অসম চুক্তি',
        'Punjab Accord / পঞ্জাৱ চুক্তি',
        'Mizo Accord / মিজো চুক্তি',
      ],
      correctAnswerIndex: 1,
      explanation: "The Assam Accord was signed on 15 August 1985 between the Government of India and the leaders of the Assam Movement (AASU) in the presence of Prime Minister Rajiv Gandhi.\nঅসম চুক্তি ১৫ আগষ্ট ১৯৮৫ত ভাৰত চৰকাৰ আৰু অসম আন্দোলনৰ (AASU) নেতাসকলৰ মাজত প্ৰধানমন্ত্ৰী ৰাজীৱ গান্ধীৰ উপস্থিতিত স্বাক্ষৰিত হৈছিল।",
      subjectTopic: 'Assam GK',
      marks: 2,
    },
    {
      question: "Which is the state flower of Assam?\nঅসমৰ ৰাজ্যিক ফুল কি?",
      options: [
        'Lotus / পদুম',
        'Rose / গোলাপ',
        'Foxtail Orchid (Kopou Phul) / কপৌ ফুল',
        'Sunflower / সূৰ্যমুখী',
      ],
      correctAnswerIndex: 2,
      explanation: "The Foxtail Orchid (Rhynchostylis retusa), locally called Kopou Phul, is the state flower of Assam and is traditionally used by Assamese women to adorn their hair during Rongali Bihu.\nফক্সটেইল অৰ্কিড (Rhynchostylis retusa), স্থানীয়ভাৱে কপৌ ফুল বোলা, অসমৰ ৰাজ্যিক ফুল আৰু অসমীয়া মহিলাসকলে ৰঙালী বিহুত নিজৰ দীঘল চুলিত সজাবলৈ পৰম্পৰাগতভাৱে ব্যৱহাৰ কৰে।",
      subjectTopic: 'Assam GK',
      marks: 2,
    },
    {
      question: "The Bogibeel Bridge is built over which river?\nবগিবিল দলং কোন নদীৰ ওপৰত নিৰ্মিত?",
      options: [
        'Barak / বৰাক',
        'Subansiri / সুবনসিৰি',
        'Manas / মানস',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "The Bogibeel Bridge, inaugurated on 25 December 2018, is a combined road and rail bridge over the Brahmaputra connecting Dibrugarh and Dhemaji districts in Assam; at 4.94 km it is India's longest rail-cum-road bridge.\n২৫ ডিচেম্বৰ ২০১৮ত উদ্বোধন কৰা বগিবিল দলং ব্ৰহ্মপুত্ৰ নদীৰ ওপৰত এখন সড়ক-ৰেল সংযুক্ত দলং, যিয়ে অসমৰ ডিব্ৰুগড় আৰু ধেমাজি জিলা সংযোগ কৰে; ৪.৯৪ কিঃমিঃ দৈৰ্ঘ্যৰে ভাৰতৰ আটাইতকৈ দীঘল ৰেল-সড়ক দলং।",
      subjectTopic: 'Assam GK',
      marks: 2,
    },
  ],

  // ===========================================================================
  // apsc-history — History of India & Assam (40)
  // ===========================================================================
  'apsc-history': [
    // --- Ancient India (8) ---
    {
      question: "Who is regarded as the real founder of the Gupta Empire?\nগুপ্ত সাম্ৰাজ্যৰ প্ৰকৃত প্ৰতিষ্ঠাপক বুলি কাক গণ্য কৰা হয়?",
      options: [
        'Chandragupta I / প্ৰথম চন্দ্ৰগুপ্ত',
        'Sri Gupta / শ্ৰী গুপ্ত',
        'Samudragupta / সমুদ্ৰগুপ্ত',
        'Chandragupta II / দ্বিতীয় চন্দ্ৰগুপ্ত',
      ],
      correctAnswerIndex: 0,
      explanation: "Chandragupta I (reigned c. 320–335 CE) is regarded as the real founder of the Gupta Empire as he started the Gupta era in 319 CE and assumed the title 'Maharajadhiraja'.\nপ্ৰথম চন্দ্ৰগুপ্ত (শাসনকাল আনুমানিক ৩২০–৩৩৫ খ্ৰী:) গুপ্ত সাম্ৰাজ্যৰ প্ৰকৃত প্ৰতিষ্ঠাপক বুলি গণ্য কৰা হয় কিয়নো তেওঁ ৩১৯ খ্ৰী:ত গুপ্ত যুগ আৰম্ভ কৰিছিল আৰু 'মহাৰাজাধিৰাজ' উপাধি গ্ৰহণ কৰিছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "The Harappan Civilization belonged to which age?\nহৰপ্পা সভ্যতা কোন যুগৰ আছিল?",
      options: [
        'Iron Age / লোহ যুগ',
        'Bronze Age / ব্ৰঞ্জ যুগ',
        'Stone Age / শিল যুগ',
        'Copper Age / তামৰ যুগ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Harappan (Indus Valley) Civilization flourished during the Bronze Age, roughly 2600–1900 BCE, and is noted for its urban planning and metallurgy.\nহৰপ্পা (সিন্ধু উপত্যকা) সভ্যতা ব্ৰঞ্জ যুগত বিকশিত হৈছিল, আনুমানিক ২৬০০–১৯০০ খ্ৰীঃপূৰ্ব, আৰু ইয়াৰ নগৰ পৰিকল্পনা আৰু ধাতুবিদ্যাৰ বাবে জনাজাত।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "Who founded the Mauryan Empire?\nমৌৰ্য সাম্ৰাজ্য কোনে প্ৰতিষ্ঠা কৰিছিল?",
      options: [
        'Ashoka / অশোক',
        'Bindusara / বিন্দুসাৰ',
        'Chandragupta Maurya / চন্দ্ৰগুপ্ত মৌৰ্য',
        'Chanakya / চাণক্য',
      ],
      correctAnswerIndex: 2,
      explanation: "Chandragupta Maurya founded the Mauryan Empire around 322 BCE, overthrowing the Nanda dynasty of Magadha with the help of his mentor Chanakya.\nচন্দ্ৰগুপ্ত মৌৰ্যই আনুমানিক ৩২২ খ্ৰীঃপূৰ্বত তেওঁৰ গুৰু চাণক্যৰ সহায়ত মগধৰ নন্দ বংশক উৎখাত কৰি মৌৰ্য সাম্ৰাজ্য প্ৰতিষ্ঠা কৰিছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "Megasthenes visited India during whose reign?\nমেগাস্থেনিছে কাৰ ৰাজত্বকালত ভাৰত ভ্ৰমণ কৰিছিল?",
      options: [
        'Ashoka / অশোক',
        'Bindusara / বিন্দুসাৰ',
        'Samudragupta / সমুদ্ৰগুপ্ত',
        'Chandragupta Maurya / চন্দ্ৰগুপ্ত মৌৰ্য',
      ],
      correctAnswerIndex: 3,
      explanation: "Megasthenes was the Greek ambassador of Seleucus I Nicator to the court of Chandragupta Maurya at Pataliputra; his work 'Indica' is a key source on Mauryan India.\nমেগাস্থেনিছ চেলিউকাছ প্ৰথম নিকেটৰৰ গ্ৰীক ৰাষ্ট্ৰদূত আছিল যি পাটলিপুত্ৰত চন্দ্ৰগুপ্ত মৌৰ্যৰ দৰবাৰলৈ আহিছিল; তেওঁৰ 'ইণ্ডিকা' মৌৰ্য ভাৰতৰ এক গুৰুত্বপূৰ্ণ উৎস।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "Who wrote the Arthashastra?\nঅৰ্থশাস্ত্ৰ কোনে ৰচনা কৰিছিল?",
      options: [
        'Kautilya (Chanakya) / কৌটিল্য (চাণক্য)',
        'Kalidasa / কালিদাস',
        'Tulsidas / তুলসীদাস',
        'Panini / পাণিনি',
      ],
      correctAnswerIndex: 0,
      explanation: "The Arthashastra, a treatise on statecraft, economic policy and military strategy, was written by Kautilya (also known as Chanakya or Vishnugupta), the prime minister of Chandragupta Maurya.\nৰাজনীতি বিজ্ঞান, অৰ্থনৈতিক নীতি আৰু সামৰিক কৌশলৰ গ্ৰন্থ অৰ্থশাস্ত্ৰ কৌটিল্যে (চাণক্য বা বিষ্ণুগুপ্ত) ৰচনা কৰিছিল, যি চন্দ্ৰগুপ্ত মৌৰ্যৰ প্ৰধানমন্ত্ৰী আছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "The Chinese traveller Fa-Hien visited India during whose reign?\nচীনা পৰিব্ৰাজক ফা-হিয়েন কাৰ ৰাজত্বকালত ভাৰত ভ্ৰমণ কৰিছিল?",
      options: [
        'Harsha / হৰ্ষ',
        'Chandragupta II / দ্বিতীয় চন্দ্ৰগুপ্ত',
        'Samudragupta / সমুদ্ৰগুপ্ত',
        'Ashoka / অশোক',
      ],
      correctAnswerIndex: 1,
      explanation: "Fa-Hien visited India during the reign of Chandragupta II (Vikramaditya) around 405–411 CE, leaving valuable accounts of the Gupta administration and Buddhist institutions.\nফা-হিয়েন আনুমানিক ৪০৫–৪১১ খ্ৰী:ত দ্বিতীয় চন্দ্ৰগুপ্ত (বিক্ৰমাদিত্য)ৰ ৰাজত্বকালত ভাৰত ভ্ৰমণ কৰিছিল আৰু গুপ্ত প্ৰশাসন আৰু বৌদ্ধ প্ৰতিষ্ঠানৰ মূল্যবান বিৱৰণ এৰি থৈছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "The Ajanta caves were primarily patronised by which dynasty?\nঅজন্তা গুহাসমূহ মূলতঃ কোন বংশই পৃষ্ঠপোষকতা কৰিছিল?",
      options: [
        'Maurya / মৌৰ্য',
        'Kushana / কুষাণ',
        'Vakataka / বাকাটক',
        'Chola / চোল',
      ],
      correctAnswerIndex: 2,
      explanation: "The later phase of the Ajanta caves was patronised by the Vakataka dynasty, especially under Emperor Harishena (c. 460–480 CE), contemporaries of the Guptas.\nঅজন্তা গুহাৰ পৰৱৰ্তী পৰ্যায় বাকাটক বংশই বিশেষকৈ সম্ৰাট হৰিষেণৰ (আনুমানিক ৪৬০–৪৮০ খ্ৰী:) অধীনত পৃষ্ঠপোষকতা কৰিছিল, যি গুপ্তসকলৰ সমসাময়িক আছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    {
      question: "Who was the most famous king of the Chola dynasty?\nচোল বংশৰ আটাইতকৈ বিখ্যাত ৰজা কোন আছিল?",
      options: [
        'Vijayalaya / বিজয়ালয়',
        'Rajendra Chola III / তৃতীয় ৰাজেন্দ্ৰ চোল',
        'Parantaka I / প্ৰথম পৰন্তক',
        'Rajaraja Chola I / প্ৰথম ৰাজৰাজ চোল',
      ],
      correctAnswerIndex: 3,
      explanation: "Rajaraja Chola I (reigned 985–1014 CE) was the greatest Chola ruler who built the Brihadisvara Temple at Thanjavur and expanded the empire across South India and Sri Lanka.\nপ্ৰথম ৰাজৰাজ চোল (শাসনকাল ৯৮৫–১০১৪ খ্ৰী:) আটাইতকৈ শ্ৰেষ্ঠ চোল শাসক আছিল যিয়ে থাঞ্জাভুৰত বৃহদীশ্বৰ মন্দিৰ নিৰ্মাণ কৰিছিল আৰু দক্ষিণ ভাৰত আৰু শ্ৰীলংকালৈ সাম্ৰাজ্য বিস্তাৰ কৰিছিল।",
      subjectTopic: 'Ancient India',
      marks: 2,
    },
    // --- Medieval India (8) ---
    {
      question: "Who founded the Khalji dynasty of the Delhi Sultanate?\nদিল্লী চুলতানীৰ খলজী বংশ কোনে প্ৰতিষ্ঠা কৰিছিল?",
      options: [
        'Jalal-ud-din Khalji / জালাল-উদ-দিন খলজী',
        'Alauddin Khalji / আলাউদ্দিন খলজী',
        'Razia Sultana / ৰাজিয়া চুলতানা',
        'Iltutmish / ইলতুতমিছ',
      ],
      correctAnswerIndex: 0,
      explanation: "Jalal-ud-din Khalji founded the Khalji dynasty in 1290 by overthrowing the last Mamluk ruler Muizuddin Qaiqabad; he ruled until he was murdered by his nephew Alauddin in 1296.\nজালাল-উদ-দিন খলজীয়ে ১২৯০ত শেষ মামলুক শাসক মুইজউদ্দিন কায়কাবাদক উৎখাত কৰি খলজী বংশ প্ৰতিষ্ঠা কৰিছিল; তেওঁ ১২৯৬ত ভতিজাক আলাউদ্দিনে হত্যা নকৰালৈকে শাসন কৰিছিল।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "The Battle of Khanwa (1527) was fought between Babur and which Rajput ruler?\nখানুৱাৰ যুদ্ধ (১৫২৭) বাবৰ আৰু কোন ৰাজপুত ৰজাৰ মাজত সংঘটিত হৈছিল?",
      options: [
        'Ibrahim Lodi / ইব্ৰাহিম লোদী',
        'Rana Sanga / ৰাণা সাংগা',
        'Hemu / হেমু',
        'Sher Shah Suri / শেৰ শাহ ছুৰি',
      ],
      correctAnswerIndex: 1,
      explanation: "The Battle of Khanwa was fought on 17 March 1527 between Babur and Rana Sanga of Mewar; Babur's victory established Mughal supremacy over northern India.\nখানুৱাৰ যুদ্ধ ১৭ মাৰ্চ ১৫২৭ত বাবৰ আৰু মেৱাৰৰ ৰাণা সাংগাৰ মাজত সংঘটিত হৈছিল; বাবৰৰ বিজয়ে উত্তৰ ভাৰতত মোগল আধিপত্য প্ৰতিষ্ঠা কৰিছিল।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "The Taj Mahal was built by which Mughal emperor?\nতাজমহল কোন মোগল সম্ৰাটে নিৰ্মাণ কৰাইছিল?",
      options: [
        'Akbar / আকবৰ',
        'Jahangir / জাহাংগীৰ',
        'Shah Jahan / শাহজাহান',
        'Aurangzeb / ঔৰংগজেব',
      ],
      correctAnswerIndex: 2,
      explanation: "The Taj Mahal at Agra was built by Mughal Emperor Shah Jahan between 1632 and 1653 in memory of his wife Mumtaz Mahal; it is a UNESCO World Heritage Site.\nআগ্ৰাৰ তাজমহল মোগল সম্ৰাট শাহজাহানে ১৬৩২ৰ পৰা ১৬৫৩লৈ পত্নী মমতাজ মহলৰ সোঁৱৰণত নিৰ্মাণ কৰাইছিল; এইটো এক ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "The Vijayanagara Empire was founded by?\nবিজয়নগৰ সাম্ৰাজ্য কোনে প্ৰতিষ্ঠা কৰিছিল?",
      options: [
        'Krishnadevaraya / কৃষ্ণদেৱ ৰায়',
        'Devaraya II / দ্বিতীয় দেৱ ৰায়',
        'Bukka Raya I (with Harihara I) / প্ৰথম বুক্ক ৰায় (প্ৰথম হৰিহৰৰ সৈতে)',
        'Sangama / সংগম',
      ],
      correctAnswerIndex: 2,
      explanation: "The Vijayanagara Empire was founded in 1336 by Harihara I and Bukka Raya I of the Sangama dynasty, with capital at Vijayanagara (Hampi), on the banks of the Tungabhadra.\nবিজয়নগৰ সাম্ৰাজ্য ১৩৩৬ত সংগম বংশৰ প্ৰথম হৰিহৰ আৰু প্ৰথম বুক্ক ৰায়ে তুংগভদ্ৰা নদীৰ পাৰত বিজয়নগৰ (হাম্পি) ৰাজধানী হিচাপে প্ৰতিষ্ঠা কৰিছিল।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "Who was the founder of the Maratha Empire?\nমাৰাঠা সাম্ৰাজ্যৰ প্ৰতিষ্ঠাপক কোন আছিল?",
      options: [
        'Shivaji / শিৱাজী',
        'Bajirao I / প্ৰথম বাজিৰাও',
        'Sambhaji / সম্ভাজী',
        'Balaji Vishwanath / বলৱন্ত বিশ্বনাথ',
      ],
      correctAnswerIndex: 0,
      explanation: "Chhatrapati Shivaji Maharaj founded the Maratha Empire in 1674 after escaping Aurangzeb's imprisonment and was crowned at Raigad on 6 June 1674.\nছত্ৰপতি শিৱাজী মহাৰাজে ঔৰংগজেবৰ কাৰাবাসৰ পৰা পলাই ১৬৭৪ত মাৰাঠা সাম্ৰাজ্য প্ৰতিষ্ঠা কৰিছিল আৰু ৬ জুন ১৬৭৪ত ৰায়গড়ত ৰাজ্যাভিষেক হৈছিল।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "The First Battle of Panipat was fought in which year?\nপানিপথৰ প্ৰথম যুদ্ধ কতবাৰত সংঘটিত হৈছিল?",
      options: [
        '1525 / ১৫২৫',
        '1526 / ১৫২৬',
        '1530 / ১৫৩০',
        '1556 / ১৫৫৬',
      ],
      correctAnswerIndex: 1,
      explanation: "The First Battle of Panipat was fought on 21 April 1526 between Babur and Ibrahim Lodi, marking the beginning of the Mughal Empire in India.\nপানিপথৰ প্ৰথম যুদ্ধ ২১ এপ্ৰিল ১৫২৬ত বাবৰ আৰু ইব্ৰাহিম লোদীৰ মাজত সংঘটিত হৈছিল, যি ভাৰতত মোগল সাম্ৰাজ্যৰ আৰম্ভণি চিহ্নিত কৰে।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "Who built the Grand Trunk Road?\nগ্ৰেণ্ড ট্ৰাংক ৰোড কোনে নিৰ্মাণ কৰাইছিল?",
      options: [
        'Akbar / আকবৰ',
        'Humayun / হুমায়ুন',
        'Sher Shah Suri / শেৰ শাহ ছুৰি',
        'Babur / বাবৰ',
      ],
      correctAnswerIndex: 2,
      explanation: "Sher Shah Suri built the Grand Trunk Road (Sadak-e-Azam) in the 16th century, running from Sonargaon (now in Bangladesh) to Peshawar (now in Pakistan).\nশেৰ শাহ ছুৰিয়ে ১৬শ শতিকাত গ্ৰেণ্ড ট্ৰাংক ৰোড (চড়ক-এ-আজম) নিৰ্মাণ কৰাইছিল, যি সোনাৰগাঁও (বৰ্তমান বাংলাদেশত)ৰ পৰা পেশাৱৰলৈ (বৰ্তমান পাকিস্তানত) পৰিছিল।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    {
      question: "The Bhakti saint Kabir was a disciple of which guru?\nভক্তি সন্ত কবিৰ কাৰ শিষ্য আছিল?",
      options: [
        'Ramanuja / ৰামানুজ',
        'Chaitanya Mahaprabhu / চৈতন্য মহাপ্ৰভু',
        'Tulsidas / তুলসীদাস',
        'Ramananda / ৰামানন্দ',
      ],
      correctAnswerIndex: 3,
      explanation: "Kabir (1440–1518) was a disciple of the Bhakti saint Ramananda; his teachings are recorded in the Bijak and he is revered by both Hindus and Muslims.\nকবিৰ (১৪৪০–১৫১৮) ভক্তি সন্ত ৰামানন্দৰ শিষ্য আছিল; তেওঁৰ শিক্ষা বীজকত লিপিবদ্ধ আৰু তেওঁক হিন্দু আৰু মুছলমান উভয়ে শ্ৰদ্ধা কৰে।",
      subjectTopic: 'Medieval India',
      marks: 2,
    },
    // --- Modern India (8) ---
    {
      question: "Who was the first European to reach India by sea in 1498?\n১৪৯৮ত সাগৰী পথেৰে ভাৰতত উপনীত হোৱা প্ৰথমজন ইউৰোপীয় কোন আছিল?",
      options: [
        'Vasco da Gama / ভাস্কো দা গামা',
        'Christopher Columbus / ক্ৰিষ্টোফাৰ কলম্বাছ',
        'Ferdinand Magellan / ফাৰ্ডিনেণ্ড মেগেলান',
        'Francisco de Almeida / ফ্ৰান্সিস্কো দে আলমেইডা',
      ],
      correctAnswerIndex: 0,
      explanation: "Portuguese explorer Vasco da Gama reached Calicut (Kozhikode) on the Malabar Coast on 20 May 1498, opening the sea route from Europe to India.\nপৰ্তুগীজ অন্বেষক ভাস্কো দা গামাই ২০ মে’ ১৪৯৮ত মালাবাৰ উপকূলৰ কালিকট (কোজিকোড)ত উপনীত হৈ ইউৰোপৰ পৰা ভাৰতলৈ সাগৰী পথ মুকলি কৰিছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The Battle of Plassey (1757) was fought between the British and whom?\nপলাশীৰ যুদ্ধ (১৭৫৭) ব্ৰিটিছ আৰু কাৰ মাজত সংঘটিত হৈছিল?",
      options: [
        'British vs Marathas / ব্ৰিটিছ বনাম মাৰাঠা',
        'British vs Siraj-ud-Daulah / ব্ৰিটিছ বনাম ছিৰাজ-উদ-দৌলা',
        'British vs Tipu Sultan / ব্ৰিটিছ বনাম টিপু চুলতান',
        'British vs Nawab of Awadh / ব্ৰিটিছ বনাম অৱধৰ নবাব',
      ],
      correctAnswerIndex: 1,
      explanation: "The Battle of Plassey on 23 June 1757 was fought between the British East India Company under Robert Clive and Nawab Siraj-ud-Daulah of Bengal, whose defeat began British rule in India.\nপলাশীৰ যুদ্ধ ২৩ জুন ১৭৫৭ত ৰবাৰ্ট ক্লাইৱৰ নেতৃত্বাধীন ব্ৰিটিছ ইষ্ট ইণ্ডিয়া কোম্পানী আৰু বংগৰ নবাব ছিৰাজ-উদ-দৌলাৰ মাজত হৈছিল; নবাবৰ পৰাজয়ে ভাৰতত ব্ৰিটিছ শাসন আৰম্ভ কৰিছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The Treaty of Yandabo was signed in which year?\nইয়াণ্ডাবু সন্ধি কতবাৰত স্বাক্ষৰিত হৈছিল?",
      options: [
        '1824 / ১৮২৪',
        '1825 / ১৮২৫',
        '1826 / ১৮২৬',
        '1827 / ১৮২৭',
      ],
      correctAnswerIndex: 2,
      explanation: "The Treaty of Yandabo was signed on 24 February 1826 between the East India Company and the Kingdom of Burma, ending the First Anglo-Burmese War and bringing Assam into British India.\nইয়াণ্ডাবু সন্ধি ২৪ ফেব্ৰুৱাৰী ১৮২৬ত ইষ্ট ইণ্ডিয়া কোম্পানী আৰু বাৰ্মা ৰাজ্যৰ মাজত স্বাক্ষৰিত হৈছিল, প্ৰথম এংলো-বাৰ্মিজ যুদ্ধৰ অন্ত ঘটাই অসমক ব্ৰিটিছ ভাৰতত অন্তৰ্ভুক্ত কৰিছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "Who introduced the Permanent Settlement in Bengal in 1793?\n১৭৯৩ত বংগত স্থায়ী বন্দোবস্ত কোনে প্ৰৱৰ্তন কৰিছিল?",
      options: [
        'Lord Wellesley / লৰ্ড ৱেলেছলী',
        'Lord Hastings / লৰ্ড হেষ্টিংছ',
        'Lord William Bentinck / লৰ্ড উইলিয়াম বেণ্টিংক',
        'Lord Cornwallis / লৰ্ড কৰ্ণৱালিছ',
      ],
      correctAnswerIndex: 3,
      explanation: "Lord Cornwallis introduced the Permanent Settlement (Zamindari system) in Bengal and Bihar in 1793, fixing the land revenue demand permanently and making zamindars the owners of land.\nলৰ্ড কৰ্ণৱালিছে ১৭৯৩ত বংগ আৰু বিহাৰত স্থায়ী বন্দোবস্ত (জমিদাৰী ব্যৱস্থা) প্ৰৱৰ্তন কৰিছিল, ভূমি ৰাজহ স্থায়ীভাৱে নিৰ্ধাৰণ কৰি জমিদাৰসকলক ভূমিৰ মালিক কৰি তুলিছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The Doctrine of Lapse was introduced by which Governor-General?\nলেপছৰ তত্ত্ব কোনজন গৱৰ্ণৰ-জেনেৰেলে প্ৰৱৰ্তন কৰিছিল?",
      options: [
        'Lord Dalhousie / লৰ্ড ডালহৌছি',
        'Lord Canning / লৰ্ড কেনিং',
        'Lord Curzon / লৰ্ড কাৰ্জন',
        'Lord Ripon / লৰ্ড ৰিপন',
      ],
      correctAnswerIndex: 0,
      explanation: "Lord Dalhousie introduced the Doctrine of Lapse (1848–1856), under which Indian states without a natural male heir were annexed by the British — Satara, Jhansi, Nagpur and Awadh were annexed this way.\nলৰ্ড ডালহৌছিয়ে লেপছৰ তত্ত্ব (১৮৪৮–১৮৫৬) প্ৰৱৰ্তন কৰিছিল, যাৰ অধীনত প্ৰাকৃতিক পুৰুষ উত্তৰাধিকাৰী নথকা ভাৰতীয় ৰাজ্য ব্ৰিটিছে অধিগ্ৰহণ কৰিছিল — চতাৰা, ঝাঁচি, নাগপুৰ আৰু অৱধ এইভাবে অধিগ্ৰহণ কৰা হৈছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The Indian National Congress was founded in which year?\nভাৰতীয় জাতীয় কংগ্ৰেছ কতবাৰত প্ৰতিষ্ঠা কৰা হৈছিল?",
      options: [
        '1875 / ১৮৭৫',
        '1885 / ১৮৮৫',
        '1895 / ১৮৯৫',
        '1905 / ১৯০৫',
      ],
      correctAnswerIndex: 1,
      explanation: "The Indian National Congress was founded on 28 December 1885 in Bombay by A. O. Hume, with Womesh Chunder Bonnerjee as its first president.\nভাৰতীয় জাতীয় কংগ্ৰেছ ২৮ ডিচেম্বৰ ১৮৮৫ত বোম্বাইত এ অ’ হিউমে প্ৰতিষ্ঠা কৰিছিল, উমেশ চন্দ্ৰ বন্দ্যোপাধ্যায়ক প্ৰথম সভাপতি হিচাপে লৈ।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The first oil well in Asia was drilled at Digboi, Assam, in which year?\nএছিয়াৰ প্ৰথম তেলৰ কুঁৱা অসমৰ ডিগবৈত কতবাৰত খনন কৰা হৈছিল?",
      options: [
        '1867 / ১৮৬৭',
        '1889 / ১৮৮৯',
        '1901 / ১৯০১',
        '1911 / ১৯১১',
      ],
      correctAnswerIndex: 1,
      explanation: "The first commercial oil well in Asia was drilled at Digboi in Assam in 1889 by the Assam Railways & Trading Company; the Digboi oilfield is also the world's oldest continuously producing oilfield.\nএছিয়াৰ প্ৰথম বাণিজ্যিক তেল কুঁৱা ১৮৮৯ত অসমৰ ডিগবৈত আছাম ৰেলৱেজ এণ্ড ট্ৰেডিং কোম্পানীয়ে খনন কৰিছিল; ডিগবৈ তেলক্ষেত্ৰ বিশ্বৰ আটাইতকৈ পুৰণি নিৰন্তৰ উৎপাদনশীল তেলক্ষেত্ৰ।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    {
      question: "The Jallianwala Bagh massacre took place on which date?\nজালিয়ানৱালাবাগ হত্যাকাণ্ড কোন তাৰিখে সংঘটিত হৈছিল?",
      options: [
        '13 April 1919 / ১৩ এপ্ৰিল ১৯১৯',
        '13 April 1929 / ১৩ এপ্ৰিল ১৯২৯',
        '8 April 1919 / ৮ এপ্ৰিল ১৯১৯',
        '1 May 1919 / ১ মে’ ১৯১৯',
      ],
      correctAnswerIndex: 0,
      explanation: "On 13 April 1919 (Baisakhi day), Brigadier-General Reginald Dyer ordered troops to fire on an unarmed crowd at Jallianwala Bagh in Amritsar, killing hundreds and wounding thousands.\n১৩ এপ্ৰিল ১৯১৯ত (বৈশাখী দিৱস) ব্ৰিগেডিয়াৰ-জেনেৰেল ৰেজিনাল্ড ডায়াৰে অমৃতসৰৰ জালিয়ানৱালাবাগত নিৰস্ত্ৰ জনতাৰ ওপৰত গুলী চলোৱাৰ নিৰ্দেশ দিছিল, শতাধিক লোক নিহত আৰু সহস্ৰাধিক আহত হৈছিল।",
      subjectTopic: 'Modern India',
      marks: 2,
    },
    // --- Assam History (8) ---
    {
      question: "Sukapha founded the Ahom kingdom in which year?\nসুকাফাই কতবাৰত আহোম ৰাজ্য প্ৰতিষ্ঠা কৰিছিল?",
      options: [
        '1228 / ১২২৮',
        '1248 / ১২৪৮',
        '1253 / ১২৫৩',
        '1268 / ১২৬৮',
      ],
      correctAnswerIndex: 0,
      explanation: "Chaolung Sukapha, a Tai prince from Mong Mao, crossed the Patkai Hills and established the Ahom kingdom at Charaideo in 1228, unifying the Brahmaputra Valley.\nচাওলুং সুকাফা, মং মাওৰ টাই ৰাজকুমাৰে পাটকাই পাহাৰ পাৰ হৈ ১২২৮ত চৰাইদেউত আহোম ৰাজ্য প্ৰতিষ্ঠা কৰিছিল, ব্ৰহ্মপুত্ৰ উপত্যকা একত্ৰিত কৰি।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "The first capital of the Ahom kingdom was at?\nআহোম ৰাজ্যৰ প্ৰথম ৰাজধানী ক’ত আছিল?",
      options: [
        'Sivasagar / শিৱসাগৰ',
        'Garhgaon / গড়গাঁও',
        'Charaideo / চৰাইদেউ',
        'Jorhat / যোৰহাট',
      ],
      correctAnswerIndex: 2,
      explanation: "Charaideo, established by Sukapha in 1228, was the first capital of the Ahom kingdom; it is famous for the maidams (royal burial mounds) and was inscribed as a UNESCO World Heritage Site in 2024.\nসুকাফাই ১২২৮ত প্ৰতিষ্ঠা কৰা চৰাইদেউ আহোম ৰাজ্যৰ প্ৰথম ৰাজধানী আছিল; ই মৈদাম (ৰাজকীয় সমাধি)ৰ বাবে বিখ্যাত আৰু ২০২৪ত ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ হিচাপে স্বীকৃত।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "The Battle of Saraighat was fought in which year?\nসৰাইঘাটৰ যুদ্ধ কতবাৰত সংঘটিত হৈছিল?",
      options: [
        '1669 / ১৬৬৯',
        '1670 / ১৬৭০',
        '1671 / ১৬৭১',
        '1672 / ১৬৭২',
      ],
      correctAnswerIndex: 2,
      explanation: "The Battle of Saraighat was fought in March 1671 on the Brahmaputra at Saraighat near Guwahati, where the Ahom army under Lachit Borphukan defeated the Mughal forces led by Raja Ram Singh I of Amber.\nসৰাইঘাটৰ যুদ্ধ মাৰ্চ ১৬৭১ত গুৱাহাটীৰ ওচৰৰ সৰাইঘাটত ব্ৰহ্মপুত্ৰত সংঘটিত হৈছিল, য’ত লচিত বৰফুকনৰ নেতৃত্বাধীন আহোম সেনাই আম্বেৰৰ ৰাজা ৰাম সিং প্ৰথমৰ নেতৃত্঵াধীন মোগল সেনাক পৰাস্ত কৰিছিল।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "Who was the Ahom general at the Battle of Saraighat?\nসৰাইঘাটৰ যুদ্ধত আহোম সেনাপতি কোন আছিল?",
      options: [
        'Lachit Borphukan / লচিত বৰফুকন',
        'Momai Tamuli Borbarua / মোমাই তামুলী বৰবৰুৱা',
        'Atan Burhagohain / আতন বুঢ়াগোহাঁই',
        'Gadadhar Singha / গদাধৰ সিংহ',
      ],
      correctAnswerIndex: 0,
      explanation: "Lachit Borphukan was the Ahom general who decisively defeated the Mughal navy at Saraighat in 1671; India's national defence academy's best cadet gold medal is named after him.\nলচিত বৰফুকন আহোম সেনাপতি আছিল যিয়ে ১৬৭১ত সৰাইঘাটত মোগল নৌসেনাক সিদ্ধান্তমূলকভাৱে পৰাস্ত কৰিছিল; ভাৰতৰ ৰাষ্ট্ৰীয় প্ৰতিৰক্ষা একাডেমীৰ শ্ৰেষ্ঠ কেডেট সোণৰ পদক তেওঁৰ নামেৰে নামাকৰণ কৰা হৈছে।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "The Moamoria rebellion broke out in which year?\nমোৱামৰীয়া বিদ্ৰোহ কতবাৰত আৰম্ভ হৈছিল?",
      options: [
        '1769 / ১৭৬৯',
        '1789 / ১৭৮৯',
        '1805 / ১৮০৫',
        '1826 / ১৮২৬',
      ],
      correctAnswerIndex: 0,
      explanation: "The Moamoria rebellion, a conflict between the Ahom kingdom and the Moamoria Vaishnavite satras, began in 1769 under the leadership of Mohanmala and severely weakened the Ahom kingdom.\nআহোম ৰাজ্য আৰু মোৱামৰীয়া বৈষ্ণৱ সত্ৰৰ মাজত সংঘাত মোৱামৰীয়া বিদ্ৰোহ ১৭৬৯ত মোহনমলাৰ নেতৃত্বত আৰম্ভ হৈছিল আৰু আহোম ৰাজ্যক গুৰুতৰভাৱে দুৰ্বল কৰিছিল।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "Who was the founder of the Koch dynasty?\nকোচ বংশৰ প্ৰতিষ্ঠাপক কোন আছিল?",
      options: [
        'Biswa Singha / বিশ্ব সিংহ',
        'Naranarayana / নৰনাৰায়ণ',
        'Chilarai / চিলাৰায়',
        'Raghudev / ৰঘুদেৱ',
      ],
      correctAnswerIndex: 0,
      explanation: "Biswa Singha (Viswa Singha) founded the Koch dynasty in 1515 CE, unifying the Koch tribes of the Kamata region and establishing the capital at Hingulavas (Koch Bihar).\nবিশ্ব সিংহই ১৫১৫ খ্ৰী:ত কোচ বংশ প্ৰতিষ্ঠা কৰিছিল, কামতা অঞ্চলৰ কোচ জনজাতিসমূহ একত্ৰিত কৰি ৰাজধানী হিংগুলাভাসত (কোচ বিহাৰ) স্থাপন কৰিছিল।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "Chilarai was the brother and general of which Koch king?\nচিলাৰায় কোন কোচ ৰজাৰ ভাতৃ আৰু সেনাপতি আছিল?",
      options: [
        'Biswa Singha / বিশ্ব সিংহ',
        'Naranarayana / নৰনাৰায়ণ',
        'Raghudev / ৰঘুদেৱ',
        'Parikshit Narayan / পৰীক্ষিত নাৰায়ণ',
      ],
      correctAnswerIndex: 1,
      explanation: "Chilarai (Shukladhwaj) was the younger brother and commander-in-chief of Koch king Naranarayana (reigned 1540–1586); his military expeditions extended Koch influence over a vast area.\nচিলাৰায় (শুক্লধ্বজ) কোচ ৰজা নৰনাৰায়ণৰ (শাসনকাল ১৫৪০–১৫৮৬) সৰু ভাতৃ আৰু সেনাপতি আছিল; তেওঁৰ সামৰিক অভিযানে কোচ প্ৰভাৱ বিশাল অঞ্চলত বিস্তাৰ কৰিছিল।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    {
      question: "The Kamarupa king Bhaskaravarman was a contemporary of which emperor?\nকামৰূপৰ ৰজা ভাস্কৰবৰ্মন কোন সম্ৰাটৰ সমসাময়িক আছিল?",
      options: [
        'Samudragupta / সমুদ্ৰগুপ্ত',
        'Harshavardhana / হৰ্ষবৰ্ধন',
        'Pulakeshin II / দ্বিতীয় পুলকেশীন',
        'Rajendra Chola I / প্ৰথম ৰাজেন্দ্ৰ চোল',
      ],
      correctAnswerIndex: 1,
      explanation: "Bhaskaravarman (reigned c. 600–650 CE), the last great ruler of the Varman dynasty of Kamarupa, was a contemporary and ally of Emperor Harshavardhana of Kanauj; Hiuen Tsang visited his court.\nকামৰূপৰ বৰ্মন বংশৰ শেষ শ্ৰেষ্ঠ শাসক ভাস্কৰবৰ্মন (শাসনকাল আনুমানিক ৬০০–৬৫০ খ্ৰী:) কনৌজৰ সম্ৰাট হৰ্ষবৰ্ধনৰ সমসাময়িক আৰু মিত্ৰ আছিল; হিউয়েন চাং তেওঁৰ দৰবাৰলৈ আহিছিল।",
      subjectTopic: 'Assam History',
      marks: 2,
    },
    // --- Freedom Movement (8) ---
    {
      question: "Kanaklata Barua was martyred during which movement?\nকনকলতা বৰুৱা কোন আন্দোলনত শ্বহীদ হৈছিল?",
      options: [
        'Quit India Movement / ভাৰত ত্যাগ আন্দোলন',
        'Non-Cooperation Movement / অসহযোগ আন্দোলন',
        'Civil Disobedience Movement / অসামৰিক অবাধ আন্দোলন',
        'Swadeshi Movement / স্বদেশী আন্দোলন',
      ],
      correctAnswerIndex: 0,
      explanation: "Kanaklata Barua, a 17-year-old girl from Gohpur, was shot dead on 20 September 1942 while leading a procession to hoist the tricolour at the Gohpur police station during the Quit India Movement.\nগোহপুৰৰ ১৭ বছৰীয়া ছোৱালী কনকলতা বৰুৱাক ভাৰত ত্যাগ আন্দোলনৰ সময়ত ২০ ছেপ্তেম্বৰ ১৯৪২ত গোহপুৰ থানাত ত্ৰিৰংগা উত্তোলন কৰিবলৈ যোৱা শোভাযাত্ৰাৰ নেতৃত্ব দিওঁতে গুলীয়াই হত্যা কৰা হৈছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Kushal Konwar was hanged in 1943 in connection with which event?\nকুশল কোঁৱৰক ১৯৪৩ত কোন ঘটনাৰ সৈতে জড়িত কৰি ফাঁচী দিয়া হৈছিল?",
      options: [
        'Salt Satyagraha / লৱণ সত্যাগ্ৰহ',
        'Train derailment at Sarupathar / সৰুপাথাৰত ট্ৰেইন দুৰ্ঘটনা',
        'Battle of Saraighat / সৰাইঘাটৰ যুদ্ধ',
        'Sepoy Mutiny / চিপাহী বিদ্ৰোহ',
      ],
      correctAnswerIndex: 1,
      explanation: "Kushal Konwar, a freedom fighter from Golaghat, was falsely implicated and hanged on 15 June 1943 for the Sarupathar train derailment (10 October 1942) in which British soldiers died during the Quit India Movement.\nগোলাঘাটৰ স্বাধীনতা সংগ্ৰামী কুশল কোঁৱৰক সৰুপাথাৰ ট্ৰেইন দুৰ্ঘটনাৰ (১০ অক্টোবৰ ১৯৪২) বাবে য’ত ব্ৰিটিছ সৈন্য মৃত্যু হৈছিল, ভাৰত ত্যাগ আন্দোলনৰ সময়ত মিছাকৈ জড়িত কৰি ১৫ জুন ১৯৪৩ত ফাঁচী দিয়া হৈছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Who was the first Chief Minister of Assam after independence?\nস্বাধীনতাৰ পিছত অসমৰ প্ৰথমগৰাকী মুখ্যমন্ত্ৰী কোন আছিল?",
      options: [
        'Bishnuram Medhi / বিষ্ণুৰাম মেধি',
        'Fakhruddin Ali Ahmed / ফখৰুদ্দিন আলি আহমেদ',
        'Gopinath Bordoloi / গোপীনাথ বৰদলৈ',
        'Sarat Chandra Sinha / শৰত চন্দ্ৰ সিনহা',
      ],
      correctAnswerIndex: 2,
      explanation: "Gopinath Bordoloi became the first Chief Minister of Assam after independence on 15 August 1947, having earlier served as Premier from 1946; he is credited with saving Assam from the Cabinet Mission Grouping plan.\nগোপীনাথ বৰদলৈ ১৫ আগষ্ট ১৯৪৭ত স্বাধীনতাৰ পিছত অসমৰ প্ৰথম মুখ্যমন্ত্ৰী হৈছিল, আগতে ১৯৪৬ৰ পৰা প্ৰিমিয়াৰ হিচাপে কাৰ্য্যনিৰ্বাহ কৰিছিল; তেওঁক কেবিনেট মিছন গ্ৰুপিং পৰিকল্পনাৰ পৰা অসমক ৰক্ষা কৰাৰ বাবে গণ্য কৰা হয়।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Who led the Non-Cooperation Movement in Assam?\nঅসমত অসহযোগ আন্দোলন কোনে নেতৃত্ব দিছিল?",
      options: [
        'Chandraprabha Saikiani / চন্দ্ৰপ্ৰভা শইকীয়ানী',
        'Kanaklata Barua / কনকলতা বৰুৱা',
        'Kushal Konwar / কুশল কোঁৱৰ',
        'Tarun Ram Phukan / তৰুণ ৰাম ফুকন',
      ],
      correctAnswerIndex: 3,
      explanation: "Tarun Ram Phukan, a prominent Assamese freedom fighter and president of the Assam Pradesh Congress Committee, led the Non-Cooperation Movement in Assam (1920–1922) and was later arrested.\nঅসম প্ৰদেশ কংগ্ৰেছ সমিতিৰ সভাপতি আৰু শ্ৰেষ্ঠ অসমীয়া স্বাধীনতা সংগ্ৰামী তৰুণ ৰাম ফুকনে অসমত অসহযোগ আন্দোলন (১৯২০–১৯২২)ৰ নেতৃত্ব দিছিল আৰু পিছত গ্ৰেপ্তাৰ হৈছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Chandraprabha Saikiani was a famous Assamese freedom fighter and pioneer of which movement?\nচন্দ্ৰপ্ৰভা শইকীয়ানী এগৰাকী বিখ্যাত অসমীয়া স্বাধীনতা সংগ্ৰামী আৰু কোন আন্দোলনৰ অগ্ৰগামী আছিল?",
      options: [
        "Women's rights movement / মহিলা অধিকাৰ আন্দোলন",
        'Tea labour movement / চাহ শ্ৰমিক আন্দোলন',
        'Peasant movement / কৃষক আন্দোলন',
        'Tribal movement / জনজাতীয় আন্দোলন',
      ],
      correctAnswerIndex: 0,
      explanation: "Chandraprabha Saikiani (1901–1972) was a pioneer of the women's rights movement in Assam; she founded the Assam Pradeshik Mahila Samiti in 1926 and was the first woman to address the Assam Sahitya Sabha session.\nচন্দ্ৰপ্ৰভা শইকীয়ানী (১৯০১–১৯৭২) অসমত মহিলা অধিকাৰ আন্দোলনৰ অগ্ৰগামী আছিল; তেওঁ ১৯২৬ত অসম প্ৰাদেশিক মহিলা সমিতি প্ৰতিষ্ঠা কৰিছিল আৰু অসম সাহিত্য সভাৰ অধিবেশনক সম্বোধন কৰা প্ৰথমগৰাকী মহিলা আছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Ambikagiri Rai Choudhury was popularly known by which title?\nঅম্বিকাগিৰি ৰায়চৌধুৰীক জনপ্ৰিয়ভাৱে কোন উপাধিৰে জনা গৈছিল?",
      options: [
        'Asom Ratna / অসম ৰত্ন',
        'Asom Kesari / অসম কেশৰী',
        'Sahityarathi / সাহিত্যৰথী',
        'Kalaguru / কলাগুৰু',
      ],
      correctAnswerIndex: 1,
      explanation: "Ambikagiri Rai Choudhury (1885–1967), an Assamese poet, freedom fighter and founder of the Assam Sangrakshini Sabha, was popularly known as 'Asom Kesari' (Lion of Assam) for his fiery patriotism.\nঅসমীয়া কবি, স্বাধীনতা সংগ্ৰামী আৰু অসম সংৰক্ষিণী সভাৰ প্ৰতিষ্ঠাপক অম্বিকাগিৰি ৰায়চৌধুৰীক (১৮৮৫–১৯৬৭) তেওঁৰ জ্বলন্ত দেশপ্ৰেমৰ বাবে জনপ্ৰিয়ভাৱে 'অসম কেশৰী' (অসমৰ সিংহ) বুলি জনা গৈছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "Bishnu Prasad Rabha was popularly known by which title?\nবিষ্ণুপ্ৰসাদ ৰাভাক জনপ্ৰিয়ভাৱে কোন উপাধিৰে জনা গৈছিল?",
      options: [
        'Sahityarathi / সাহিত্যৰথী',
        'Natya Pragya / নাট্য প্ৰজ্ঞা',
        'Kalaguru / কলাগুৰু',
        'Sangeet Samrat / সংগীত সম্ৰাট',
      ],
      correctAnswerIndex: 2,
      explanation: "Bishnu Prasad Rabha (1909–1969), a multi-faceted Assamese artist, composer, dancer, writer and revolutionary, was popularly known as 'Kalaguru' (Master of Arts); his song 'Bilote Halise' is iconic.\nবহুমুখী অসমীয়া শিল্পী, সুৰকাৰ, নৰ্তক, লেখক আৰু বিপ্লৱী বিষ্ণুপ্ৰসাদ ৰাভাক (১৯০৯–১৯৬৯) জনপ্ৰিয়ভাৱে 'কলাগুৰু' বুলি জনা গৈছিল; তেওঁৰ 'বিলতে হালিছে' গীতটো চিৰস্মৰণীয়।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
    {
      question: "The Assam Pradesh Congress Committee was formed in which year?\nঅসম প্ৰদেশ কংগ্ৰেছ সমিতি কতবাৰত গঠন কৰা হৈছিল?",
      options: [
        '1918 / ১৯১৮',
        '1919 / ১৯১৯',
        '1920 / ১৯২০',
        '1921 / ১৯২১',
      ],
      correctAnswerIndex: 3,
      explanation: "The Assam Pradesh Congress Committee (APCC) was formed in June 1921 after the Nagpur session of the Indian National Congress (December 1920) reorganised provincial committees on linguistic basis.\nঅসম প্ৰদেশ কংগ্ৰেছ সমিতি (APCC) ভাৰতীয় জাতীয় কংগ্ৰেছৰ নাগপুৰ অধিবেশন (ডিচেম্বৰ ১৯২০)ৰ পিছত ভাষিক ভিত্তিত প্ৰাদেশিক সমিতি পুনৰ্গঠনৰ পিছত জুন ১৯২১ত গঠন কৰা হৈছিল।",
      subjectTopic: 'Freedom Movement',
      marks: 2,
    },
  ],
};
