// =============================================================================
// ExamVault — APSC (Assam Public Service Commission) GEOGRAPHY
// Bilingual question pool — apsc-geography (40 items)
//
// Format (CRITICAL — every field is bilingual EN + অসমীয়া):
//   question  -> "English\nঅসমীয়া"
//   option    -> "English / অসমীয়া"
//   expl      -> "English\nঅসমীয়া"
//
// apsc-geography : 40 questions — Physical Geography, Indian Geography,
//                  Assam Geography, Economic Geography
//
// correctAnswerIndex is distributed evenly (10 × 0, 10 × 1, 10 × 2, 10 × 3).
// =============================================================================
import type { QuestionPoolMap } from './structure';

export const APSC_POOLS_GEO: QuestionPoolMap = {
  'apsc-geography': [
    // --- Physical Geography (12) ---
    {
      question: "From which glacier does the Brahmaputra river originate?\nব্ৰহ্মপুত্ৰ নদী কোন হিমবাহৰ পৰা উৎপন্ন হৈছে?",
      options: [
        'Chemayungdung Glacier / চেমায়ুংডুং হিমবাহ',
        'Gangotri Glacier / গংগোত্ৰী হিমবাহ',
        'Siachen Glacier / চিয়াচেন হিমবাহ',
        'Zemu Glacier / জেমু হিমবাহ',
      ],
      correctAnswerIndex: 0,
      explanation: "The Brahmaputra originates from the Chemayungdung glacier in the Kailash range of the Himalayas in Tibet at an elevation of about 5,300 m.\nব্ৰহ্মপুত্ৰ নদী তিব্বতৰ হিমালয়ৰ কৈলাশ শৃংগখলৰ চেমায়ুংডুং হিমবাহৰ পৰা প্ৰায় ৫,৩০০ মিটাৰ উচ্চতাত উৎপন্ন হৈছে।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "By what name is the Brahmaputra known in Tibet?\nতিব্বতত ব্ৰহ্মপুত্ৰ নদী কি নামেৰে জনাজাত?",
      options: [
        'Jamuna / যমুনা',
        'Yarlung Tsangpo / য়াৰলুং ছাংপো',
        'Dihang / দিহাং',
        'Padma / পদ্মা',
      ],
      correctAnswerIndex: 1,
      explanation: "In Tibet the Brahmaputra is known as Yarlung Tsangpo; it is called Dihang when it enters Arunachal Pradesh, Jamuna in Bangladesh and joins the Padma.\nতিব্বতত ব্ৰহ্মপুত্ৰক য়াৰলুং ছাংপো বুলি কোৱা হয়; অৰুণাচলত দিহাং, বাংলাদেশত যমুনা আৰু পদ্মাৰ লগত মিলিত হয়।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "Which is the largest tributary of the Brahmaputra?\nব্ৰহ্মপুত্ৰৰ আটাইতকৈ ডাঙৰ উপনদী কোন?",
      options: [
        'Kopili / কপিলী',
        'Manas / মানস',
        'Subansiri / সুৱনশিৰি',
        'Dhansiri / ধনশিৰি',
      ],
      correctAnswerIndex: 2,
      explanation: "The Subansiri is the largest tributary of the Brahmaputra, joining it on the north bank in the Lakhimpur district of Assam.\nসুৱনশিৰি ব্ৰহ্মপুত্ৰৰ আটাইতকৈ ডাঙৰ উপনদী, অসমৰ লখিমপুৰ জিলাত ব্ৰহ্মপুত্ৰৰ উত্তৰ পাৰত মিলিত হয়।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "The Manas river flows through which neighbouring country before entering Assam?\nমানস নদী অসমত প্ৰৱেশ কৰাৰ আগতে কোন চুবুৰীয়া দেশৰ মাজেদি বৈ যায়?",
      options: [
        'Nepal / নেপাল',
        'Bhutan / ভূটান',
        'Bangladesh / বাংলাদেশ',
        'Myanmar / ম্যানমাৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "The Manas river originates in Bhutan and flows through it before entering Assam, where it joins the Brahmaputra near Jogighopa.\nমানস নদী ভূটানত উৎপন্ন হৈ অসমত প্ৰৱেশ কৰে আৰু যোগীঘোপাৰ ওচৰত ব্ৰহ্মপুত্ৰৰ লগত মিলিত হয়।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "On which bank of the Brahmaputra does the Kopili river join?\nকপিলী নদী ব্ৰহ্মপুত্ৰৰ কোন পাৰত মিলিত হয়?",
      options: [
        'South bank / দক্ষিণ পাৰ',
        'North bank / উত্তৰ পাৰ',
        'East bank / পূব পাৰ',
        'West bank / পশ্চিম পাৰ',
      ],
      correctAnswerIndex: 0,
      explanation: "The Kopili is a major south-bank tributary of the Brahmaputra. The Kopili Hydro Electric Project is located on this river.\nকপিলী ব্ৰহ্মপুত্ৰৰ এটা প্ৰধান দক্ষিণ-পাৰৰ উপনদী। কপিলী জলবিদ্যুৎ প্ৰকল্প এই নদীৰ ওপৰত অৱস্থিত।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "The Dhansiri river flows along which national park of Assam?\nধনশিৰি নদী অসমৰ কোন ৰাষ্ট্ৰীয় উদ্যানৰ কাষেদি বৈ গৈছে?",
      options: [
        'Manas National Park / মানস ৰাষ্ট্ৰীয় উদ্যান',
        'Kaziranga National Park / কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান',
        'Orang National Park / ওৰাং ৰাষ্ট্ৰীয় উদ্যান',
        'Dibru-Saikhowa National Park / দিব্ৰু-চৈকোৱা ৰাষ্ট্ৰীয় উদ্যান',
      ],
      correctAnswerIndex: 1,
      explanation: "The Dhansiri river forms the eastern boundary of Kaziranga National Park and is an important water source for the park's wildlife.\nধনশিৰি নদী কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যানৰ পূব সীমা গঠন কৰে আৰু ই উদ্যানৰ বন্যপ্ৰাণীৰ বাবে গুৰুত্বপূৰ্ণ জল উৎস।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "The Burhi Dihing river flows through which districts of Assam?\nবুঢ়ী দিহিং নদী অসমৰ কোনখন জিলাৰ মাজেদি বৈ গৈছে?",
      options: [
        'Dhubri and Goalpara / ধুবুৰী আৰু গোৱালপাৰা',
        'Nagaon and Morigaon / নগাঁও আৰু মৰিগাঁও',
        'Dibrugarh and Tinsukia / ডিব্ৰুগড় আৰু তিনিচুকীয়া',
        'Cachar and Karimganj / কাছাৰ আৰু কৰিমগঞ্জ',
      ],
      correctAnswerIndex: 2,
      explanation: "The Burhi Dihing is a south-bank tributary of the Brahmaputra flowing through the Dibrugarh and Tinsukia districts, where the Namrup thermal power station is located.\nবুঢ়ী দিহিং ব্ৰহ্মপুত্ৰৰ দক্ষিণ-পাৰৰ উপনদী, ডিব্ৰুগড় আৰু তিনিচুকীয়া জিলাৰ মাজেদি বৈ যায়; নামৰূপ তাপবিদ্যুৎ কেন্দ্ৰ ইয়াতেই অৱস্থিত।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "Which river is popularly known as the 'Sorrow of Assam'?\nকোন নদীক 'অসমৰ দুখদায়ক নদী' বুলি কোৱা হয়?",
      options: [
        'Subansiri / সুৱনশিৰি',
        'Kopili / কপিলী',
        'Dhansiri / ধনশিৰি',
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
      ],
      correctAnswerIndex: 3,
      explanation: "The Brahmaputra is called the 'Sorrow of Assam' because of the devastating floods it causes almost every year during the monsoon season.\nবাৰিষা কালত ব্ৰহ্মপুত্ৰই প্ৰায় প্ৰতি বছৰে সৃষ্টি কৰা বিধ্বংসী বানপানীৰ বাবে ইয়াক 'অসমৰ দুখদায়ক নদী' বুলি কোৱা হয়।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "During which month does the southwest monsoon generally arrive in Assam?\nদক্ষিণ-পশ্চিম মৌচুম সাধাৰণতে অসমত কোন মাহত আহে?",
      options: [
        'October / অক্টোবৰ',
        'April / এপ্ৰিল',
        'August / আগষ্ট',
        'June / জুন',
      ],
      correctAnswerIndex: 3,
      explanation: "The southwest monsoon normally reaches Assam by the first week of June, bringing the bulk of the state's annual rainfall.\nদক্ষিণ-পশ্চিম মৌচুম সাধাৰণতে জুন মাহৰ প্ৰথম সপ্তাহত অসমত উপনীত হয় আৰু ৰাজ্যখনৰ বাৰ্ষিক বৰষুণৰ সিংহভাগ এই সময়ত হয়।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "Which place in Meghalaya is recognised as the wettest place on Earth?\nমেঘালয়ৰ কোন ঠাইক পৃথিৱীৰ আটাইতকৈ সেঁজাঊ ঠাই হিচাপে স্বীকৃতি দিয়া হৈছে?",
      options: [
        'Cherrapunji / চেৰাপুঞ্জি',
        'Mawsynram / মাউচিন্ৰাম',
        'Shillong / শ্বিলং',
        'Tura / তুৰা',
      ],
      correctAnswerIndex: 1,
      explanation: "Mawsynram in the East Khasi Hills of Meghalaya receives the highest average annual rainfall in the world, making it the wettest place on Earth.\nমেঘালয়ৰ পূব খাচি পাহাৰ জিলাৰ মাউচিন্ৰামে পৃথিৱীৰ ভিতৰতে সৰ্বাধিক গড় বাৰ্ষিক বৰষুণ লাভ কৰে, যাৰবাবে ই পৃথিৱীৰ আটাইতকৈ সেঁজাঊ ঠাই।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "The Himalayas were formed by the collision of which two tectonic plates?\nহিমালয় পৰ্বতমালা কোন দুটা টেকটনিক প্লেটৰ সংঘৰ্ষৰ ফলত গঠিত হৈছিল?",
      options: [
        'African and Eurasian / আফ্ৰিকান আৰু ইউৰেচিয়ান',
        'Pacific and Indian / পেচিফিক আৰু ইণ্ডিয়ান',
        'Indian and Eurasian / ইণ্ডিয়ান আৰু ইউৰেচিয়ান',
        'Antarctic and Indian / এণ্টাৰ্কটিক আৰু ইণ্ডিয়ান',
      ],
      correctAnswerIndex: 2,
      explanation: "The Himalayas were formed by the ongoing collision of the Indian Plate with the Eurasian Plate, beginning about 50 million years ago.\nহিমালয় পৰ্বতমালা প্ৰায় ৫ কোটি বছৰ আগতে আৰম্ভ হোৱা ইণ্ডিয়ান প্লেট আৰু ইউৰেচিয়ান প্লেটৰ সংঘৰ্ষৰ ফলত গঠিত হৈছিল।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },
    {
      question: "What is the Brahmaputra called in Bangladesh?\nবাংলাদেশত ব্ৰহ্মপুত্ৰক কি বুলি কোৱা হয়?",
      options: [
        'Tsangpo / ছাংপো',
        'Padma / পদ্মা',
        'Dihang / দিহাং',
        'Jamuna / যমুনা',
      ],
      correctAnswerIndex: 3,
      explanation: "In Bangladesh the Brahmaputra is known as the Jamuna; it later merges with the Padma (the main stream of the Ganga) before flowing into the Bay of Bengal.\nবাংলাদেশত ব্ৰহ্মপুত্ৰক যমুনা বুলি কোৱা হয়; পিছত ই পদ্মাৰ (গংগাৰ মুখ্য ধাৰা) সৈতে মিলিত হয় আৰু বংগোপসাগৰত পৰে।",
      subjectTopic: 'Physical Geography',
      marks: 2,
    },

    // --- Indian Geography (10) ---
    {
      question: "Which is the highest peak of the Himalayan range?\nহিমালয় পৰ্বতমালাৰ আটাইতকৈ ওখ শৃংগ কোন?",
      options: [
        'Mount Everest / মাউণ্ট এভাৰেষ্ট',
        'Kanchenjunga / কাঞ্চনজংঘা',
        'K2 / কে-২',
        'Nanda Devi / নন্দা দেৱী',
      ],
      correctAnswerIndex: 0,
      explanation: "Mount Everest (8,849 m) is the highest peak of the Himalayas and the world; Kanchenjunga is the third-highest and the highest peak fully within India.\nমাউণ্ট এভাৰেষ্ট (৮,৮৪৯ মি) হিমালয়ৰ আৰু পৃথিৱীৰ আটাইতকৈ ওখ শৃংগ; কাঞ্চনজংঘা তৃতীয় ওখ আৰু ভাৰতৰ ভিতৰতে আটাইতকৈ ওখ।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "The Ganga river originates from which glacier?\nগংগা নদী কোন হিমবাহৰ পৰা উৎপন্ন হয়?",
      options: [
        'Siachen Glacier / চিয়াচেন হিমবাহ',
        'Gangotri Glacier / গংগোত্ৰী হিমবাহ',
        'Milam Glacier / মিলাম হিমবাহ',
        'Pindari Glacier / পিন্ডাৰী হিমবাহ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Ganga originates as the Bhagirathi from the Gangotri glacier in Uttarakhand; it takes the name Ganga after the confluence of Bhagirathi and Alaknanda at Devprayag.\nগংগা উত্তৰাখণ্ডৰ গংগোত্ৰী হিমবাহৰ পৰা ভাগীৰথী হিচাপে উৎপন্ন হয়; দেৱপ্ৰয়াগত ভাগীৰথী আৰু অলকানন্দাৰ সংগমৰ পিছত গংগা নাম লয়।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "The Western Ghats are also known by which name?\nপশ্চিম ঘাট পৰ্বতমালা আন কি নামেৰে জনাজাত?",
      options: [
        'Aravallis / আৰৱলী',
        'Vindhyas / বিন্ধ্য',
        'Satpuras / সতপুৰা',
        'Sahyadri / সহ্যাদ্ৰি',
      ],
      correctAnswerIndex: 3,
      explanation: "The Western Ghats, a UNESCO World Heritage Site, are also called the Sahyadri range and stretch along the western coast of India.\nপশ্চিম ঘাট, যিটো ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ, সহ্যাদ্ৰি পৰ্বতমালা নামেৰেও জনাজাত আৰু ভাৰতৰ পশ্চিম উপকূলৰ লগত বিস্তৃত।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "Which is the largest plateau in India?\nভাৰতৰ আটাইতকৈ ডাঙৰ মালভূমি কোন?",
      options: [
        'Malwa Plateau / মালৱা মালভূমি',
        'Chota Nagpur Plateau / ছোটনাগপুৰ মালভূমি',
        'Meghalaya Plateau / মেঘালয় মালভূমি',
        'Deccan Plateau / ডেকান মালভূমি',
      ],
      correctAnswerIndex: 3,
      explanation: "The Deccan Plateau is the largest plateau in India, covering most of southern India between the Western and Eastern Ghats.\nডেকান মালভূমি ভাৰতৰ আটাইতকৈ ডাঙৰ মালভূমি, যি পশ্চিম আৰু পূব ঘাটৰ মাজৰ দক্ষিণ ভাৰতৰ বেছিভাগ অংশ আগুৰি আছে।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "Through how many Indian states does the Tropic of Cancer pass?\nকৰ্কটৰেখা কিমানখন ভাৰতীয় ৰাজ্যৰ মাজেদি পাৰ হৈ যায়?",
      options: [
        '8 states / ৮খন ৰাজ্য',
        '6 states / ৬খন ৰাজ্য',
        '5 states / ৫খন ৰাজ্য',
        '10 states / ১০খন ৰাজ্য',
      ],
      correctAnswerIndex: 0,
      explanation: "The Tropic of Cancer (23.5°N) passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram.\nকৰ্কটৰেখা (২৩.৫° উত্তৰ) ৮খন ভাৰতীয় ৰাজ্যৰ মাজেদি পাৰ হয়: গুজৰাট, ৰাজস্থান, মধ্যপ্ৰদেশ, ছত্তীসগঢ়, ঝাৰখণ্ড, পশ্চিমবংগ, ত্ৰিপুৰা আৰু মিজোৰাম।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "Which is the longest river entirely within India?\nসম্পূৰ্ণৰূপে ভাৰতৰ ভিতৰতে থকা আটাইতকৈ দীঘল নদী কোন?",
      options: [
        'Godavari / গোদাৱৰী',
        'Ganga / গংগা',
        'Yamuna / যমুনা',
        'Narmada / নৰ্মদা',
      ],
      correctAnswerIndex: 1,
      explanation: "The Ganga (about 2,525 km) is the longest river that flows entirely within India; the Indus and Brahmaputra are longer but extend beyond India's borders.\nগংগা (প্ৰায় ২,৫২৫ কিমি) সম্পূৰ্ণৰূপে ভাৰতৰ ভিতৰতে বৈ যোৱা আটাইতকৈ দীঘল নদী; সিন্ধু আৰু ব্ৰহ্মপুত্ৰ অধিক দীঘল কিন্তু ভাৰতৰ সীমাৰ বাহিৰলৈকে বিস্তৃত।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "The Thar Desert is located mainly in which Indian state?\nথৰ মৰুভূমি মূলতঃ ভাৰতৰ কোন ৰাজ্যত অৱস্থিত?",
      options: [
        'Gujarat / গুজৰাট',
        'Punjab / পঞ্জাব',
        'Rajasthan / ৰাজস্থান',
        'Haryana / হৰিয়ানা',
      ],
      correctAnswerIndex: 2,
      explanation: "The Thar Desert, also known as the Great Indian Desert, lies mainly in the state of Rajasthan and extends into parts of Gujarat, Punjab and Haryana.\nথৰ মৰুভূমি, যাক গ্ৰেট ইণ্ডিয়ান ডেজাৰ্ট বুলিও কোৱা হয়, মূলতঃ ৰাজস্থান ৰাজ্যত অৱস্থিত আৰু গুজৰাট, পঞ্জাব আৰু হৰিয়ানাৰ কিছু অংশলৈকে বিস্তৃত।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "Which strait separates India from Sri Lanka?\nকোন প্ৰণালীয়ে ভাৰতক শ্রীলংকাৰ পৰা পৃথক কৰে?",
      options: [
        'Strait of Hormuz / হৰমুজ প্ৰণালী',
        'Bering Strait / বেৰিং প্ৰণালী',
        'Palk Strait / পাক প্ৰণালী',
        'Bass Strait / বাছ প্ৰণালী',
      ],
      correctAnswerIndex: 3,
      explanation: "The Palk Strait separates the southern coast of India (Tamil Nadu) from the northern coast of Sri Lanka.\nপাক প্ৰণালীয়ে ভাৰতৰ দক্ষিণ উপকূলক (তামিলনাডু) শ্রীলংকাৰ উত্তৰ উপকূলৰ পৰা পৃথক কৰে।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "What is the northernmost range of the Himalayas called?\nহিমালয়ৰ উত্তৰতম শৃংগখলক কি বুলি কোৱা হয়?",
      options: [
        'Himadri / হিমাদ্ৰি',
        'Himachal / হিমাচল',
        'Shivalik / শিৱালিক',
        'Pir Panjal / পীৰ পাঞ্জাল',
      ],
      correctAnswerIndex: 0,
      explanation: "The Himadri (Great or Inner Himalayas) is the northernmost and highest range, with peaks averaging above 6,000 m in elevation.\nহিমাদ্ৰি (গ্ৰেট বা ইনাৰ হিমালয়) উত্তৰতম আৰু আটাইতকৈ ওখ শৃংগখল, যাৰ শৃংগবোৰৰ গড় উচ্চতা ৬,০০০ মিটাৰতকৈ অধিক।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },
    {
      question: "Which river is known as the 'Dakshin Ganga' (Ganga of the South)?\nকোন নদীক 'দক্ষিণ গংগা' বুলি কোৱা হয়?",
      options: [
        'Krishna / কৃষ্ণা',
        'Godavari / গোদাৱৰী',
        'Kaveri / কাৱেৰী',
        'Mahanadi / মহানদী',
      ],
      correctAnswerIndex: 1,
      explanation: "The Godavari, the longest river of peninsular India (about 1,465 km), is called the 'Dakshin Ganga' because of its large drainage basin and cultural importance.\nগোদাৱৰী, দক্ষিণ ভাৰতৰ আটাইতকৈ দীঘল নদী (প্ৰায় ১,৪৬৫ কিমি), ইয়াৰ বৃহৎ নদী অৱবাহিকা আৰু সাংস্কৃতিক গুৰুত্বৰ বাবে 'দক্ষিণ গংগা' বুলি কোৱা হয়।",
      subjectTopic: 'Indian Geography',
      marks: 2,
    },

    // --- Assam Geography (12) ---
    {
      question: "Kaziranga National Park is famous for which of the following?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান তলৰ কোনটোৰ বাবে বিখ্যাত?",
      options: [
        'Bengal tiger / ৰয়েল বেংগল বাঘ',
        'Asian elephant / এছিয়ান হাতী',
        'One-horned rhinoceros / এশিংগীয়া গঁড়',
        'Snow leopard / হিমবাঘ',
      ],
      correctAnswerIndex: 2,
      explanation: "Kaziranga National Park in Assam is world-famous for hosting about two-thirds of the world's population of the Indian one-horned rhinoceros.\nঅসমৰ কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান বিশ্বৰ ভাৰতীয় এশিংগীয়া গঁড়ৰ জনসংখ্যাৰ প্ৰায় দুই-তৃতীয়াংশ বাস কৰাৰ বাবে বিশ্ববিখ্যাত।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "In which year was Kaziranga National Park inscribed as a UNESCO World Heritage Site?\nকাজিৰঙা ৰাষ্ট্ৰীয় উদ্যানক ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ হিচাপে কোন বছৰত স্বীকৃতি দিয়া হৈছিল?",
      options: [
        '1972 / ১৯৭২',
        '1980 / ১৯৮০',
        '1990 / ১৯৯০',
        '1985 / ১৯৮৫',
      ],
      correctAnswerIndex: 3,
      explanation: "Kaziranga was inscribed as a UNESCO World Heritage Site in 1985 for its outstanding natural value and as the habitat of the one-horned rhinoceros.\nএশিংগীয়া গঁড়ৰ বাসস্থান আৰু উৎকৃষ্ট প্ৰাকৃতিক মূল্যৰ বাবে ১৯৮৫ চনত কাজিৰঙাক ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ হিচাপে স্বীকৃতি দিয়া হৈছিল।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Which is recognised as the largest river island in the world?\nবিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপ হিচাপে কোনটো স্বীকৃত?",
      options: [
        'Majuli / মাজুলী',
        'Umananda / উমানন্দ',
        'Havelock / হেভলক',
        'Diu / দিউ',
      ],
      correctAnswerIndex: 0,
      explanation: "Majuli, in the Brahmaputra river in Assam, is recognised by the Guinness World Records as the largest river island in the world.\nঅসমৰ ব্ৰহ্মপুত্ৰ নদীৰ মাজত থকা মাজুলীক গিনিজ ৱৰ্ল্ড ৰেকৰ্ডছে বিশ্বৰ আটাইতকৈ ডাঙৰ নদীদ্বীপ হিচাপে স্বীকৃতি দিছে।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Manas National Park of Assam is located along which river?\nঅসমৰ মানস ৰাষ্ট্ৰীয় উদ্যান কোন নদীৰ কাষেদি অৱস্থিত?",
      options: [
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
        'Manas / মানস',
        'Subansiri / সুৱনশিৰি',
        'Barak / বৰাক',
      ],
      correctAnswerIndex: 1,
      explanation: "Manas National Park lies along the Manas river in the foothills of the Himalayas in western Assam, along the Bhutan border.\nমানস ৰাষ্ট্ৰীয় উদ্যান পশ্চিম অসমৰ হিমালয়ৰ পাদদেশত ভূটান সীমান্তত মানস নদীৰ কাষেদি অৱস্থিত।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Manas National Park was inscribed as a UNESCO World Heritage Site in which year?\nমানস ৰাষ্ট্ৰীয় উদ্যানক কোন বছৰত ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ হিচাপে স্বীকৃতি দিয়া হৈছিল?",
      options: [
        '1992 / ১৯৯২',
        '1999 / ১৯৯৯',
        '1985 / ১৯৮৫',
        '2005 / ২০০৫',
      ],
      correctAnswerIndex: 2,
      explanation: "Manas Wildlife Sanctuary was inscribed as a UNESCO World Heritage Site in 1985; it was briefly placed on the List of World Heritage in Danger from 1992 to 2011.\nমানস বন্যপ্ৰাণী অভয়াৰণ্যক ১৯৮৫ চনত ইউনেস্কো বিশ্ব ঐতিহ্য ক্ষেত্ৰ হিচাপে স্বীকৃতি দিয়া হৈছিল; ১৯৯২ৰ পৰা ২০১১লৈ ই বিপদাপন্ন তালিকাত আছিল।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Orang National Park in Assam is popularly known by which name?\nঅসমৰ ওৰাং ৰাষ্ট্ৰীয় উদ্যান জনপ্ৰিয়ভাৱে কি নামেৰে জনাজাত?",
      options: [
        'Mini Tibet / মিনি তিব্বত',
        'Mini Switzerland / মিনি ছুইজাৰলেণ্ড',
        'Mini Kerala / মিনি কেৰালা',
        'Mini Kaziranga / মিনি কাজিৰঙা',
      ],
      correctAnswerIndex: 3,
      explanation: "Because of its landscape and one-horned rhinoceros population similar to Kaziranga, Orang National Park is called the 'Mini Kaziranga' of Assam.\nকাজিৰঙাৰ দৰে প্ৰাকৃতিক দৃশ্য আৰু এশিংগীয়া গঁড়ৰ জনসংখ্যা থকাৰ বাবে ওৰাং ৰাষ্ট্ৰীয় উদ্যানক অসমৰ 'মিনি কাজিৰঙা' বুলি কোৱা হয়।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Dibru-Saikhowa National Park of Assam is famous for which of the following?\nঅসমৰ দিব্ৰু-চৈকোৱা ৰাষ্ট্ৰীয় উদ্যান তলৰ কোনটোৰ বাবে বিখ্যাত?",
      options: [
        'Feral horses / বন্য ঘোঁৰা',
        'Lions / সিংহ',
        "Wild buffalo herd / বন্য ম'হৰ দল",
        'Asiatic cheetah / এছিয়াটিক চিতা',
      ],
      correctAnswerIndex: 0,
      explanation: "Dibru-Saikhowa National Park, located in Dibrugarh and Tinsukia districts, is well known for its population of feral horses and as a biodiversity hotspot.\nডিব্ৰুগড় আৰু তিনিচুকীয়া জিলাত অৱস্থিত দিব্ৰু-চৈকোৱা ৰাষ্ট্ৰীয় উদ্যান বন্য ঘোঁৰাৰ জনসংখ্যা আৰু জৈৱবৈচিত্ৰ্য কেন্দ্ৰ হিচাপে বিখ্যাত।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "The tea gardens of Upper Assam are mainly concentrated in which districts?\nউজনি অসমৰ চাহবাগিচাবোৰ মূলতঃ কোনখন জিলাত কেন্দ্ৰভূত?",
      options: [
        'Barpeta and Bongaigaon / বৰপেটা আৰু বঙাইগাঁও',
        'Dibrugarh, Jorhat and Tinsukia / ডিব্ৰুগড়, যোৰহাট আৰু তিনিচুকীয়া',
        'Cachar and Hailakandi / কাছাৰ আৰু হাইলাকান্দি',
        'Dhubri and Kokrajhar / ধুবুৰী আৰু কোকৰাঝাৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "Upper Assam districts of Dibrugarh, Jorhat, Tinsukia, Sivasagar and Golaghat form the core of Assam's tea-producing belt and produce some of the finest orthodox teas in the world.\nউজনি অসমৰ ডিব্ৰুগড়, যোৰহাট, তিনিচুকীয়া, শিৱসাগৰ আৰু গোলাঘাট জিলাই অসমৰ চাহ উৎপাদনকাৰী বেল্টৰ মূল গঠন কৰে আৰু বিশ্বৰ কেইটামান শ্ৰেষ্ঠ অৰ্থ'ডক্স চাহ উৎপাদন কৰে।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "The traditional 'Assam-type' house is architecturally designed to withstand which natural hazard?\nপৰম্পৰাগত 'অসমীয়া-ধৰণ'ৰ ঘৰ স্থাপত্যশৈলী কোন প্ৰাকৃতিক বিপদ সহ্য কৰিবলৈ ডিজাইন কৰা হৈছে?",
      options: [
        'Cyclones / ঘূৰ্ণিবতাহ',
        'Floods / বানপানী',
        'Earthquakes / ভূমিকম্প',
        'Avalanches / হিমপ্ৰপাত',
      ],
      correctAnswerIndex: 2,
      explanation: "Assam lies in a high-seismic zone (Zone V); the lightweight, timber-and-bamboo Ikra (Assam-type) construction is flexible and resists earthquake shaking well.\nঅসম উচ্চ ভূমিকম্প অঞ্চলত (Zone V) অৱস্থিত; ইক্ৰা (অসমীয়া-ধৰণ) ঘৰৰ হালকা কাঠ-বাঁহ গঠন নমনীয় আৰু ভূমিকম্পৰ কম্পন সহজে সহ্য কৰিব পাৰে।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Which is the only recognised hill station of Assam?\nঅসমৰ একমাত্ৰ স্বীকৃত পাহাৰীয়া ষ্টেচন কোন?",
      options: [
        'Haflong / হাফলং',
        'Tezpur / তেজপুৰ',
        'Jatinga / যাতিংগা',
        'Umrangso / উম্ৰাংছো',
      ],
      correctAnswerIndex: 0,
      explanation: "Haflong, the headquarters of Dima Hasao district, is the only hill station of Assam, situated at an altitude of about 680 m above sea level.\nডিমা হাছাও জিলাৰ সদৰ ঠাই হাফলং অসমৰ একমাত্ৰ পাহাৰীয়া ষ্টেচন, সাগৰপৃষ্ঠৰ পৰা প্ৰায় ৬৮০ মিটাৰ উচ্চতাত অৱস্থিত।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Which river is regarded as the lifeline of Assam?\nকোন নদীক অসমৰ জীৱনৰেখা হিচাপে গণ্য কৰা হয়?",
      options: [
        'Brahmaputra / ব্ৰহ্মপুত্ৰ',
        'Barak / বৰাক',
        'Subansiri / সুৱনশিৰি',
        'Manas / মানস',
      ],
      correctAnswerIndex: 0,
      explanation: "The Brahmaputra is regarded as the lifeline of Assam; its valley supports the majority of the state's agriculture, transport and settlements.\nব্ৰহ্মপুত্ৰক অসমৰ জীৱনৰেখা হিচাপে গণ্য কৰা হয়; ইয়াৰ উপত্যকাই ৰাজ্যখনৰ বেছিভাগ কৃষি, পৰিবহণ আৰু বসতি আগুৰি আছে।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },
    {
      question: "Which city serves as the capital of Assam?\nঅসমৰ ৰাজধানী হিচাপে কোনখন চহৰে কাম কৰে?",
      options: [
        'Guwahati / গুৱাহাটী',
        'Dispur / দিছপুৰ',
        'Jorhat / যোৰহাট',
        'Tezpur / তেজপুৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "Dispur, a locality within Guwahati, is the capital of Assam; the Assam Secretariat and Assembly are located there.\nগুৱাহাটীৰ ভিতৰত থকা দিছপুৰ অসমৰ ৰাজধানী; অসম সচিবালয় আৰু বিধানসভা ইয়াতেই অৱস্থিত।",
      subjectTopic: 'Assam Geography',
      marks: 2,
    },

    // --- Economic Geography (6) ---
    {
      question: "Assam is the largest producer of which commodity in India?\nঅসম ভাৰতত কোন সামগ্ৰীৰ আটাইতকৈ ডাঙৰ উৎপাদক?",
      options: [
        'Coffee / কফি',
        'Rubber / ৰবৰ',
        'Tea / চাহ',
        'Sugarcane / আখি',
      ],
      correctAnswerIndex: 2,
      explanation: "Assam is the largest tea-producing state in India, contributing more than half of India's total tea production; it is famous for its orthodox CTC and Assam tea.\nঅসম ভাৰতৰ আটাইতকৈ ডাঙৰ চাহ উৎপাদক ৰাজ্য, যিয়ে ভাৰতৰ মুঠ চাহ উৎপাদনৰ আধাতকৈ অধিক যোগান ধৰে; অৰ্থ'ডক্স CTC আৰু অসম চাহৰ বাবে বিখ্যাত।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
    {
      question: "The Digboi refinery, established in 1901, holds which distinction?\n১৯০১ চনত স্থাপিত ডিগবৈ তেল শোধনাগাৰৰ কি বিশেষত্ব আছে?",
      options: [
        "India's largest refinery / ভাৰতৰ আটাইতকৈ ডাঙৰ শোধনাগাৰ",
        'Most modern refinery / আটাইতকৈ আধুনিক শোধনাগাৰ',
        "India's first coal plant / ভাৰতৰ প্ৰথম কয়লা প্ৰকল্প",
        "Asia's first oil refinery / এছিয়াৰ প্ৰথম তেল শোধনাগাৰ",
      ],
      correctAnswerIndex: 3,
      explanation: "The Digboi refinery, commissioned in 1901 in Tinsukia district, is regarded as Asia's first oil refinery and one of the oldest operating refineries in the world.\n১৯০১ চনত তিনিচুকীয়া জিলাত কাৰ্যক্ষম হোৱা ডিগবৈ শোধনাগাৰক এছিয়াৰ প্ৰথম তেল শোধনাগাৰ আৰু বিশ্বৰ পুৰণি চালু শোধনাগাৰসমূহৰ এটা হিচাপে গণ্য কৰা হয়।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
    {
      question: "Muga silk, for which Assam is famous, is also known by which name?\nঅসমৰ বাবে বিখ্যাত মুগা ৰেচমক আন কি নামেৰে জনা যায়?",
      options: [
        'Golden silk / সোণালী ৰেচম',
        'White silk / বগা ৰেচম',
        'Red silk / ৰঙা ৰেচম',
        "Black silk / ক'লা ৰেচম",
      ],
      correctAnswerIndex: 0,
      explanation: "Muga silk, produced only in Assam from the Antheraea assamensis silkworm, has a natural golden-yellow colour and is renowned for its durability and lustre.\nকেৱল অসমত উৎপাদিত মুগা ৰেচম Antheraea assamensis পলুৰ পৰা সংগৃহীত, স্বাভাৱিক সোণালী-হালধীয়া ৰঙৰ বাবে ইয়াক 'সোণালী ৰেচম' বুলিও কোৱা হয়।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
    {
      question: "The Numaligarh Refinery of Assam is located in which district?\nঅসমৰ নুমালিগড় শোধনাগাৰ কোন জিলাত অৱস্থিত?",
      options: [
        'Tinsukia / তিনিচুকীয়া',
        'Golaghat / গোলাঘাট',
        'Dibrugarh / ডিব্ৰুগড়',
        'Sivasagar / শিৱসাগৰ',
      ],
      correctAnswerIndex: 1,
      explanation: "The Numaligarh Refinery Limited (NRL) is located at Numaligarh in Golaghat district; it was set up as a grass-roots refinery based on Assam crude oil.\nনুমালিগড় শোধনাগাৰ লিমিটেড (NRL) গোলাঘাট জিলাৰ নুমালিগড়ত অৱস্থিত; ই অসম কেঁচা তেলৰ ওপৰত ভিত্তি কৰি এটা গ্ৰাছ-ৰুটছ শোধনাগাৰ হিচাপে স্থাপন কৰা হৈছিল।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
    {
      question: "Which city hosts the major tea auction centre of Assam?\nঅসমৰ প্ৰধান চাহ নিলাম কেন্দ্ৰ কোনখন চহৰত অৱস্থিত?",
      options: [
        'Jorhat / যোৰহাট',
        'Dibrugarh / ডিব্ৰুগড়',
        'Guwahati / গুৱাহাটী',
        'Tinsukia / তিনিচুকীয়া',
      ],
      correctAnswerIndex: 2,
      explanation: "The Guwahati Tea Auction Centre (GTAC), established in 1970, is one of the largest tea auction centres in the world and the main auction hub for Assam tea.\n১৯৭০ চনত স্থাপিত গুৱাহাটী চাহ নিলাম কেন্দ্ৰ (GTAC) বিশ্বৰ ডাঙৰ চাহ নিলাম কেন্দ্ৰসমূহৰ এটা আৰু অসম চাহৰ প্ৰধান নিলাম কেন্দ্ৰ।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
    {
      question: "In which year was the historic Digboi oil well first successfully drilled?\nডিগবৈৰ ঐতিহাসিক তেল কূপ প্ৰথমবাৰৰ বাবে সফলভাৱে কোন বছৰত খনন কৰা হৈছিল?",
      options: [
        '1866 / ১৮৬৬',
        '1901 / ১৯০১',
        '1889 / ১৮৮৯',
        '1947 / ১৯৪৭',
      ],
      correctAnswerIndex: 2,
      explanation: "The first commercially successful oil well at Digboi was drilled in 1889 by the Assam Railway and Trading Company, marking the beginning of India's oil industry.\n১৮৮৯ চনত অসম ৰেলৱে এণ্ড ট্ৰেডিং কোম্পানীয়ে ডিগবৈত প্ৰথম বাৰৰ বাবে সফলভাৱে তেল কূপ খনন কৰে, যি ভাৰতৰ তেল উদ্যোগৰ সূচনা বুজায়।",
      subjectTopic: 'Economic Geography',
      marks: 2,
    },
  ],
};
