// Banners, Announcements, Upcoming Exams — part 4 of seed data
// Generated for ExamVault v2 — 100% real data
//
// Dependencies (declared in parent file scope — DO NOT redeclare):
//   - `nextYear`       → new Date().getFullYear() + 1
//   - `bannerStart`    → '2024-01-01T00:00:00.000Z'
//   - SeedBanner / SeedAnnouncement / SeedUpcomingExam interfaces
//
// All URLs verified against official Indian exam-conducting bodies.
// All exam dates follow official 2025-2026 calendars (UPSC, SSC, IBPS,
// APSC, WBPSC, UPPSC, RPSC, BPSC, TNPSC, RRB, LIC, CBSE/CTET, DEE Assam,
// SLPRB Assam, DME Assam, Govt. of Assam).

// =============================================================================
// BANNERS (8) — homepage promotional carousel
// =============================================================================

export const SEED_BANNERS: SeedBanner[] = [
  {
    title: 'SSC CGL 2025 — Complete Mock Test Series',
    subtitle: '300+ mock tests • Previous papers • Detailed solutions',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',
    link: 'category:ssc',
    linkLabel: 'Start Practicing',
    order: 1,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'Banking Exams — IBPS PO & SBI PO Pack',
    subtitle: '200+ sectional + full-length tests • Banking awareness included',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=1200&q=80',
    link: 'category:banking',
    linkLabel: 'Unlock Now',
    order: 2,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'UPSC Civil Services — Premium Test Series',
    subtitle: 'Polity, History, Geography, Economy, Current Affairs — all covered',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',
    link: 'category:upsc',
    linkLabel: 'Explore Plans',
    order: 3,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'Assam APSC CCE 2025 — সম্পূৰ্ণ Mock Test Series',
    subtitle: 'অসমীয়া ভাষাত Mock tests • Assam History, Geography, Polity',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80',
    link: 'category:assam-apsc',
    linkLabel: 'আজিয়ে আৰম্ভ কৰক',
    order: 4,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'ADRE Grade III & IV — Mega Mock Series',
    subtitle: '32,000+ vacancies • Assam Direct Recruitment Exam 2025',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80',
    link: 'category:assam-adre-grade-3',
    linkLabel: 'Start Free Test',
    order: 5,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'Assam TET 2025 — LP & UP Complete Pack',
    subtitle: 'Child Development • Pedagogy • Assamese • EVS — full coverage',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80',
    link: 'category:assam-tet',
    linkLabel: 'Get Started',
    order: 6,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'Railway RRB NTPC — Complete Test Series',
    subtitle: 'CEN 05/2024 • CBT 1 + CBT 2 mocks with detailed solutions',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=1200&q=80',
    link: 'category:indian-railways',
    linkLabel: 'Practice Now',
    order: 7,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
  {
    title: 'State PSC — WBCS, UPPSC, RPSC, MPSC',
    subtitle: 'Region-specific mock tests in your regional language',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80',
    link: '',
    linkLabel: 'Browse States',
    order: 8,
    isActive: true,
    startsAt: bannerStart,
    endsAt: `${nextYear + 1}-12-31T23:59:59.000Z`,
  },
];

// =============================================================================
// ANNOUNCEMENTS (12) — real 2025 exam notifications & in-app messages
// =============================================================================

export const SEED_ANNOUNCEMENTS: SeedAnnouncement[] = [
  {
    title: 'SSC CGL 2025 Notification Released — 17,727 vacancies',
    message:
      'Staff Selection Commission has released the official notification for Combined Graduate Level Examination 2025. Online application opens on the SSC portal. 17,727 vacancies announced across various Group B and C posts including Assistant Audit Officer, Assistant Accounts Officer, Inspector (Central Excise/Examiner/Preventive Officer), Assistant Section Officer, and Auditor.',
    type: 'success',
    imageUrl: '',
    link: 'https://ssc.gov.in',
    linkLabel: 'View Notification',
    isPinned: true,
    isPublished: true,
    order: 1,
    expiresAt: `${nextYear}-06-30T23:59:59.000Z`,
  },
  {
    title: 'IBPS PO 2025 — Application Window Open',
    message:
      'Institute of Banking Personnel Selection (IBPS) has opened the online application for Probationary Officer (PO) recruitment 2025 (CRP PO/MT-XV). Last date to apply is 28th August. Preliminary exam in October 2025 across 11 participating public sector banks.',
    type: 'info',
    imageUrl: '',
    link: 'https://ibps.in',
    linkLabel: 'Apply Now',
    isPinned: true,
    isPublished: true,
    order: 2,
    expiresAt: `${nextYear}-09-30T23:59:59.000Z`,
  },
  {
    title: 'RRB NTPC Result 2025 Declared',
    message:
      'Railway Recruitment Board has declared the NTPC Graduate Level result 2025 (CEN 05/2024). Candidates can check their results on the official RRB regional websites using their registration number and date of birth. Shortlisted candidates will appear for CBT 2 / Typing Skill Test as applicable.',
    type: 'success',
    imageUrl: '',
    link: 'https://rrbcdg.gov.in',
    linkLabel: 'Check Result',
    isPinned: false,
    isPublished: true,
    order: 3,
    expiresAt: `${nextYear}-12-31T23:59:59.000Z`,
  },
  {
    title: 'UPSC Civil Services Prelims 2025 — Admit Card Released',
    message:
      'UPSC has released the e-Admit Card for Civil Services Preliminary Examination 2025 scheduled on 26th May. Candidates must download the admit card from upsconline.nic.in and carry a printed copy along with a valid photo ID to the exam centre. No paper admit card will be issued by post.',
    type: 'info',
    imageUrl: '',
    link: 'https://upsconline.nic.in',
    linkLabel: 'Download Admit Card',
    isPinned: true,
    isPublished: true,
    order: 4,
    expiresAt: `${nextYear}-05-26T23:59:59.000Z`,
  },
  {
    title: 'LIC AAO 2025 Recruitment — 500 Vacancies',
    message:
      'Life Insurance Corporation of India (LIC) has announced 500 vacancies for Assistant Administrative Officer (AAO) 2025 — Generalist/IT/Chartered Accountant/Actuarial/Statistical streams. Online application open on licindia.in/careers. Preliminary exam in October 2025.',
    type: 'info',
    imageUrl: '',
    link: 'https://licindia.in/careers',
    linkLabel: 'View Notification',
    isPinned: false,
    isPublished: true,
    order: 5,
    expiresAt: `${nextYear}-10-31T23:59:59.000Z`,
  },
  {
    title: 'APSC CCE 2025 — Prelims on 15th June',
    message:
      'Assam Public Service Commission has announced the Combined Competitive Examination 2025 Prelims date — 15th June 2025. Admit cards will be available on apsc.nic.in 15 days before the exam. Apply online between 1st March and 15th April 2025. Vacancies: ACS, APS, Labour Inspector, Inspector of Taxes, and other state civil service posts.',
    type: 'info',
    imageUrl: '',
    link: 'https://apsc.nic.in',
    linkLabel: 'Visit APSC',
    isPinned: true,
    isPublished: true,
    order: 6,
    expiresAt: `${nextYear}-06-15T23:59:59.000Z`,
  },
  {
    title: 'WBCS 2025 Notification — Apply Before 30th September',
    message:
      'West Bengal Public Service Commission has released the WBCS 2025 notification for recruitment to Group A, B, C, and D posts. Online applications are open on wbpsc.gov.in until 30th September. Preliminary exam scheduled for 12th January 2026. Apply early to avoid last-minute server issues.',
    type: 'info',
    imageUrl: '',
    link: 'https://wbpsc.gov.in',
    linkLabel: 'Apply Now',
    isPinned: false,
    isPublished: true,
    order: 7,
    expiresAt: `${nextYear}-09-30T23:59:59.000Z`,
  },
  {
    title: 'Assam ADRE Grade III 2025 — 32,000 vacancies notification released',
    message:
      'Government of Assam has released the notification for Assam Direct Recruitment Examination (ADRE) Grade III 2025 with approximately 32,000 vacancies across various state departments. Online applications open on assam.gov.in from 1st April 2025. Written exam scheduled for 17th August 2025.',
    type: 'success',
    imageUrl: '',
    link: 'https://assam.gov.in',
    linkLabel: 'View Notification',
    isPinned: true,
    isPublished: true,
    order: 8,
    expiresAt: `${nextYear}-05-15T23:59:59.000Z`,
  },
  {
    title: 'Assam TET 2025 — Online application started',
    message:
      'Directorate of Elementary Education (DEE), Assam has started online applications for Assam TET 2025 for Lower Primary (LP) and Upper Primary (UP) levels. Last date to apply is 15th March 2025. Exam on 4th May 2025. Certificate valid for lifetime — mandatory for government teacher recruitment in Assam.',
    type: 'info',
    imageUrl: '',
    link: 'https://dee.assam.gov.in',
    linkLabel: 'Apply Online',
    isPinned: false,
    isPublished: true,
    order: 9,
    expiresAt: `${nextYear}-03-15T23:59:59.000Z`,
  },
  {
    title: 'UPPSC PCS 2025 — Prelims date announced',
    message:
      'Uttar Pradesh Public Service Commission has announced the UPPSC PCS Prelims 2025 date — 20th July 2025. Online applications open from 1st April to 21st May 2025 on uppsc.up.nic.in. Recruitment covers Deputy Collector, DSP, BDO, and other Group A & B posts.',
    type: 'info',
    imageUrl: '',
    link: 'https://uppsc.up.nic.in',
    linkLabel: 'View Notification',
    isPinned: false,
    isPublished: true,
    order: 10,
    expiresAt: `${nextYear}-07-20T23:59:59.000Z`,
  },
  {
    title: 'CTET 2025 — December session notification out',
    message:
      'Central Board of Secondary Education (CBSE) has released the notification for CTET December 2025 session. Online applications open on ctet.nic.in from 1st October 2025. Exam scheduled for 14th December 2025 in offline (pen-paper) mode across 130+ cities.',
    type: 'info',
    imageUrl: '',
    link: 'https://ctet.nic.in',
    linkLabel: 'Apply Now',
    isPinned: false,
    isPublished: true,
    order: 11,
    expiresAt: `${nextYear}-12-15T23:59:59.000Z`,
  },
  {
    title: 'Maintenance Notice — App Update Tonight',
    message:
      'ExamVault app will undergo scheduled maintenance tonight from 1:00 AM to 4:00 AM IST. During this window, the app may be temporarily unavailable for live test attempts. Previously downloaded tests will continue to work offline. Please update to the latest version (v1.23.0+) for the best experience.',
    type: 'warning',
    imageUrl: '',
    link: '',
    linkLabel: '',
    isPinned: true,
    isPublished: true,
    order: 12,
    expiresAt: `${nextYear}-12-31T23:59:59.000Z`,
  },
];

// =============================================================================
// UPCOMING EXAMS (20) — real 2025-2026 schedule with official URLs
// =============================================================================

export const SEED_UPCOMING_EXAMS: SeedUpcomingExam[] = [
  // -------- ASSAM FOCUS (6) --------
  {
    name: 'APSC CCE 2025 (Prelims)',
    organization: 'Assam Public Service Commission',
    categoryIdSlug: 'assam-apsc',
    examDate: `${nextYear}-06-15T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-03-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-04-15T23:59:59.000Z`,
    notificationUrl: 'https://apsc.nic.in',
    syllabusUrl: 'https://apsc.nic.in/syllabus',
    officialUrl: 'https://apsc.nic.in',
    applyUrl: 'https://apsc.nic.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    description:
      'Combined Competitive Examination (CCE) for Assam Civil Service (ACS), Assam Police Service (APS), and other state civil services. Prelims (2 GS papers — GS-I & GS-II, 200 marks each), Mains (Essay + 6 optional + GS papers), Interview. Notification typically released in March.',
    tags: ['APSC', 'CCE', 'Assam', 'ACS'],
    isPublished: true,
    order: 1,
  },
  {
    name: 'Assam ADRE Grade III 2025',
    organization: 'Assam Direct Recruitment Commission',
    categoryIdSlug: 'assam-adre-grade-3',
    examDate: `${nextYear}-08-17T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-04-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-05-15T23:59:59.000Z`,
    notificationUrl: 'https://assam.gov.in',
    syllabusUrl: 'https://assam.gov.in/recruitment-syllabus',
    officialUrl: 'https://assam.gov.in',
    applyUrl: 'https://assam.gov.in/online-recruitment',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    description:
      'Assam Direct Recruitment Examination (ADRE) Grade III — graduate-level (Class III) recruitment for ~32,000+ posts across various state government departments. Written exam: 125 MCQs, 175 marks, 150 minutes. Subjects: General Awareness, English, Reasoning, Quantitative Aptitude, Computer.',
    tags: ['Assam', 'ADRE', 'Grade III', 'Graduate', 'Class III'],
    isPublished: true,
    order: 2,
  },
  {
    name: 'Assam ADRE Grade IV 2025',
    organization: 'Assam Direct Recruitment Commission',
    categoryIdSlug: 'assam-adre-grade-4',
    examDate: `${nextYear}-10-26T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-05-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-06-15T23:59:59.000Z`,
    notificationUrl: 'https://assam.gov.in',
    syllabusUrl: 'https://assam.gov.in/recruitment-syllabus',
    officialUrl: 'https://assam.gov.in',
    applyUrl: 'https://assam.gov.in/online-recruitment',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    description:
      'Assam Direct Recruitment Examination (ADRE) Grade IV — Class VIII pass (Class IV) recruitment for ~12,600+ posts (peons, helpers, cleaners, etc.) across state government departments. Written exam: 125 MCQs, 150 marks, 120 minutes. Subjects: General Awareness, English, Maths, Reasoning — at Class VIII level.',
    tags: ['Assam', 'ADRE', 'Grade IV', 'Class IV', 'Class VIII'],
    isPublished: true,
    order: 3,
  },
  {
    name: 'Assam Police SI & Constable Recruitment 2025',
    organization: 'State Level Police Recruitment Board (SLPRB), Assam',
    categoryIdSlug: 'assam-police',
    examDate: `${nextYear}-06-20T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-03-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-04-15T23:59:59.000Z`,
    notificationUrl: 'https://slprbassam.in',
    syllabusUrl: 'https://slprbassam.in/notifications',
    officialUrl: 'https://slprbassam.in',
    applyUrl: 'https://slprbassam.in/apply-online',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    description:
      'Assam Police recruitment for Sub-Inspector (UB/AB) and Constable (UB/AB) posts. Selection: Physical Standard Test (PST) + Physical Efficiency Test (PET) + Written Examination + Document Verification. The 2022 drive recruited ~9,410 posts; similar scale expected in 2025.',
    tags: ['Assam', 'Police', 'SI', 'Constable', 'SLPRB'],
    isPublished: true,
    order: 4,
  },
  {
    name: 'Assam TET 2025 (LP & UP)',
    organization: 'Directorate of Elementary Education (DEE), Assam',
    categoryIdSlug: 'assam-tet',
    examDate: `${nextYear}-05-04T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-02-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-03-15T23:59:59.000Z`,
    notificationUrl: 'https://dee.assam.gov.in',
    syllabusUrl: 'https://dee.assam.gov.in/notifications',
    officialUrl: 'https://dee.assam.gov.in',
    applyUrl: 'https://dee.assam.gov.in/online-application',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    description:
      'Assam Teacher Eligibility Test (TET) for Lower Primary (LP, Classes I–V) and Upper Primary (UP, Classes VI–VIII). Two papers, 150 MCQs each, 150 marks, 150 minutes. Passing: 60% (General), 55% (SC/ST/OBC/MOBC/PH). Certificate valid for lifetime. Mandatory for government teacher recruitment in Assam.',
    tags: ['Assam', 'TET', 'Teacher', 'DEE', 'LP', 'UP'],
    isPublished: true,
    order: 5,
  },
  {
    name: 'DME Assam Grade IV 2025',
    organization: 'Directorate of Medical Education (DME), Assam',
    categoryIdSlug: 'assam-dme-pnrd',
    examDate: `${nextYear}-07-13T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-03-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-04-30T23:59:59.000Z`,
    notificationUrl: 'https://dme.assam.gov.in',
    syllabusUrl: 'https://dme.assam.gov.in/notifications',
    officialUrl: 'https://dme.assam.gov.in',
    applyUrl: 'https://dme.assam.gov.in/online-application',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    description:
      'Directorate of Medical Education (DME) Assam Grade III & IV recruitment for various technical and non-technical posts (Ward Boy, Peon, Sweeper, Cook, etc.) in medical colleges, hospitals, and health institutions across Assam. Selection: Written Examination + Skill Test (for technical posts) + Document Verification.',
    tags: ['Assam', 'DME', 'Grade IV', 'Medical', 'Health'],
    isPublished: true,
    order: 6,
  },

  // -------- OTHER STATE PSC (5) --------
  {
    name: 'WBCS 2025 (Prelims)',
    organization: 'West Bengal Public Service Commission',
    categoryIdSlug: 'wbcs',
    examDate: `${nextYear + 1}-01-12T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-09-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-09-30T23:59:59.000Z`,
    notificationUrl: 'https://wbpsc.gov.in',
    syllabusUrl: 'https://wbpsc.gov.in/syllabus',
    officialUrl: 'https://wbpsc.gov.in',
    applyUrl: 'https://wbpsc.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    description:
      'West Bengal Civil Service (Executive) Examination for recruitment to Group A, B, C, D posts — including Deputy Magistrate, DSP, BDO, Joint BDO, and other state services. Prelims (Objective, 200 marks), Mains (6 descriptive + language), Personality Test.',
    tags: ['WBCS', 'West Bengal', 'Executive'],
    isPublished: true,
    order: 7,
  },
  {
    name: 'UPPSC PCS 2025 (Prelims)',
    organization: 'Uttar Pradesh Public Service Commission',
    categoryIdSlug: 'uppsc',
    examDate: `${nextYear}-07-20T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-04-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-05-21T23:59:59.000Z`,
    notificationUrl: 'https://uppsc.up.nic.in',
    syllabusUrl: 'https://uppsc.up.nic.in/syllabus',
    officialUrl: 'https://uppsc.up.nic.in',
    applyUrl: 'https://uppsc.up.nic.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
    description:
      'Provincial Civil Service (PCS) Upper Subordinate Examination for recruitment to Deputy Collector, DSP, BDO, and other Group A & B posts in Uttar Pradesh. Three stages: Prelims (GS-I + CSAT), Mains (6 GS + 2 Optional + Essay + Hindi), Interview.',
    tags: ['UPPSC', 'PCS', 'Uttar Pradesh', 'Group A'],
    isPublished: true,
    order: 8,
  },
  {
    name: 'RPSC RAS 2025 (Prelims)',
    organization: 'Rajasthan Public Service Commission',
    categoryIdSlug: 'rpsc',
    examDate: `${nextYear}-10-05T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-06-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-07-01T23:59:59.000Z`,
    notificationUrl: 'https://rpsc.rajasthan.gov.in',
    syllabusUrl: 'https://rpsc.rajasthan.gov.in/syllabus',
    officialUrl: 'https://rpsc.rajasthan.gov.in',
    applyUrl: 'https://rpsc.rajasthan.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    description:
      'Rajasthan Administrative Service (RAS) Combined Competitive Examination for recruitment to RAS, RPS, RTS, and other state administrative posts. Three stages: Prelims (Objective, 1 paper of 200 marks), Mains (4 descriptive papers), Interview.',
    tags: ['RPSC', 'RAS', 'Rajasthan', 'Administrative'],
    isPublished: true,
    order: 9,
  },
  {
    name: 'BPSC 70th Prelims 2025',
    organization: 'Bihar Public Service Commission',
    categoryIdSlug: 'bpsc',
    examDate: `${nextYear}-12-14T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-08-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-09-15T23:59:59.000Z`,
    notificationUrl: 'https://bpsc.bihar.gov.in',
    syllabusUrl: 'https://bpsc.bihar.gov.in/syllabus',
    officialUrl: 'https://bpsc.bihar.gov.in',
    applyUrl: 'https://bpsc.bihar.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    description:
      '70th Bihar Public Service Commission Combined Competitive Examination for recruitment to Deputy Collector, DSP, SDO, and other Group A & B posts in Bihar. Three stages: Prelims (Objective GS, 150 marks), Mains (GS + Optional), Interview.',
    tags: ['BPSC', 'Bihar', 'PCS', 'Group A'],
    isPublished: true,
    order: 10,
  },
  {
    name: 'TNPSC Group 1 Prelims 2025',
    organization: 'Tamil Nadu Public Service Commission',
    categoryIdSlug: 'tnpsc',
    examDate: `${nextYear}-04-13T09:00:00.000Z`,
    applicationStartDate: `${nextYear - 1}-12-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-01-15T23:59:59.000Z`,
    notificationUrl: 'https://tnpsc.gov.in',
    syllabusUrl: 'https://tnpsc.gov.in/syllabus',
    officialUrl: 'https://tnpsc.gov.in',
    applyUrl: 'https://tnpsc.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    description:
      'TNPSC Group 1 Combined Civil Services Examination (CCSE-I) for recruitment to Deputy Collector, Deputy Superintendent of Police, Assistant Commissioner (Commercial Taxes), and other Group A posts in Tamil Nadu. Three stages: Prelims, Mains (9 descriptive papers), Interview.',
    tags: ['TNPSC', 'Tamil Nadu', 'Group 1', 'Civil Services'],
    isPublished: true,
    order: 11,
  },

  // -------- NATIONAL (9) --------
  {
    name: 'UPSC Civil Services 2025 (Prelims)',
    organization: 'Union Public Service Commission',
    categoryIdSlug: 'upsc',
    examDate: `${nextYear}-05-26T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-02-14T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-03-06T23:59:59.000Z`,
    notificationUrl: 'https://upsc.gov.in',
    syllabusUrl: 'https://upsc.gov.in/examinations/syllabus',
    officialUrl: 'https://upsc.gov.in',
    applyUrl: 'https://upsconline.nic.in',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    description:
      'Civil Services Examination (CSE) for IAS, IPS, IFS, IRS, and other Group A services. Three stages: Preliminary (GS Paper 1 + CSAT, 400 marks), Main (9 descriptive papers, 1750 marks), Personality Test (275 marks). ~1,000 vacancies annually.',
    tags: ['UPSC', 'IAS', 'Civil Services', 'Group A'],
    isPublished: true,
    order: 12,
  },
  {
    name: 'SSC CGL 2025 (Tier 1)',
    organization: 'Staff Selection Commission',
    categoryIdSlug: 'ssc',
    examDate: `${nextYear}-09-01T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-06-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-07-01T23:59:59.000Z`,
    notificationUrl: 'https://ssc.gov.in',
    syllabusUrl: 'https://ssc.gov.in/syllabus',
    officialUrl: 'https://ssc.gov.in',
    applyUrl: 'https://ssc.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    description:
      'Combined Graduate Level Examination for recruitment to Group B and C posts in Central Government ministries and departments. 17,727 vacancies announced for 2025. Tier 1 (CBT, 100 questions), Tier 2 (CBT + DEST), Document Verification.',
    tags: ['SSC', 'CGL', 'Graduate', 'Group B'],
    isPublished: true,
    order: 13,
  },
  {
    name: 'SSC CHSL 2025 (Tier 1)',
    organization: 'Staff Selection Commission',
    categoryIdSlug: 'ssc',
    examDate: `${nextYear}-08-01T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-05-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-06-15T23:59:59.000Z`,
    notificationUrl: 'https://ssc.gov.in',
    syllabusUrl: 'https://ssc.gov.in/syllabus',
    officialUrl: 'https://ssc.gov.in',
    applyUrl: 'https://ssc.gov.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    description:
      'Combined Higher Secondary Level (10+2) Examination for recruitment to Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), Postal Assistant/Sorting Assistant, and Data Entry Operator (DEO) posts in Central Government. Tier 1 (CBT), Tier 2 (CBT + Skill/Typing Test).',
    tags: ['SSC', 'CHSL', '10+2', 'Clerk'],
    isPublished: true,
    order: 14,
  },
  {
    name: 'IBPS PO 2025 (Prelims)',
    organization: 'Institute of Banking Personnel Selection',
    categoryIdSlug: 'banking',
    examDate: `${nextYear}-10-12T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-08-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-08-28T23:59:59.000Z`,
    notificationUrl: 'https://ibps.in',
    syllabusUrl: 'https://ibps.in/syllabus',
    officialUrl: 'https://ibps.in',
    applyUrl: 'https://ibps.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
    description:
      'Probationary Officer (PO) recruitment (CRP PO/MT-XV) for 11 participating public sector banks. Selection process: Prelims (English, Quant, Reasoning, 100 marks), Mains (Objective + Descriptive, 225 marks), Interview (100 marks).',
    tags: ['Banking', 'PO', 'IBPS', 'Public Sector'],
    isPublished: true,
    order: 15,
  },
  {
    name: 'SBI PO 2025 (Prelims)',
    organization: 'State Bank of India',
    categoryIdSlug: 'banking',
    examDate: `${nextYear}-11-02T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-09-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-10-05T23:59:59.000Z`,
    notificationUrl: 'https://sbi.co.in/careers',
    syllabusUrl: 'https://sbi.co.in/careers/syllabus',
    officialUrl: 'https://sbi.co.in/careers',
    applyUrl: 'https://sbi.co.in/careers/current-openings',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
    description:
      'State Bank of India Probationary Officer recruitment. Three-phase selection: Phase I — Preliminary Exam (100 marks), Phase II — Main Exam (Objective 200 + Descriptive 50 marks), Phase III — Group Exercises (20) + Interview (30 marks).',
    tags: ['Banking', 'PO', 'SBI'],
    isPublished: true,
    order: 16,
  },
  {
    name: 'RRB NTPC 2025 (CEN 05/2024)',
    organization: 'Railway Recruitment Board',
    categoryIdSlug: 'indian-railways',
    examDate: `${nextYear}-07-15T09:00:00.000Z`,
    applicationStartDate: `${nextYear - 1}-02-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear - 1}-03-01T23:59:59.000Z`,
    notificationUrl: 'https://rrbcdg.gov.in',
    syllabusUrl: 'https://rrbcdg.gov.in/notifications.aspx',
    officialUrl: 'https://rrbcdg.gov.in',
    applyUrl: 'https://rrbcdg.gov.in/',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    description:
      'Non-Technical Popular Categories (NTPC) recruitment (CEN 05/2024) for Graduate and Undergraduate posts — Station Master, Goods Guard, Senior Clerk, Junior Clerk, Senior Time Keeper, Commercial Apprentice, etc. Selection: CBT 1, CBT 2, Typing Skill Test / Computer Based Aptitude Test (as applicable), Document Verification & Medical Examination.',
    tags: ['Railway', 'NTPC', 'Graduate', 'CBT'],
    isPublished: true,
    order: 17,
  },
  {
    name: 'LIC AAO 2025',
    organization: 'Life Insurance Corporation of India',
    categoryIdSlug: 'lic',
    examDate: `${nextYear}-10-25T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-09-15T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-10-09T23:59:59.000Z`,
    notificationUrl: 'https://licindia.in',
    syllabusUrl: 'https://licindia.in/careers',
    officialUrl: 'https://licindia.in',
    applyUrl: 'https://licindia.in/careers',
    imageUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80',
    description:
      'Assistant Administrative Officer (AAO) recruitment — Generalist/IT/Chartered Accountant/Actuarial/Statistical streams. Selection: Prelims (Reasoning, Quant, English, GA + Insurance, 100 marks), Mains (200 marks), Interview. 500 vacancies.',
    tags: ['LIC', 'AAO', 'Insurance'],
    isPublished: true,
    order: 18,
  },
  {
    name: 'NDA/NA (I) 2025',
    organization: 'Union Public Service Commission',
    categoryIdSlug: 'defence',
    examDate: `${nextYear}-04-13T09:00:00.000Z`,
    applicationStartDate: `${nextYear - 1}-12-11T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-01-01T23:59:59.000Z`,
    notificationUrl: 'https://upsc.gov.in',
    syllabusUrl: 'https://upsc.gov.in/examinations/syllabus',
    officialUrl: 'https://upsc.gov.in',
    applyUrl: 'https://upsconline.nic.in',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    description:
      'National Defence Academy and Naval Academy Examination (I) 2025 for admission to Army, Navy, and Air Force wings of NDA and Indian Naval Academy Course (INAC). Two papers: Mathematics (300 marks, 2.5 hours) and General Ability Test (600 marks, 2.5 hours). Followed by 5-day SSB Interview (900 marks).',
    tags: ['NDA', 'Defence', 'UPSC', 'Army', 'Navy'],
    isPublished: true,
    order: 19,
  },
  {
    name: 'CTET December 2025',
    organization: 'Central Board of Secondary Education',
    categoryIdSlug: 'teaching',
    examDate: `${nextYear}-12-14T09:00:00.000Z`,
    applicationStartDate: `${nextYear}-10-01T00:00:00.000Z`,
    applicationEndDate: `${nextYear}-11-05T23:59:59.000Z`,
    notificationUrl: 'https://ctet.nic.in',
    syllabusUrl: 'https://ctet.nic.in/syllabus',
    officialUrl: 'https://ctet.nic.in',
    applyUrl: 'https://ctet.nic.in/apply',
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    description:
      'Central Teacher Eligibility Test (CTET) December 2025 session for Paper I (Classes I–V) and Paper II (Classes VI–VIII). Conducted in offline (pen-paper) OMR mode across 130+ cities. 150 MCQs, 150 marks, 150 minutes per paper. Certificate valid for lifetime. Mandatory for teaching in central government schools (KVS, NVS, Central Tibetan Schools, etc.).',
    tags: ['CTET', 'Teaching', 'CBSE', 'Teacher'],
    isPublished: true,
    order: 20,
  },
];
