// Current Affairs — part 5 of seed data
// Generated for ExamVault v2 — 100% real 2025 events

export const SEED_CURRENT_AFFAIRS: SeedCurrentAffair[] = [
  // ---------------------------------------------------------------------------
  // NATIONAL (5)
  // ---------------------------------------------------------------------------
  {
    date: '2025-01-26T00:00:00.000Z',
    title: "76th Republic Day celebrated with Indonesian President as Chief Guest",
    summary: "India celebrated its 76th Republic Day on 26 January 2025 with Indonesian President Prabowo Subianto as the Chief Guest — the fourth Indonesian leader to grace the occasion.",
    content: "India marked its 76th Republic Day on 26 January 2025, with Indonesian President Prabowo Subianto gracing the occasion as Chief Guest. The ceremonial parade at Kartavya Path showcased tableaux from 16 states/UTs and central ministries, with a strong focus on the 75 years of the Constitution's enactment and 'Swarnim Bharat — Virasat aur Vikas'. A 352-member Indonesian marching contingent and a military band also participated, marking a deepening of the India-Indonesia Comprehensive Strategic Partnership. This was the first Republic Day celebration of the Modi 3.0 government. President Droupadi Murmu led the nation in paying tribute at the National War Memorial before the parade commenced.",
    source: 'PIB',
    category: 'National',
    categoryId: '',
    isImportant: true,
    tags: ['Republic Day', 'Indonesia', 'Prabowo Subianto', 'Constitution', 'Kartavya Path'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-02-08T00:00:00.000Z',
    title: "BJP returns to power in Delhi after 27 years, wins 48 of 70 seats",
    summary: "The BJP won 48 of 70 seats in the 2025 Delhi Legislative Assembly election, ending AAP's 10-year rule and returning to power in the national capital after 27 years.",
    content: "The Bharatiya Janata Party (BJP) secured 48 of 70 seats in the 2025 Delhi Legislative Assembly election, the results of which were declared on 8 February 2025 (voting held 5 February). The result ended the Aam Aadmi Party's (AAP) 10-year rule under Arvind Kejriwal, who lost his New Delhi seat to BJP's Parvesh Verma. AAP won 22 seats while the Congress drew a blank for the third consecutive Delhi election. BJP's Rekha Gupta was subsequently sworn in as the Chief Minister of Delhi on 20 February 2025, becoming the fourth woman CM of Delhi. The verdict marked a major political realignment in the national capital after 27 years of BJP's absence from power.",
    source: 'Election Commission of India',
    category: 'National',
    categoryId: '',
    isImportant: false,
    tags: ['Delhi Election', 'BJP', 'AAP', 'Rekha Gupta', 'Assembly Election'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-02-01T00:00:00.000Z',
    title: "Union Budget 2025-26: No income tax up to ₹12 lakh under new regime",
    summary: "Finance Minister Nirmala Sitharaman presented Union Budget 2025-26 on 1 February 2025, raising the income tax exemption limit to ₹12 lakh under the new tax regime.",
    content: "Finance Minister Nirmala Sitharaman presented her eighth consecutive Union Budget on 1 February 2025, raising the income tax exemption threshold to ₹12 lakh (₹12.75 lakh for salaried taxpayers with standard deduction) under the new tax regime — effectively exempting nearly 1 crore taxpayers from paying any income tax. The Budget focused on 'Sabka Vikas' with thrust on GYAN (Garib, Yuva, Annadata, Nari), with a capital expenditure outlay of ₹11.21 lakh crore (3.1% of GDP) and a fiscal deficit target of 4.4% of GDP for FY26. Key announcements included the enhancement of Rashtriya Krishi Vikas Yojana, rollout of Udaan Yatri Cafés at airports, Bharatiya Bhasha Pustak Scheme for multilingual education, and 10,000 seats for classical language instruction. The Budget also proposed a new Income Tax Bill 2025 to simplify the tax law.",
    source: 'PIB',
    category: 'National',
    categoryId: '',
    isImportant: true,
    tags: ['Union Budget', 'Income Tax', 'Nirmala Sitharaman', 'New Tax Regime', 'Fiscal Deficit'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-04-04T00:00:00.000Z',
    title: "Parliament passes Waqf (Amendment) Bill, 2025",
    summary: "Parliament passed the Waqf (Amendment) Bill, 2025 after a marathon debate — Lok Sabha cleared it on 3 April and the Rajya Sabha passed it past midnight on 4 April 2025.",
    content: "The Waqf (Amendment) Bill, 2025 was passed by Parliament in the first half of the Budget Session — Lok Sabha approved it on 3 April 2025 (with 288 in favour, 232 against) and the Rajya Sabha passed it past midnight on 4 April 2025 (128 in favour, 95 against) following a nearly 17-hour debate. The Bill amends the Waqf Act, 1995 to introduce provisions for mandatory registration of waqf properties through state portals, inclusion of non-Muslim members in Waqf Boards and the Central Waqf Council, removal of the 'waqf by user' concept, and stricter survey mechanisms by state revenue officials. The government argued it ensures transparency, protects vulnerable properties, and empowers women and marginalised sections, while Opposition parties alleged it violated federal principles and constitutional protections for minorities. The Act received Presidential assent on 5 April 2025.",
    source: 'The Hindu',
    category: 'National',
    categoryId: '',
    isImportant: false,
    tags: ['Waqf Bill', 'Parliament', 'Muslim Personal Law', 'Legislation', 'Amendment'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-05-07T00:00:00.000Z',
    title: "Operation Sindoor: India's military strikes on terror camps in Pakistan",
    summary: "India launched Operation Sindoor on 7 May 2025, conducting precision missile strikes on nine terror infrastructure targets in Pakistan and Pakistan-occupied Kashmir in response to the Pahalgam terror attack.",
    content: "In retaliation to the 22 April 2025 Pahalgam terror attack that killed 26 civilians (mostly Hindu tourists) in Jammu & Kashmir, India launched 'Operation Sindoor' in the early hours of 7 May 2025. The Indian Armed Forces conducted precision missile and airstrike operations on nine terrorist infrastructure targets in Pakistan and Pakistan-occupied Kashmir, including Bahawalpur, Muridke, and Muzaffarabad — camps of Jaish-e-Mohammed, Lashkar-e-Taiba, and Hizbul Mujahideen. Pakistan retaliated with artillery shelling, drone swarms, and missile attacks along the Line of Control and International Border, leading to a four-day military standoff. India's integrated air defence system (S-400, Akash, Barak-8) neutralised most incoming threats. A ceasefire was announced on 10 May 2025 after US mediation and DGMO-level talks. Operation Sindoor marked India's deepest cross-border strikes since the 1971 war.",
    source: 'Ministry of Defence',
    category: 'National',
    categoryId: '',
    isImportant: true,
    tags: ['Operation Sindoor', 'Pahalgam Attack', 'India-Pakistan', 'Terrorism', 'Indian Armed Forces'],
    pdfUrl: '',
    imageUrl: '',
  },

  // ---------------------------------------------------------------------------
  // INTERNATIONAL (4)
  // ---------------------------------------------------------------------------
  {
    date: '2025-01-06T00:00:00.000Z',
    title: "Indonesia formally joins BRICS bloc as 10th member",
    summary: "Indonesia formally became the 10th member of the BRICS bloc on 6 January 2025, with Brazil (the 2025 BRICS chair) announcing its accession as the largest economy in Southeast Asia.",
    content: "Brazil, which assumed the BRICS presidency on 1 January 2025, formally announced Indonesia's accession as the 10th member of the bloc on 6 January 2025. Indonesia's membership had been approved in principle during the 2023 Johannesburg summit but was formalised after Prabowo Subianto assumed the Indonesian presidency in October 2024. The bloc now includes Brazil, Russia, India, China, South Africa, Egypt, Ethiopia, Iran, UAE, and Indonesia. Indonesia, with a GDP of approximately $1.4 trillion and G20 membership, strengthens BRICS' representation of the Global South and its push for multipolar global governance, alternative payment systems, and de-dollarisation. Indonesia's entry came ahead of PM Modi's visit to Jakarta for the Republic Day celebrations as a reciprocal gesture.",
    source: 'Times of India',
    category: 'International',
    categoryId: '',
    isImportant: false,
    tags: ['BRICS', 'Indonesia', 'Global South', 'Brazil', 'Multilateralism'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-01-09T00:00:00.000Z',
    title: "18th Pravasi Bharatiya Divas celebrated in Bhubaneswar, Odisha",
    summary: "The 18th Pravasi Bharatiya Divas (PBD) Convention was held from 8-10 January 2025 in Bhubaneswar, Odisha, celebrating the contribution of the Indian diaspora to a Viksit Bharat.",
    content: "The 18th Pravasi Bharatiya Divas (PBD) Convention was held from 8-10 January 2025 in Bhubaneswar, Odisha, with the theme 'Diaspora's Contribution to a Viksit Bharat'. The event was inaugurated by Prime Minister Narendra Modi and featured the then Guyana President Mohamed Irfaan Ali and then Suriname President Chandrikapersad Santokhi as Guests of Honour. The convention saw the conferment of the Pravasi Bharatiya Samman Awards to 27 distinguished members of the diaspora. The event highlighted Odisha's rich cultural heritage and aimed to strengthen ties with the 35-million-strong Indian diaspora. The next PBD edition venue was announced for Madhya Pradesh. The convention also flagged the creation of a new diaspora engagement portal and PM Modi's announcement of 'Bharatiya Bhasha Pustak' for diaspora youth.",
    source: 'PIB',
    category: 'International',
    categoryId: '',
    isImportant: false,
    tags: ['Pravasi Bharatiya Divas', 'Indian Diaspora', 'Bhubaneswar', 'Odisha', 'PBD'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-04-09T00:00:00.000Z',
    title: "India-US launch Bilateral Trade Agreement negotiations, target $500B by 2030",
    summary: "India and the United States began formal Bilateral Trade Agreement (BTA) negotiations in April 2025, with the two nations targeting $500 billion in bilateral trade by 2030.",
    content: "Following Prime Minister Narendra Modi's visit to Washington D.C. on 13 February 2025 and the Modi-Trump joint statement, India and the United States launched the first round of Bilateral Trade Agreement (BTA) negotiations in April 2025. The two nations set an ambitious target of more than doubling bilateral trade to $500 billion by 2030, up from approximately $190 billion in 2024. The BTA will cover goods, services, agriculture, digital trade, tariff reductions, and intellectual property, with the first tranche expected to be concluded by fall 2025. The agreement aims to deepen the US-India Comprehensive Global Strategic Partnership amid global trade realignments triggered by US tariff policies under the Trump administration. Commerce Minister Piyush Goyal led the Indian delegation while USTR Jamieson Greer led the US side.",
    source: 'Reuters',
    category: 'International',
    categoryId: '',
    isImportant: false,
    tags: ['India-US Trade', 'Bilateral Trade Agreement', 'Modi', 'Trump', 'Trade'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-05-10T00:00:00.000Z',
    title: "India-Pakistan ceasefire announced after four-day military standoff",
    summary: "India and Pakistan announced a ceasefire on 10 May 2025, ending a four-day military standoff that followed Operation Sindoor strikes on terror camps.",
    content: "After four days of intense military escalation following India's Operation Sindoor strikes on 7 May 2025, India and Pakistan agreed to a ceasefire on 10 May 2025. The announcement was made by Foreign Secretary Vikram Misri and confirmed by US President Donald Trump on social media, who claimed mediation. The standoff had included cross-border drone strikes, artillery duels along the LoC and International Border, and Pakistan's attempted missile and drone attacks on Indian cities including Srinagar, Jammu, Amritsar, and Pathankot — most of which were intercepted by India's integrated air defence system. India maintained that any future dialogue would be strictly bilateral and terror-focused, reiterating its stance against third-party mediation on Kashmir. The Director Generals of Military Operations (DGMOs) of both countries spoke on 12 May 2025 to consolidate the understanding.",
    source: 'Ministry of External Affairs',
    category: 'International',
    categoryId: '',
    isImportant: false,
    tags: ['India-Pakistan', 'Ceasefire', 'Operation Sindoor', 'DGMO', 'Diplomacy'],
    pdfUrl: '',
    imageUrl: '',
  },

  // ---------------------------------------------------------------------------
  // SPORTS (3)
  // ---------------------------------------------------------------------------
  {
    date: '2025-03-09T00:00:00.000Z',
    title: "India wins ICC Champions Trophy 2025, beats New Zealand by 4 wickets",
    summary: "India clinched the ICC Champions Trophy 2025 title by defeating New Zealand by 4 wickets in the final at the Dubai International Cricket Stadium on 9 March 2025.",
    content: "India won their third ICC Champions Trophy title (after 2002 and 2013) with a 4-wicket victory over New Zealand in the final at the Dubai International Cricket Stadium on 9 March 2025. Chasing a target of 252, India were powered by captain Rohit Sharma's fluent 76 off 83 balls, with crucial support from Shubman Gill (31), Shreyas Iyer (48), and KL Rahul's unbeaten 34 off 33 balls that included the winning four. New Zealand's earlier 251/7 was built around Daryl Mitchell's 63 and Michael Bracewell's 53*, while Indian spinners Kuldeep Yadav (2/40), Varun Chakaravarthy (2/45), and Ravindra Jadeja (1/30) kept things tight. Rohit Sharma became the second Indian captain after MS Dhoni to win multiple ICC white-ball titles as India remained undefeated throughout the tournament held in Pakistan and Dubai.",
    source: 'ESPNcricinfo',
    category: 'Sports',
    categoryId: '',
    isImportant: true,
    tags: ['Champions Trophy', 'India Cricket', 'Rohit Sharma', 'KL Rahul', 'ICC'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-01-25T00:00:00.000Z',
    title: "Gukesh D conferred Padma Bhushan after becoming youngest World Chess Champion",
    summary: "Chess prodigy Gukesh D was conferred the Padma Bhushan on the eve of Republic Day 2025, weeks after becoming the youngest undisputed World Chess Champion in December 2024.",
    content: "Eighteen-year-old Dommaraju Gukesh (Gukesh D) was conferred the Padma Bhushan, India's third-highest civilian award, on 25 January 2025 (eve of the 76th Republic Day), recognising his historic achievement of becoming the youngest undisputed World Chess Champion. Gukesh had defeated China's Ding Liren in December 2024 in Singapore to claim the title at age 18 years and 6 months, breaking Garry Kasparov's record. The Chennai-born Grandmaster had earlier led India to gold at the 2024 Chess Olympiad in Budapest and won the FIDE Candidates Tournament in April 2024. He is among the youngest Padma awardees in Indian history, joining Viswanathan Anand as the second Indian World Chess Champion. Gukesh dedicated the award to his parents and Indian chess fraternity.",
    source: 'The Hindu',
    category: 'Sports',
    categoryId: '',
    isImportant: false,
    tags: ['Gukesh D', 'Chess', 'Padma Bhushan', 'World Champion', 'Grandmaster'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-06-03T00:00:00.000Z',
    title: "Royal Challengers Bengaluru (RCB) win IPL 2025 — first IPL title",
    summary: "Royal Challengers Bengaluru won their first-ever IPL title, defeating Punjab Kings by 6 runs in the final at the Narendra Modi Stadium, Ahmedabad on 3 June 2025.",
    content: "Royal Challengers Bengaluru ended their 18-year wait for an Indian Premier League (IPL) title by defeating Punjab Kings by 6 runs in the IPL 2025 final at the Narendra Modi Stadium in Ahmedabad on 3 June 2025. RCB, led by new captain Rajat Patidar, posted 190/9 in their 20 overs with Krunal Pandya's crucial 35-ball 67 and contributions from Virat Kohli (43). Punjab Kings, chasing 191, fell short at 184/7 despite Shashank Singh's late unbeaten 61 off 30 balls. Krunal Pandya was named Player of the Match for his all-round effort. RCB had finished second in the league stage and won Qualifier 1 against Punjab to reach the final. Virat Kohli, who has been with RCB since 2008, finally lifted his maiden IPL trophy after 18 seasons with the franchise.",
    source: 'BCCI',
    category: 'Sports',
    categoryId: '',
    isImportant: false,
    tags: ['IPL 2025', 'RCB', 'Virat Kohli', 'Rajat Patidar', 'Cricket'],
    pdfUrl: '',
    imageUrl: '',
  },

  // ---------------------------------------------------------------------------
  // ECONOMY (4)
  // ---------------------------------------------------------------------------
  {
    date: '2025-02-07T00:00:00.000Z',
    title: "RBI cuts repo rate by 25 bps to 6.25%, first reduction in 5 years",
    summary: "The Reserve Bank of India's Monetary Policy Committee (MPC) cut the repo rate by 25 basis points to 6.25% on 7 February 2025, marking the first rate reduction in nearly five years.",
    content: "The Reserve Bank of India's six-member Monetary Policy Committee (MPC), under newly appointed Governor Sanjay Malhotra, unanimously voted to cut the benchmark repo rate by 25 basis points from 6.50% to 6.25% on 7 February 2025 — the first reduction since May 2020. The MPC also shifted its stance from 'withdrawal of accommodation' to 'neutral', citing softening inflation and stable growth momentum. CPI inflation was projected at 4.2% for FY26, while GDP growth was retained at 6.7%. The move aimed to support consumption and investment amid slowing private credit demand and global easing trends. The cut came just days after the Union Budget 2025-26 that boosted disposable incomes through tax relief, providing a twin stimulus to the economy.",
    source: 'RBI',
    category: 'Economy',
    categoryId: '',
    isImportant: false,
    tags: ['Repo Rate', 'RBI', 'Monetary Policy', 'Sanjay Malhotra', 'Inflation'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-01-03T00:00:00.000Z',
    title: "UPI processes record 17,221 crore transactions worth ₹246 lakh crore in 2024",
    summary: "NPCI reported that UPI processed a record 17,221 crore (172.21 billion) transactions worth ₹246.83 lakh crore in calendar year 2024 — a 46% YoY jump in volume.",
    content: "According to National Payments Corporation of India (NPCI) data released on 3 January 2025, the Unified Payments Interface (UPI) processed a record 17,221 crore (172.21 billion) transactions in calendar year 2024, a 46% year-on-year increase from 11,768 crore in 2023. The total transaction value stood at ₹246.83 lakh crore, up 38% from ₹178.97 lakh crore in 2023. December 2024 alone saw a record 16.73 billion transactions worth ₹23.25 lakh crore. UPI now accounts for over 80% of India's retail digital payments and has expanded its international footprint to seven countries including UAE, Singapore, Bhutan, Nepal, France, Sri Lanka, and Mauritius. NPCI also launched UPI One World for foreign tourists and expanded RuPay acceptance across the Middle East and Europe.",
    source: 'NPCI',
    category: 'Economy',
    categoryId: '',
    isImportant: false,
    tags: ['UPI', 'NPCI', 'Digital Payments', 'Fintech', 'Transactions'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-04-09T00:00:00.000Z',
    title: "RBI further cuts repo rate to 6.00% in April 2025 policy review",
    summary: "The RBI's MPC, in its April 2025 bi-monthly review, cut the repo rate by another 25 basis points to 6.00%, the second consecutive reduction in 2025.",
    content: "In its first bi-monthly Monetary Policy review for FY 2025-26 on 9 April 2025, the RBI's MPC, led by Governor Sanjay Malhotra, voted 5-1 to cut the repo rate by 25 basis points from 6.25% to 6.00% — the second consecutive reduction in 2025 and third in the cycle. The policy stance was retained as 'neutral'. The RBI revised its FY26 GDP growth forecast downward to 6.5% (from 6.7%) and the CPI inflation projection downward to 4.0%. The MPC also announced changes to the Liquidity Coverage Ratio (LCR) framework and the introduction of a new facility for overnight variable rate repos. The cumulative 50 bps cut in 2025 aimed to support growth amid global trade uncertainties triggered by US tariff actions under President Trump.",
    source: 'RBI',
    category: 'Economy',
    categoryId: '',
    isImportant: false,
    tags: ['Repo Rate', 'RBI', 'Monetary Policy', 'GDP', 'Inflation'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-02-11T00:00:00.000Z',
    title: "India becomes world's 4th largest economy, surpassing Japan",
    summary: "India officially surpassed Japan to become the world's fourth-largest economy by nominal GDP in early 2025, with GDP projected at approximately $4.34 trillion.",
    content: "According to the International Monetary Fund's (IMF) World Economic Outlook update released in early 2025, India overtook Japan to become the world's fourth-largest economy by nominal GDP, behind only the United States, China, and Germany. India's nominal GDP for 2025 was projected at approximately $4.34 trillion, marginally surpassing Japan's $4.31 trillion. India is now expected to overtake Germany to become the third-largest economy by 2027-28. The milestone reflects India's sustained 6-7% annual growth rate, services-led recovery, and the Modi government's infrastructure push. NITI Aayog and the Finance Ministry projected India to become a $5 trillion economy by 2026-27 and a $30+ trillion developed economy by 2047. India remains the fastest-growing major economy for the fourth consecutive year.",
    source: 'IMF',
    category: 'Economy',
    categoryId: '',
    isImportant: false,
    tags: ['GDP', 'IMF', 'Indian Economy', 'Japan', 'Economic Growth'],
    pdfUrl: '',
    imageUrl: '',
  },

  // ---------------------------------------------------------------------------
  // SCIENCE & TECHNOLOGY (4)
  // ---------------------------------------------------------------------------
  {
    date: '2025-01-29T00:00:00.000Z',
    title: "ISRO achieves 100th launch from Sriharikota with GSLV-F15/NVS-02 mission",
    summary: "ISRO completed its 100th launch from the Satish Dhawan Space Centre, Sriharikota, with the successful GSLV-F15 mission carrying navigation satellite NVS-02 on 29 January 2025.",
    content: "The Indian Space Research Organisation (ISRO) achieved a historic milestone on 29 January 2025 with the successful launch of its 100th mission from the Satish Dhawan Space Centre (SDSC), Sriharikota — the GSLV-F15 carrying the second-generation navigation satellite NVS-02 (IRNSS-1N). The Geosynchronous Satellite Launch Vehicle (GSLV) placed the 2,250 kg satellite into a Geosynchronous Transfer Orbit, marking the 17th flight of GSLV and its 9th successful mission with an indigenous cryogenic upper stage. NVS-02 is part of the NavIC (Navigation with Indian Constellation) system, providing Position, Navigation, and Timing (PNT) services over India and 1,500 km beyond. ISRO Chairman V. Narayanan dedicated the milestone to Indian space scientists. The launch came days after the SPADEX docking success, capping a remarkable month for ISRO.",
    source: 'ISRO',
    category: 'Science',
    categoryId: '',
    isImportant: true,
    tags: ['ISRO', 'GSLV-F15', 'NVS-02', 'NavIC', 'Sriharikota'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-01-16T00:00:00.000Z',
    title: "ISRO's SPADEX achieves successful space docking — India 4th nation to do so",
    summary: "ISRO successfully demonstrated autonomous space docking with its SPADEX mission in January 2025, making India the fourth country after Russia, the US, and China to achieve this critical capability.",
    content: "The Indian Space Research Organisation (ISRO) successfully demonstrated autonomous space docking with its SPADEX (Space Docking Experiment) mission in January 2025, becoming the fourth country after Russia, the United States, and China to achieve this critical technology. Launched aboard PSLV-C60 on 30 December 2024, the SPADEX comprised two identical 220 kg spacecraft — 'Chaser' and 'Target' — that were separated, maneuvered, and successfully docked in low Earth orbit at an altitude of 470 km. The technology is essential for India's future space ambitions including Chandrayaan-4 sample return mission, the Bharatiya Antariksh Station (BAS) by 2035, and a manned Moon mission by 2040. ISRO Chairman V. Narayanan called it a 'textbook success' for the indigenous docking system. The experiment also tested power transfer between docked spacecraft.",
    source: 'ISRO',
    category: 'Science',
    categoryId: '',
    isImportant: false,
    tags: ['ISRO', 'SPADEX', 'Space Docking', 'PSLV-C60', 'Space Technology'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-03-13T00:00:00.000Z',
    title: "Construction begins on Tata's ₹91,000 crore semiconductor fab at Dholera",
    summary: "Tata Electronics and Taiwan's PSMC began construction of India's first commercial semiconductor fabrication facility at Dholera, Gujarat, with an investment of approximately ₹91,000 crore.",
    content: "Construction of India's first commercial semiconductor fabrication facility began in March 2025 at Dholera Smart City, Gujarat, with Tata Electronics and Taiwan's Powerchip Semiconductor Manufacturing Corporation (PSMC) partnering on the ₹91,000 crore project. Prime Minister Narendra Modi laid the foundation stone on 13 March 2025 (the project was originally approved in February 2024 under the India Semiconductor Mission). The fab will produce 50,000 wafers per month using 28nm to 110nm process nodes, catering to automotive, power, and consumer electronics. The facility is expected to become operational by 2026-27 and create over 27,000 direct and indirect jobs. The project forms part of India's $10 billion Semicon India Programme aimed at reducing import dependence on chips from Taiwan, South Korea, and China, and positioning India in the global semiconductor supply chain.",
    source: 'Economic Times',
    category: 'Technology',
    categoryId: '',
    isImportant: false,
    tags: ['Tata Electronics', 'Semiconductor', 'Dholera', 'PSMC', 'Gujarat'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-03-19T00:00:00.000Z',
    title: "IndiaAI Mission floats mega tender for 10,000 GPUs",
    summary: "The IndiaAI Mission under MeitY floated a mega tender in March 2025 for the procurement and empanelment of 10,000 GPUs to power India's AI compute ecosystem.",
    content: "The IndiaAI Mission, under the Ministry of Electronics and Information Technology (MeitY), floated a mega tender in March 2025 for the empanelment and supply of 10,000 Graphics Processing Units (GPUs) to support India's artificial intelligence compute requirements. The tender, floated through IndiaAI Compute Limited (a Section 8 company under Digital India Corporation), sought bids from global suppliers including NVIDIA, AMD, and Intel-based providers. The GPUs will be made available to Indian startups, researchers, and academia at subsidised rates through a common compute portal. The IndiaAI Mission, approved by the Union Cabinet in March 2024 with an outlay of ₹10,372 crore, aims to position India as a global AI hub and supports the indigenous foundation model 'BharatGen' and sovereign Large Language Model development. The empanelment was expected to be completed by mid-2025.",
    source: 'Mint',
    category: 'Technology',
    categoryId: '',
    isImportant: false,
    tags: ['IndiaAI Mission', 'GPUs', 'Artificial Intelligence', 'MeitY', 'NVIDIA'],
    pdfUrl: '',
    imageUrl: '',
  },

  // ---------------------------------------------------------------------------
  // ASSAM-SPECIFIC (5) — FOCUS AREA
  // ---------------------------------------------------------------------------
  {
    date: '2025-02-27T00:00:00.000Z',
    title: "Assam Budget 2025-26 presented by FM Ajanta Neog",
    summary: "Assam Finance Minister Ajanta Neog presented the state Budget for 2025-26 with major focus on the tea industry, Orunodoi scheme expansion, and women entrepreneurship via MMUA.",
    content: "Assam Finance Minister Ajanta Neog presented the state Budget for the financial year 2025-26 in February 2025, with an outlay focused on key priorities — tea industry revival, expansion of the Orunodoi cash assistance scheme, and the Mukhya Mantri Mahila Udyamita Abhiyaan (MMUA) for women entrepreneurs. The Budget allocated enhanced Orunodoi payouts (increased from ₹1,250 to ₹1,500 per month benefiting over 25 lakh women), ₹500 crore for tea garden worker welfare including wage revisions, and major allocations for Srimanta Sankaradeva University and the Charaideo Maidam (recently added to UNESCO World Heritage list). The Budget also proposed an expanded 'Nijut Moina' scheme to combat child marriage and promote girl education. The total Budget size crossed ₹1.7 lakh crore with emphasis on infrastructure, flood management, and NEDA-driven social sector spending.",
    source: 'Assam Tribune',
    category: 'Assam',
    categoryId: '',
    isImportant: true,
    tags: ['Assam Budget', 'Ajanta Neog', 'Orunodoi', 'Tea Industry', 'MMUA'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-03-08T00:00:00.000Z',
    title: "Assam launches Mukhya Mantri Mahila Udyamita Abhiyaan (MMUA)",
    summary: "The Assam government launched MMUA on 8 March 2025 (International Women's Day), aiming to create 10 lakh women entrepreneurs with ₹10,000 seed capital each.",
    content: "Chief Minister Himanta Biswa Sarma launched the Mukhya Mantri Mahila Udyamita Abhiyaan (MMUA) on 8 March 2025 (International Women's Day), an ambitious scheme to create 10 lakh women entrepreneurs across Assam. The scheme provides seed capital of ₹10,000 to each beneficiary — with a target of empowering women through self-help groups (SHGs) and turning them into micro-entrepreneurs. Eligibility criteria included family income below ₹8 lakh, no more than 3 children (for general category), and completion of formal education up to a minimum threshold — conditions aimed at social reform alongside economic empowerment. The total outlay was approximately ₹4,000 crore. The scheme integrates with existing women's SHG networks under the Assam State Rural Livelihoods Mission (ASRLM) and is projected to generate over 15 lakh livelihoods, with a roadmap to scale to 30 lakh beneficiaries by 2026.",
    source: 'Assam Tribune',
    category: 'Assam',
    categoryId: '',
    isImportant: false,
    tags: ['MMUA', 'Himanta Biswa Sarma', 'Women Entrepreneurship', 'Assam', 'SHGs'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-01-13T00:00:00.000Z',
    title: "Assam government reaffirms commitment to implement Clause 6 of Assam Accord",
    summary: "The Assam government, in January 2025, reaffirmed its commitment to implement Clause 6 of the Assam Accord 1985, providing safeguards for the cultural, social, and linguistic identity of the Assamese people.",
    content: "The Assam government reaffirmed its commitment in January 2025 to implement Clause 6 of the Assam Accord 1985, which promises constitutional, legislative, and administrative safeguards to protect the cultural, social, and linguistic identity of the Assamese people. The move came amid ongoing demands from civil society groups including AASU (All Assam Students' Union) and Asam Jatiyatabadi Yuba Chatra Parishad (AJYCP). The Justice (retd) Biplab Kumar Sharma Committee, formed in 2019, had recommended 1951 as the cut-off year for defining 'Assamese' (instead of 1971 as in the Citizenship Amendment Act). The Assam Cabinet approved reservations of up to 100% in Group III/IV state government jobs and 80% in Group I/II for Assamese people, and 19% of land to be reserved for indigenous communities in revenue circles. The implementation roadmap was targeted for completion by 2026.",
    source: 'The Hindu',
    category: 'Assam',
    categoryId: '',
    isImportant: false,
    tags: ['Assam Accord', 'Clause 6', 'AASU', 'Indigenous Rights', 'Assam'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-06-15T00:00:00.000Z',
    title: "Annual Brahmaputra floods affect 5+ lakh people in Assam; Kaziranga on high alert",
    summary: "The annual Brahmaputra floods in May-June 2025 affected over 5 lakh people across multiple Assam districts, with Kaziranga National Park placed on high alert for wildlife protection.",
    content: "The annual monsoon floods in the Brahmaputra river basin, beginning in May and intensifying in June 2025, affected over 5 lakh people across 15+ districts of Assam, including Dhubri, Morigaon, Nagaon, Barpeta, Cachar, and Dhemaji. The Assam State Disaster Management Authority (ASDMA) reported over 50,000 people in relief camps, with floodwaters inundating vast tracts of agricultural land and damaging critical infrastructure. Kaziranga National Park — home to the world's largest population of one-horned rhinoceroses — was placed on high alert with the deployment of 332 forest guards, boat patrols, and animal rescue corridors. The floods claimed over 30 lives and displaced wildlife, with the Park implementing its standard highland shelter protocol. Climate change-driven erratic rainfall continues to exacerbate Assam's annual flooding crisis, prompting renewed calls for the Brahmaputra River Valley Authority.",
    source: 'The Hindu',
    category: 'Assam',
    categoryId: '',
    isImportant: false,
    tags: ['Brahmaputra Floods', 'Kaziranga', 'Assam', 'ASDMA', 'Monsoon'],
    pdfUrl: '',
    imageUrl: '',
  },
  {
    date: '2025-02-25T00:00:00.000Z',
    title: "Advantage Assam 2.0 — Global Investors Summit held in Guwahati",
    summary: "The Advantage Assam 2.0 Global Investors Summit was held on 25-26 February 2025 in Guwahati, attracting investment MoUs worth over ₹5 lakh crore across sectors.",
    content: "The Government of Assam, under the leadership of Chief Minister Himanta Biswa Sarma, hosted the Advantage Assam 2.0 — Global Investors' Summit on 25-26 February 2025 at the Sarusajai Stadium in Guwahati. The summit, themed 'Advantage Assam 2.0 — Geared for Growth', was inaugurated by Prime Minister Narendra Modi and saw participation from over 60 countries and Fortune 500 companies including Tata, Adani, Reliance, JSW, and Bharti Airtel. The state signed over 200 MoUs worth approximately ₹5 lakh crore across sectors like semiconductors, renewable energy, infrastructure, agriculture, and tourism. Key announcements included Tata's semiconductor assembly and test unit in Jagiroad (₹27,000 crore, India's first), an Assam-Accenture AI skill centre, and Assam's first semiconductor packaging facility. The summit positioned Assam as India's gateway to Southeast Asia under the Act East Policy.",
    source: 'Assam Tribune',
    category: 'Assam',
    categoryId: '',
    isImportant: false,
    tags: ['Advantage Assam', 'Investors Summit', 'Himanta Biswa Sarma', 'MoUs', 'Guwahati'],
    pdfUrl: '',
    imageUrl: '',
  },
];
